### ISSUE TITLE
QueryMultiple has unknown return type

### ISSUE THREAD

**Issue by timdooling** [DapperLib/Dapper#1006]
I am trying to employ QueryMultiple to return the results of a stored procedure.

The first is a single record from a table, and the second is a list of records that are linked to the first record by a foreign key.

Here is the code I am being forced to use:

                   try
                    {
                        using (IDbConnection dbConnection = ConnectionProvider.OpenConnection(CCCMapper.GetConnectionStringName("Request"), CCCMapper.GetDatabase("Request")))
                        {
                            dbConnection.Open();
                            if (CCCMapper.StoredProcedureExists("Request", "Request_s"))
                            {
                                dynamic reader = dbConnection.QueryMultiple("Request_s", param: new { id = id }, commandType: CommandType.StoredProcedure);
                                if (reader != null)
                                {
                                    result = reader.Read<_Request>()[0] as _Request;
                                    result.reviews = reader.Read<_Review>() as IEnumerable<_Review>;    
                                }
                            }
                        }
                    }
                    catch (SqlException sqlex)
                    {
                        Error(sqlex, false);
                        Comment(String.Format("type name: {0}", "Request"));
                        throw;
                    }
                    catch (Exception ex)
                    {
                        Error(ex);
                        Comment(String.Format("type name: {0}", "Request"));
                        throw;
                    }

The regular code won't work because I get an error that states "unknown return type of method 'QueryMultiple'".  The working type that is being returned is System.Collections.Generic.List, and most of the extension methods such as Single(), First(), etc., do not work.. I get this type of error for any attempt to use any List method:  'System.Collections.Generic.List' does not contain a definition for 'Single' .

I can't use var so I have to use dynamic.  If I use var, then it says unknown type of variable reader.

QueryMultiple shows the return type as Dapper.SqlMapper.GridReader but if I use that instead of dynamic or var I get an error on SqlMapper which states "unknown type or namespace "SqlMapper" of "Dapper".

I am using Visual Studio 2013 with some Telerik extensions:  JustCode, in particular.

The version of Dapper is 1.50.4.0.  I also use DapperExtensions, but I am getting away from it's use in favor of stored procedures.

How do I get rid of this problem without the ugly coding?

**Comment by mgravell** [comment]
That's... really weird. It sounds like a tooling error more than anything else - maybe a weird messed up reference. It *should* work with `var`  or `Dapper.SqlMapper.GridReader`, but... I genuinely have no idea how to repro this, since I don't have VS2013.

**Comment by timdooling** [comment]
My solution works because the compiler ignores the error, but I really want things to work as the examples suggest.

I have tested the system with Fiddler, and it works as expected with the api call returning the main record with the embedded records (I am using JSON), but I would prefer the system work as expected.

**Comment by NickCraver** [comment]
Given this was a VS 2013 issue specifically and we can't repro, going to close this out to cleanup. It's an interesting issue...but ultimately something with the VS tooling here, and on a much older version than we'd want to chase down (being up front here).
