### ISSUE TITLE
Cast error using AspenTech.SqlPlus provider

### ISSUE THREAD

**Issue by mvisconte** [DapperLib/Dapper#1090]
I am using Dapper with an ADO.NET driver for AspenTech's SQLPlus.

There is an issue when deserializing reals:

The query _select ip_graph_minimum as TestProp from kpidef where name = 'testKPI'_ returns, using the provider's GUI

      TestProp / 0.00

If I use Dapper, as follows:

```
public class Test
{
    public object TestProp { get; set; }
}
....

    IDbConnection connection = new AspenTech.SQLplus.SQLplusConnection("host=myHost");

    var result = connection.QuerySingle<Test>("select ip_graph_minimum as TestProp from kpidef where name = 'testKPI'");
    Console.WriteLine(result.TestProp.GetType());
    Console.WriteLine(result.TestProp.ToString());

```

It works fine, and returns

> System.Double
> 0

However, if I strongly type the property:

```
public class Test
{
    public Double TestProp { get; set; }
}
....

    IDbConnection connection = new AspenTech.SQLplus.SQLplusConnection("host=myHost");

    var result = connection.QuerySingle<Test>("select ip_graph_minimum as TestProp from kpidef where name = 'testKPI'");

```

An invalid cast exception is thrown:

> Error parsing column 0 (TestProp=0 - Double)

I am well aware that not a lot of people are using this provider, but it may help uncover a bigger issue.

**Comment by NickCraver** [comment]
I'm sorry we're completely unfamiliar with this provider. It seems like an underlying issue in the provider itself though, as we're casting the same way across all providers. That being said, I can't readily find the source for that provider to take a look either...

**Comment by NickCraver** [comment]
Without more to go on, we can't advise further here. If more info becomes available, we can re-open here.
