### ISSUE TITLE
Is it possible to not use data annotations

### ISSUE THREAD

**Issue by juanonsoftware** [DapperLib/Dapper#1133]
I see there are attributes like Table, Key...

Is it possible to not decorate the entities with these attribute? I mean another option to inject that logic into Dapper Contrib ?

Thanks,

**Comment by juanonsoftware** [comment]
I found now that I can use ITableNameMapper along with SqlMapperExtensions.TableNameMapper delegate to archive this.
Thanks

**Comment by chriswolf-nrg** [comment]
Can  you post an example?
