### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by netXiaoYang** [DapperLib/Dapper#1209]
Dapper-master\Dapper.Tests.Performance\Dapper.Tests.Performance.csproj : error  : 项目的默认 XML 命名空间必须为 MSBuild XML 命名空间。如果项目是用 MSBuild 2003 格式创建的，请将 xmlns="http://schemas.microsoft.com/developer/msbuild/2003" 添加到 <Project> 元素中。如果项目是用旧的 1.0 或 1.2 格式创建的，请将其转换为 MSBuild 2003 格式

**Comment by NickCraver** [comment]
It looks like you tried to open things with a much older version of MSBuild in general. Please be sure to use the latest tooling when working on the project :)
