### ISSUE TITLE
Execute Multiple Update - rows affected

### ISSUE THREAD

**Issue by Blastnsmash** [DapperLib/Dapper#1227]
Is there a way or extension library where I can execute a multi-update statement in dapper but get back each individual statement rows affected?

For example:

string query = "Update table1 set tbcol=@tbcol where...; Update table2 set tbcol=@tbcol where...";

var affectedrows = con.Execute(query);

Find if statement 1 had rows affected instead of aggregate
Find if statement 2 had rows affected instead of aggregate

**Comment by EitanBlumin** [comment]
Depending on the type of DB provider you're using, you could probably write something like the following in your SQL command (this is a SQL server example):

```
string query = "
Update table1 set tbcol=@tbcol where...;
Set @table1cnt = @@rowcount;

 Update table2 set tbcol=@tbcol where...;
Set @table2cnt = @@rowcount";
```

Then, you could do one of two things:

1. Define table1cnt and table2cnt as output parameters and get their values.
2. Declare @table1cnt and @table2cnt in the beginning of the SQL command, and at the end use SELECT statement to return their values as if a query. I.e.: `SELECT @table1cnt as t1cnt, @table2cnt as t2cnt`


The usage of @@rowcount is a SQL Server syntax, but I'm certain something like this is possible in all popular DB providers as well.

**Comment by SRYER** [comment]
Thanks for a decent solution to this problem :)

**Comment by SRYER** [comment]
Still very nice solution - just re-descovered by googling :D

**Comment by phiree** [comment]
how to get the two number from Execute or  ExecuteScalar??  they both return just one number.

**Comment by NickCraver** [comment]
@phiree Use `.Query<>` here instead, e.g. `.Query<(int Count1, int Count2)>("......<query above>.... Select @table1cnt, @table2cnt");`

Closing this one out to cleanup since approached are listed above.
