### ISSUE TITLE
QueryAsync missing buffered parameter

### ISSUE THREAD

**Issue by vitidev** [DapperLib/Dapper#1239]
I can

`db.Query<Person>(sql, parameters, buffered: false)`

But I can't 

`db.QueryAsync<Person>(sql, parameters, buffered: false)`

At the same time, the multimap overload of QueryAsync has parameter "buffered"

`Task<IEnumerable<TReturn>> QueryAsync<TReturn>(this IDbConnection cnn, string sql, Type[] types, Func<object[], TReturn> map, object param = null, IDbTransaction transaction = null, bool buffered = true, `

**Comment by mgravell** [comment]
Well that's odd. Is there an overload that takes the struct? Maybe that has
it?

But: when async iterators lands in c# vNext, we'll need to revisit the
non-buffered query-async *anyway*, as it is only pseudo-async at the moment
(by necessity).

**Comment by vitidev** [comment]
@mgravell 
Yes. I found 
`QueryAsync<T>(this IDbConnection cnn, CommandDefinition command) `

But it was expected that synchronous and asynchronous versions will have "mirror" signatures. Sometimes you have to convert Query into QueryAsyncand it's very nice when it's enough to add Async(+await) and that is all

>as it is only pseudo-async at the moment

That all the same it is good, it is possible not to hold a current thread waiting for the response from a database

>when async iterators lands in c# vNext

Async enumerators are good, but a little incomprehensible why you can not do without them like

     var reader = await db.ExecuteAsyncReaderAsync(); // 
     while (await reader.ReadAsync())
     {
           var value = reader.GetChar(0);
     }

     var reader = await db.QueryReaderAsync<Person>();
     while (await reader.MoveNext())
     {
          var value = reader.Current;
     }

Or is it already there and I do not read the documentation well?

**Comment by mgravell** [comment]
You absolutely *can* do that as long as you're happy for the consuming code
to do that work but a execute-reader and getting the per-T materializer
separately. The point here is that until C# vNext, neither "foreach" nor
"yield return" support this scenario, so you can't *just* return a
sequence. That's what vNext gives us: "await foreach".

**Comment by ravimp** [comment]
@mgravell await foreach is out there now. Any plans to support this now?

**Comment by ravimp** [comment]
@mgravell, Dapper has been such a help, I'd like to return favor. I think I can contribute if someone points me in right direction. Meanwhile, I got this from an SO post. Do you think it is a reliable workaround until we get an API for it?

```
using var reader = await connection.ExecuteReaderAsync(query, parameters);
var rowParser = reader.GetRowParser<T>();

while (await reader.ReadAsync()) {
    yield return rowParser(reader);
}
```

**Comment by mgravell** [comment]
add some `ConfigureAwait(false)` and you're probably pretty close; personally I'm also a bit of a stickler for exhausting the reader, because I've seen TDS faults go unreported if this isn't done, so:

``` c#
while (await reader.ReadAsync()) {
    yield return rowParser(reader);
}
while (await reader.NextResultAsync()) {}
```

but: up to you

**Comment by SeanFarrow** [comment]
Did this ever get implemented in dapper directly?
I'm at a point where this would be really useful.

Thanks,
Sean.

**Comment by PedroFerreira4470** [comment]
any news regarding this?

**Comment by mgravell** [comment]
this feature now essentially provided via #1912
