### ISSUE TITLE
I can't found the "int Insert<T>(Enumerable<T> list);" in dapper.contrib,why?

### ISSUE THREAD

**Issue by YeJianXi** [DapperLib/Dapper#1260]
I can't found the "int Insert<T>(Enumerable<T> list);" in dapper.contrib,why?

**Comment by jessegood** [comment]
Because there is only one extension method that handles both single entities and lists of entities.

**Comment by NickCraver** [comment]
The above is correct - there are other issues asking for generic insert methods though - closing this one out to cleanup (since it's tracked elsewhere).
