### ISSUE TITLE
Possible mistake when clearing query cache

### ISSUE THREAD

**Issue by bokmadsen** [DapperLib/Dapper#1264]
In the documentation it states that the query cache is cleaned up, once in a while. However looking at the code it looks like it clears the entire cache every 1000 queries. This is due to the check in this line:

https://github.com/StackExchange/Dapper/blob/d19d6012e75feebf24d591ad21b16f13becc95f2/Dapper/SqlMapper.cs#L78

COLLECT_HIT_COUNT_MIN is defined as:
https://github.com/StackExchange/Dapper/blob/d19d6012e75feebf24d591ad21b16f13becc95f2/Dapper/SqlMapper.cs#L91

Wouldn't that render the IF statement true every time, as hitcount always would be >= 0?

**Comment by NickCraver** [comment]
This method is behaving correctly - the first time a query is added to the cache, it has a `hitCount` of `0`. Only if it's used _again_ does it get a `hitCount++`, so that method is cleaning up things that are _never_ re-used as is the intent :)
