### ISSUE TITLE
SqLite ReadFirstAsync<int> 

### ISSUE THREAD

**Issue by Olbrasoft** [DapperLib/Dapper#1301]
public override async Task<IResultWithTotalCount<QuestionDto>> HandleAsync(PagedAnsweredQuestionsQuery query, CancellationToken token)
        {
            //const string sql = @"SELECT Questions.Id, Questions.DateCreated, Questions.DateAnswered, Questions.QuestionText, Questions.DisplayName, Questions.EmailAddress, Questions.AnswerText, Categories.Name AS CategoryName
            //FROM Questions INNER JOIN
            //Categories ON Questions.CategoryId = Categories.Id
            //WHERE(NOT(Questions.DateAnswered IS NULL))
            //ORDER BY Questions.DateAnswered DESC LIMIT @Take OFFSET @Skip;

            //SELECT count(id) FROM Questions WHERE (NOT (Questions.DateAnswered IS NULL))";

            const string sql = @"SELECT Questions.Id, Questions.DateCreated, Questions.DateAnswered, Questions.QuestionText, Questions.DisplayName, Questions.EmailAddress, Questions.AnswerText, Categories.Name AS CategoryName
            FROM Questions INNER JOIN
            Categories ON Questions.CategoryId = Categories.Id
            WHERE(NOT(Questions.DateAnswered IS NULL))
            ORDER BY Questions.DateAnswered DESC OFFSET @Skip ROWS FETCH NEXT @Take ROWS ONLY;

            SELECT count(id) FROM Questions WHERE (NOT (Questions.DateAnswered IS NULL))";

            IResultWithTotalCount<QuestionDto> result;

            using (var connection = GetConnection())
            {
                using (var multi = connection.QueryMultipleAsync(sql, new { Take = query.Paging.PageSize, Skip = query.Paging.CalculateSkip() }).Result)
                {
                    result = new ResultWithTotalCount<QuestionDto>
                    {
                        Result = (await multi.ReadAsync<QuestionDto>()).ToArray(),

                        // SQLite TotalCount = (int) await multi.ReadFirstAsync<long>()

                        TotalCount = await multi.ReadFirstAsync<int>()
                    };
                }
            }
            
            return result;
        }

**Comment by mgravell** [comment]
Can you add some words here? I'm not sure if you're asking a question, reporting an issue, or just... showing me some code. Please clarify.

**Comment by Olbrasoft** [comment]
For MSSql Server works ReadFirstAsync<int>() but SQLite ReadFirstAsync<int> error convert  int64 to int32 ,   it can be bypassed  (int) await multi.ReadFirstAsync<long>()

**Comment by PromontoryProtean** [comment]
I am running into a similar problem. This works:

```
var rowCount = await dbConnection.ExecuteScalarAsync<int>("SELECT COUNT(Id) FROM TheTable");
var someRows = await dbConnection.QueryAsync<MyRecordClass>("SELECT Id,SomeColumn FROM TheTable");
```

But if I try to do the same thing using QueryMultiple to avoid the second round trip, I get the following error on the rowCount query:
Unable to cast object of type 'System.Int64' to type 'System.Int32'

dbc.QueryMultiple code that fails:
```
var sql = "SELECT COUNT(Id) FROM TheTable;SELECT Id,SomeColumn FROM TheTable";
using (var multi = dbConnection.QueryMultiple(sql))
{
   var rowCount = await multi.ReadSingleAsync<int>();
   var someRows = await multi.ReadAsync<AdminNode>();
}
```

I remember running into a similar issue years ago using one of the Query extension method variations with SQLite but it was resolved at some point.

I am able to work around the bug by doing:
```
using (var multi = dbConnection.QueryMultiple(sql))
{
   var rowCount = (int)await multi.ReadSingleAsync<long>();
   var someRows = await multi.ReadAsync<AdminNode>();
}
```

But this creates additional problems when working with pluggable db providers.

For context, I am running into this bug using .NET Core 3 preview 9, Dapper 2.04 and System.Data.SQLite.Core 1.0.111

**Comment by NickCraver** [comment]
This is the same issue as #1496 - resolving in #1663.
