### ISSUE TITLE
Insert Arabic in to mysql  scrambling code

### ISSUE THREAD

**Issue by KingDracula** [DapperLib/Dapper#1308]
i was add charset=utf8mb4 in connectionstring,  mysql  code  is utf8mb4 .
when i run the insert script in navicat is ok ,but run in program with Dapper  was scrambling code

'دليل البدء السريع (لغات متعددة) - A8-50 اللوحي (A5500)'

???? ????? ?????? (???? ??????) - A8-50 ?????? (A5500)

**Comment by bgrainger** [comment]
This is unlikely to be a bug in Dapper itself; it just uses C# `char` and `string` to communicate with the underlying ADO.NET library.

Try switching to [MySqlConnector](https://www.nuget.org/packages/MySqlConnector/) to see if it's a problem with MySql.Data.

**Comment by reinaldocoelho** [comment]
I have the same Bug with SQL Server, I have an NVARCHAR column, but it´s broke the insert with japanese chars.
If I make my INSERT by hand with Dapper like "insert into table(field) values(N'単純な値') the insert work´s well.

Look like an bug on Dapper.Contrib

**Comment by reinaldocoelho** [comment]
Updating information, the problem with MSSQL is my fault.
The field on database was created with VARCHAR instead of NVARCHAR.

When changed the type the mapping worked well.

**Comment by NickCraver** [comment]
Glad you're sorted! Closing this out to cleanup.
