### ISSUE TITLE
SqlMapper with dependency injection

### ISSUE THREAD

**Issue by xaviergxf** [DapperLib/Dapper#1314]
Hi,

Any plans on using dependency injection for sqlmappers instead of static?

Thanks

**Comment by mgravell** [comment]
"more contextual configuration" is certainly on the wishlist; I wouldn't
presume any of the "how" of that right now

**Comment by NickCraver** [comment]
We may explore this via AsyncLocal<T> in vNext, but not directly dependency injection here :)
