### ISSUE TITLE
2.0.30 is missing release notes

### ISSUE THREAD

**Issue by mrtristan** [DapperLib/Dapper#1343]
I'm trying to get a feel for the production readiness of v2. I'm seeing that GitHub has a release that's marked as being in `preview`, while the nuget version has an extra v2 series release and neither is marked as being in some sort of pre-release channel.

Is there any reason why the GitHub / Nuget versions don't align? Is there different significance to things on one side vs the other? It also seems that `2.0.30` is missing release notes.

(tried searching issues before asking this, sorry if i missed it)

**Comment by mgravell** [comment]
I've pushed the tags. You're right that we need to update the release notes; I'll revise this issue to focus on that in the title

**Comment by mrtristan** [comment]
sweeeeet. thanks. I usually peruse github instead of nuget for releases since there's _usually_ a little more info on that side.

**Comment by phillip-haydon** [comment]
Is there any update to this? 

https://stackexchange.github.io/Dapper/

The release notes haven't been updated...

**Comment by ImrePyhvel** [comment]
Still no release notes for 2.0.30.

**Comment by NickCraver** [comment]
The release notes for 2.0.30 were added in - closing out to clean up.
