### ISSUE TITLE
OpenTelemetry collector for Dapper

### ISSUE THREAD

**Issue by andy-g** [DapperLib/Dapper#1355]
Is there any plan to release an OpenTelemetry collector for Dapper?

OpenTelemetry (https://opentelemetry.io) is the next major version of the OpenTracing and OpenCensus projects, and it'd be awesome to have telemetry data automatically populated from dapper, especially as a major reason for using dapper is the performance advantage it gives over something like EFCore. 
https://github.com/open-telemetry/opentelemetry-dotnet

There is already a collector for StackExchangeRedis (https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Collector.StackExchangeRedis), so I'd be interested to know what would be involved in implementing something similar for dapper.

**Comment by NickCraver** [comment]
There are no plans (from us) to implement this, but one way you could go about it is the same way MiniProfiler does it: by wrapping the `DbConnection`. See [the `ProfiledDb*` classes in MiniProfiler](https://github.com/MiniProfiler/dotnet/tree/master/src/MiniProfiler.Shared/Data). That approach works for any ADO.NET provider, but it looks like OpenTelemetry already did SqlServer specifically in: https://github.com/open-telemetry/opentelemetry-dotnet/pull/536

Hope that answers the question!

**Comment by NickCraver** [comment]
Closing this out to cleanup!
