### ISSUE TITLE
ReadAsync on mutli results (GridReader) joins?

### ISSUE THREAD

**Issue by sitepodmatt** [DapperLib/Dapper#1358]
Multiple results each with joins does mapper support ReadAsync<TSource, TJoin1, TJoin2, TOutput>(Func<... joiner>, this appears to work with multi.Read but there's no corresponding signatures for ReadAsync methods on GridReader. 

Is this feature missing or have I made an oversight?

**Comment by NickCraver** [comment]
Collapsing into duplicate #296 - planning on resolving this in vNext.
