### ISSUE TITLE
CommandTimeout not  work for simple TSQL "WHILE 1 = 1..."

### ISSUE THREAD

**Issue by ingted** [DapperLib/Dapper#1360]
Hi,
On SQL SERVER 2017 with Dapper query like:

```
let sqlConn = new SqlConnection(sqlConnStr)
sqlConn.Open ()
let r = dapperMapParametrizedQuery<SqlMapper.DapperRow> "while 1 = 1 begin print('I do not `timeout') end" Map.empty sqlConn (Nullable<int> 5)
```

It will never timeout... but if the code is like this, it works...

```
dapperMapParametrizedQuery<SqlMapper.DapperRow> "while 1 = 1 begin waitfor delay '00:00:30' end" Map.empty sqlConn (Nullable<int> 5)
```

**Comment by mgravell** [comment]
This is ultimately a feature of the ADO.NET provider (SqlClient); the timeout is essentially applied *between receives*; if you `print`, it counts as a receive and the timer gets reset - so yes, it never times out. Adding the `waitfor` delays the receive, triggering the timeout. But nothing here is Dapper.

I'm not sure we want to add a second layer of timers at the client for this, unless there is a more applicable use-case than an infinite loop with a `print`

**Comment by NickCraver** [comment]
Answered above (still current) - closing this out to cleanup.
