### ISSUE TITLE
Exception: When passing parameters by position, each parameter can only be referenced once

### ISSUE THREAD

**Issue by tjaskula** [DapperLib/Dapper#1406]
This happens in request that have all different parameters names.

It happens that in `commandText` there is a value `Part ?EUR ?I? Dis`  in multiple places, which is catched wrongly as parameter with the regular expression `\?([\p{L}_][\p{L}\p{N}_]*)\?`

The matched string is `?I?` which obviously is not a parameter name.

**Comment by NRKirby** [comment]
Can you share a small repro, on Github or whatever?

**Comment by NickCraver** [comment]
An example query would indeed help here - it's hard to tell if or how we'd adjust the Regex without some more context (changing it to observe context might be very expensive/risky). An example would be great!

**Comment by NickCraver** [comment]
Without some repro, can't help much here - closing out but happy to discuss if we have more to go on.

**Comment by zanyar3** [comment]
I have a problem for now but fix by **different name but some value,** 

**Example**
```
DynamicParameters parameters = new();
parameters.Add("user", 'my-user');
parameters.Add("user2", 'my-user');

var query = @"SELECT *
              FROM table
              WHERE col = @user
                        
              UNION ALL
                        
              SELECT *
              FROM table2
              WHERE col = @user2"
```
                    
Have another idea for fix this problem?
