### ISSUE TITLE
oracle database error: when parameter is empty list,error message:Oracle.ManagedDataAccess.Client.OracleException:“ORA-00923: 未找到要求的 FROM 关键字”,but this is ok when I use mysql database

### ISSUE THREAD

**Issue by lishuangquan1987** [DapperLib/Dapper#1427]
![image](https://user-images.githubusercontent.com/15365329/77499457-1b8eaa00-6e8d-11ea-8c9e-f64dbc40ed51.png)

**Comment by lishuangquan1987** [comment]
below is my code:
`  string sql = "select * from aaa_test_a where id in :ids";
			object param = new
			{
				ids = new int[] { }
			};
			using (var conn = new Oracle.ManagedDataAccess.Client.OracleConnection(connStr))
			{
				conn.Query<ModelA>(sql,param);
			}
`

**Comment by samuelrvg** [comment]
Dapper is not support Oracle.

**Comment by NickCraver** [comment]
Can you please paste the exception? I'm unable to read the language in the image or readily translate it :)

**Comment by lishuangquan1987** [comment]
stack trace:
   在 OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   在 OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   在 Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   在 Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   在 System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   在 Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) 在 F:\Project2020\PCI.Framework.ORM性能测试\Dapper\SqlMapper.cs 中: 第 1051 行
   在 Dapper.SqlMapper.<QueryImpl>d__140`1.MoveNext() 在 F:\Project2020\PCI.Framework.ORM性能测试\Dapper\SqlMapper.cs 中: 第 1079 行
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) 在 F:\Project2020\PCI.Framework.ORM性能测试\Dapper\SqlMapper.cs 中: 第 721 行
   在 Dapper_DapperExtension_Test.Program.Main(String[] args) 在 F:\Project2020\PCI.Framework.ORM性能测试\Dapper_DapperExtension_Test\Program.cs 中: 第 37 行

**Comment by diegosps** [comment]
I just stumbled in a similar issue:

```
string sql = @"merge into t_tile t 
                        using (select :processo processo, :status status, :cache cache, :quadkey quadkey, min(dat_origem) min_dat, max(dat_origem) max_dat, sysdate dat_now, :ctImages ct_images, :zoom zoom from t_imagem where id in :imagens) s
                        on (t.cod_quadkey = s.quadkey and t.cod_cache = s.cache)
                        when matched then update set t.cod_processo = s.processo, t.cod_status = s.status, t.dat_create = s.dat_now, t.dat_min_aquisition = s.min_dat, t.dat_max_aquisition = s.max_dat, t.val_count_images = s.ct_images
                        when not matched then insert (cod_cache, cod_quadkey, val_zoom, cod_processo, cod_status, dat_create, dat_min_aquisition, dat_max_aquisition, val_count_images) 
                            values (s.cache, s.quadkey, s.zoom, s.processo, s.status, s.dat_now, s.min_dat, s.max_dat, s.ct_images)";
```

if `imagens` is empty I receive a similar exception:

Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00923: palavra-chave FROM não localizada onde esperada
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in ...


But I'm not sure if this is dapper related. Seems like an Oracle bug for me.

**Comment by NickCraver** [comment]
It looks like the generated SQL is invalid here - rather than changing query generation, my recommendation would be to _not run a query at all_ if `ids` is empty, since there's no gain in doing so - it's a far more optimal path to short circuit that situation.
