### ISSUE TITLE
Dapper not mapping bool to bit (as an input parameter)

### ISSUE THREAD

**Issue by JRam13** [DapperLib/Dapper#1436]
Take this simple query for example:

```
bool isDeleted = false;

// Query
SELECT * FROM TableA
WHERE isDeleted = @isDeleted

// Resulting SQL
SELECT * FROM TableA
WHERE isDeleted = False /* @isDeleted */
```

Why is `false` mapping to `False`?

Weirdly enough, it maps bit -> bool just fine.

**Comment by mgravell** [comment]
I don't understand the question. Dapper *doesn't do* injection of parameter values (exepct for a very specific case, which isn't this). Dapper simply adds parameters with typed values. There is no "resulting SQL" - Dapper literally doesn't have code to do anything like that!

So: where did your "resulting SQL" come from? Is that some kind of trace? If so, I suspect that it was your ADO.NET provider that performed that step, possibly for a database that doesn't directly support parameters. Now the questions become:

1. What database/server is this?
2. What ADO.NET provider is this?

**Comment by JRam13** [comment]
@mgravell Thanks for the response. 

The resulting SQL is what gets translated and sent over the wire as the query string (since input parameters need to be mapped appropriately).  I might have wrongfully assumed Dapper did this mapping (in this case turning bool false into `False` instead of 0). 

Anyway, we're using Sql Server (running on Azure), and default ADO.NET provider for Sql (System.Data.SqlClient) - using .Net Core 2.2.

Right now the obvious workaround is converting the bool value into an int... but not really sure why we would need to do that.

**Comment by mgravell** [comment]
I would be *very* surprised by SqlClient doing such a thing. If you have a
repro, that sounds like a bug to report to the SqlClient team.

**Comment by NickCraver** [comment]
It sounds like something else is going on here - can you provide full repro code? It sounds like your param is getting a `.ToString()` somewhere and that's not something Dapper or SqlClient would do...

**Comment by shadman-heckyl** [comment]
My stored procedure
```sql
ALTER PROCEDURE [dbo].[update_ProcessStatus]
	 @ProcessStatusId		TINYINT = NULL
	,@ProcessStatus			NVARCHAR(50) = NULL
	,@ProcessShortStatus	CHAR(1) = NULL
	,@IsActive				BIT
	,@LastUpdatedBy			NVARCHAR(100)
	,@ActionFlag			CHAR(1)
AS
BEGIN
```

my data param class

```cs
public class EditProcessStatusMaster
    {
        public byte ProcessStatusId { get; set; }
        public string ProcessStatus { get; set; }
        public string ProcessShortStatus { get; set; }
        public bool? @IsActive { get; set; }
        public string LastUpdatedBy { get; set; }
        public string ActionFlag { get; set; }
    }
```

Error im getting:
System.AggregateException : One or more errors occurred. (Procedure or function 'update_ProcessStatus' expects parameter '@IsActive', which was not supplied.)

My repo code:

```cs
public Task<int> AddOrUpdateAsync(EditProcessStatusMaster value)
        {
            var sql = "exec update_ProcessStatus";
            return dbManager._Connector.Connection.ExecuteAsync(sql, value);
        }
```

**Comment by shadman-heckyl** [comment]
The dapper is unable to map bool input to bit param

**Comment by shadman-heckyl** [comment]
Changed to below code now working please ignore above issue
```cs
public Task<int> AddOrUpdateAsync(EditProcessStatusMaster value)
        {
            var sql = "update_ProcessStatus";
            return dbManager._Connector.Connection.ExecuteAsync(sql, value, commandType: CommandType.StoredProcedure);
        }
```

**Comment by NickCraver** [comment]
Ah I see with the example code - glad you're sorted. Closing out to cleanup!
