### ISSUE TITLE
Dapper.Contrib old fix did not make it into NuGet

### ISSUE THREAD

**Issue by oreleraki** [DapperLib/Dapper#1437]
Hi,

I've open this issue because after research i arrived into #355 and noticed it was closed long time ago but no fix has ever made it way into the different NuGet packages.

**Comment by mgravell** [comment]
One of the key features of - in fact pretty much the definition of - the "contrib" package is that it isn't directly maintained by the core Dapper team. So: I encourage you: if this is something that you think could and should be fixed, please do fork and contribute the fix as a PR. Of particular note may be the server compatibility table, but IIRC this is SQL Server 2008, onwards, so: it shouldn't be controversial... as long as this code path only impacts SQL Server!
