### ISSUE TITLE
Is't possible with Dapper to project tables with codefirst?

### ISSUE THREAD

**Issue by biapar** [DapperLib/Dapper#1455]
Is't possible with Dapper to project tables with codefirst?

**Comment by NickCraver** [comment]
Do you have an example? I'm not familiar with the feature set you're talking about - if it's meaning some specific implementation of code first, or do you mean Dapper as a full mapping ORM like Entity Framework? If the latter, that's not the goal of Dapper: to be a very slim, very fast, minimal wrapper for mapping. If _not_ that, we need some more info to go on :)

**Comment by biapar** [comment]
That is like Petapoco. I code a class with decorations and the orm create or mod the table.

**Comment by NickCraver** [comment]
Gotcha - that is not a feature set of Dapper, or one we intend to add. There are plenty of ORMs that do this though!

**Comment by biapar** [comment]
Thx. ( Do you suggest Petapoco ? ) _:)

**Comment by NickCraver** [comment]
Can't comment either way - I've never used it, sorry! Entity Framework is all else we've played with that much, but we don't use it in this manner either.

**Comment by dallasbeek** [comment]
Did you mean database first and using the T4 template to generate?

**Comment by biapar** [comment]
See this : https://github.com/umbraco/Umbraco-CMS/blob/9ffb3bed571af2be853127064514983d56501f25/src/Umbraco.Core/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs

**Comment by NickCraver** [comment]
Closing out to cleanup :)
