### ISSUE TITLE
INSERT with nullable<int> gives "Must declare the scalar variable".

### ISSUE THREAD

**Issue by alex-jitbit** [DapperLib/Dapper#1470]
This is probably related to #581

```c-sharp
int fieldId = 42;
int? userid = null;
cn.Execute("INSERT INTO myTable (FieldID, UserID) VALUES (@fieldId, @userid)",
	new { fieldId, userid });
```

This code results in `Must declare the scalar variable @userid` on _some machines only_ (with older versions of SQL Server like SQL 2012).

This is probably not a bug in Dapper since it work on most servers, but I'd really appreciate any clues on what it can be... May be an old `SqlClient` driver? Not sure.

Or Dapper is not adding the parameter to the collection under some circumstances?

**Comment by NickCraver** [comment]
The error message and the code aren't lining up for me, I see `@userID` in the insert statement, `userID` in the params (so far so good), but the error posted is `@userid` (lower-case).

Sanity check: is this _exactly_ the code running, or is there a casing difference between params and SQL text? A mismatch _will_ break on servers with a case-sensitive collation for the master database (not the one you're querying...params are based on master), but _won't_ break on case-insensitive servers (the default for SQL Server installs). It'd only go boom for the latter in other situations such as `@uSerID` and `@userID` both declared, etc.

**Comment by alex-jitbit** [comment]
@NickCraver sorry, yes, I changed the code to be more... uhm... self-explaining. The original code has the right casing. I just edited the issue to make it precise.

**Comment by NickCraver** [comment]
@alex-jitbit not seeing an edit here, double check it submitted?

**Comment by alex-jitbit** [comment]
@NickCraver hey it's not me it's GitHub! It thinks that @-xxx is a username mension and makes it lowercase, hahah

**Comment by NickCraver** [comment]
hah, try escaping the error in backticks: ` :)

**Comment by alex-jitbit** [comment]
I'm closing this issue, it was something else
