### ISSUE TITLE
how to remove SQL differences in different databases

### ISSUE THREAD

**Issue by ensleep** [DapperLib/Dapper#1471]
We use @ as prefix of parameters in ms sql ,as use : in oracle and mysql. How can execute sql with dapper without these prefixes? Because my projects want to run with diff databases.Thks

**Comment by mgravell** [comment]
That isn't something Dapper provides right now. In the general case, there are lots of other subtle language differences that make it not that simple.

**Comment by ensleep** [comment]
Yes,there are lots of other subtle language differences. I think these differences can be resolved by my developers, because I will tell then don't use any "bad" sql. But the prefix is a trouble with me . Can I get some way to reolve the prefix of parameter in diff sql language?

**Comment by mgravell** [comment]
I'm not aware of any API in ADO.NET that advertises the parameter syntax
for the relevant syntax.

**Comment by bgrainger** [comment]
`DbCommandBuilder.GetParameterName` (https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbcommandbuilder.getparametername?view=netcore-3.1#System_Data_Common_DbCommandBuilder_GetParameterName_System_String_) is the closest thing I can think of, but it's `protected`.

I'm not sure if there's any way to get at its return value through the public API of that class.

**Comment by bgrainger** [comment]
Update: you should be able to use the `ParameterMarkerFormat` value from the `DataSourceInformation` schema: https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/common-schema-collections#datasourceinformation

**Comment by NickCraver** [comment]
Bradley's instructions above is the best route I'm aware of here - still no plans for Dapper to do generation there. Closing out to cleanup!
