### ISSUE TITLE
QueryMultiple for Oracle

### ISSUE THREAD

**Issue by thiagopassosp** [DapperLib/Dapper#1477]
Error ORA-00911 when executing multiple queries.
Is there any solution for this error?

Version 2.04

**Comment by mgravell** [comment]
Can you give an example of code that causes this error? I believe ORA 911 is an invalid character. Obviously it is hard to comment on that when I have zero characters to look at.

**Comment by zqlovejyc** [comment]
oracle not support multiple query. may be you need use cursor

**Comment by NickCraver** [comment]
Indeed Oracle doesn't support this functionality - see https://stackoverflow.com/questions/18772781/using-dapper-querymultiple-in-oracle for more details and further explanation!
