### ISSUE TITLE
Call ReadFirstOrDefaultAsync throw Exception

### ISSUE THREAD

**Issue by zqlovejyc** [DapperLib/Dapper#1480]
When I Call ReadFirstOrDefault, It's OK .

Like this 

![image](https://user-images.githubusercontent.com/19462884/83715766-bf03f400-a660-11ea-9192-bfc3615e8876.png)

but Call ReadFirstOrDefaultAsync ,it;s Error:
![image](https://user-images.githubusercontent.com/19462884/83715768-c0cdb780-a660-11ea-998d-fdfc9f34b431.png)

Nuget version:

![image](https://user-images.githubusercontent.com/19462884/83715804-d5aa4b00-a660-11ea-97d3-4439c4d58a58.png)

**Comment by NickCraver** [comment]
Resolved in #1575 - tidying up!
