### ISSUE TITLE
Add summary of the different packages (.Contrib, .SqlBuilder, etc.) to main README?

### ISSUE THREAD

**Issue by DylanSp** [DapperLib/Dapper#1488]
I'm wondering if it would be a good idea to add a brief summary of what the different sub-packages (Dapper.Contrib and the like) do to the main README. I didn't even realize they provided additional functionality at first, due to the lack of discoverability. Would this be helpful/appreciated?

**Comment by NickCraver** [comment]
It would be both helpful and appreciated :)
