### ISSUE TITLE
Diferent result with QueryAsync and QueryMultipleAsync

### ISSUE THREAD

**Issue by Wqawer** [DapperLib/Dapper#1496]
I am using .net core 3.1 with dapper 2.0.35

When i do something like this:
```
var q = "Select count(1)";
var count = await conn.QueryAsync<int>(q);
```

It works ok and returns integer, but when i do something like this: 
```
var q = "Select 'a'; Select count(1); ";
using(var multiple = await cnn.QueryMultipleAsync(q){
    var text= await multiple.ReadAsync<string>();
    var count = await multiple.ReadAsync<int>();
}
```
This throws System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Int32'. I have found out that second query returns long instead of int and that is causing error.

Is this expected behaviour or is it bug?

**Comment by mgravell** [comment]
Sounds like a bug with us not running all the same conversions in both cases.

**Comment by NickCraver** [comment]
Added a fix for this (seen a few reports, all the same thing) in #1663.
