### ISSUE TITLE
Oracle Package method call throws exception handled in the package method

### ISSUE THREAD

**Issue by kchristo71** [DapperLib/Dapper#1504]
I am having a strange issue where I am calling an Oracle package method call using ExecuteAsync:
`var rowsAffected = await Connection.ExecuteAsync(command, parameters, commandType: CommandType.StoredProcedure);`
This method internally has an exception handling mechanism which handles all exceptions and returns any errors in an out parameter called **p_err_msg**:
`EXCEPTION
  
   WHEN OTHERS THEN
      v_err_msg  := SQLERRM; 
      v_sql_code := SQLCODE;
      v_err_msg  := v_err_msg||'  '||primaky_key||'  '||dbms_utility.format_error_backtrace;
      p_err_msg  := v_err_msg;
      DBMS_OUTPUT.PUT_LINE(p_err_msg);                                   
END;`

Calling the package method from any Oracle IDE (SQL Developer, TOAD etc) demonstrates the expected behaviour, not throwing an exception but returns the error message in the out variable.
Calling OracleConnection.ExecuteAsync for the same method with the same parameters results to the exception, which is handled in the package method, being thrown to the client.
Any idea why this happens and how it can be avoided. It is causing an issue because we want to make sure that exception is only thrown in any case that we fail to execute the method (connectivity issues) but not when an error internal to the package method is thrown.

**Comment by onurcanyilmaz** [comment]
Hi,
Firstly, you used OracleClient,  in that case you must creating custom class for oracle parameters.
And this class must inherit from IDynamicParameters. 

you must use class OracleParameter.

also, you can use directly the this class : https://gist.github.com/vijayganeshpk/3096151

**Comment by NickCraver** [comment]
@onurcanyilmaz Is correct - that's the adapter approach needed here. We can't include this in the base library without taking an Oracle dependency (something Dapper can't reasonably do), but with then implementation above you should be all sorted.
