### ISSUE TITLE
Does Dapper support CosmosDB

### ISSUE THREAD

**Issue by santoshpatro** [DapperLib/Dapper#1506]
Can any help me to know with some sample examples regarding Dapper support for CosmosDB for asp.net core 3.1 based REST API?

Any reference example will help me a lot.

**Comment by mgravell** [comment]
Dapper just sits on top of ADO.NET; is there an ADO.NET provider for CosmosDB? If not, then "no". If there is: have you tried it? Did it work?

Dapper tries hard to not need to know much about what it is talking to. If you are trying it and seeing specific problems: great, but we'd need detail on those problems.
