### ISSUE TITLE
(Third-party library) Dapper Query Builder - wrapper to build dynamic SQL using string interpolation

### ISSUE THREAD

**Issue by Drizin** [DapperLib/Dapper#1512]
[https://github.com/Drizin/DapperQueryBuilder/](https://github.com/Drizin/DapperQueryBuilder/)

**Dapper Query Builder using String Interpolation and Fluent API**

We all love Dapper and how Dapper is a minimalist library.

This library is a wrapper around Dapper mostly for helping building dynamic SQL queries and commands (as a replacement for [Dapper.SqlBuilder](https://github.com/StackExchange/Dapper/tree/main/Dapper.SqlBuilder)). 

It's based on 2 fundamentals:

1. String Interpolation instead of manually using DynamicParameters
1. Query and Parameters walk side-by-side

Sample usage:

```cs
int maxPrice = 1000;
int maxWeight = 15;
string search = "%Mountain%";

var products = cn.QueryBuilder($@"
    SELECT ProductId, Name, ListPrice, Weight
    FROM [Product]
    WHERE [ListPrice] <= {maxPrice}
    AND [Weight] <= {maxWeight}
    AND [Name] LIKE {search}
    ORDER BY ProductId").Query<Product>();
```

`Query<>` invokes Dapper and automatically passes the underlying SQL statement and Parameters. Additional parameters (transaction, commandTimeout) can still be passed. Underlying SQL will be fully parameterized like:
```sql
SELECT ProductId, Name, ListPrice, Weight
FROM [Product]
WHERE [ListPrice] <= @p0
AND [Weight] <= @p1
AND [Name] LIKE @p2
ORDER BY ProductId
```

You can also start with an initial query and then append dynamic conditions:
```cs
var query = cn.QueryBuilder($"SELECT * FROM [Product] WHERE 1=1");
query.Append($"AND Name LIKE {productName}"); 
query.Append($"AND ProductSubcategoryID = {subCategoryId}"); 
var products = query.Query<Product>(); 
```

Or leaving filters to be described later:
```cs
var cn = new SqlConnection(connectionString);

// You can build the query manually and just use QueryBuilder to replace "where" filters (if any)
var q = cn.QueryBuilder(@"SELECT ProductId, Name, ListPrice, Weight
    FROM [Product]
    /**where**/
    ORDER BY ProductId
    ");
    
// You just pass the parameters as if it was an interpolated string, 
// and QueryBuilder will automatically convert them to Dapper parameters (injection-safe)
q.Where($"[ListPrice] <= {maxPrice}");
q.Where($"[Weight] <= {maxWeight}");
q.Where($"[Name] LIKE {search}");

// Query() will automatically build your query and replace your /**where**/ (if any filter was added)
var products = q.Query<Product>();
```

Mixing and/or filters in structured way:
```cs
q.Where(new Filters(Filters.FiltersType.OR)
{
    new Filters(Filters.FiltersType.AND)
    {
        $"[Weight] <= {maxWeight}",
        $"[Weight] >= {minWeight}",
    }
    new Filter($"[Name] LIKE {search}")
});
```

Chained-methods (Fluent API) if you have something like a QueryBuilder exposed in UI to your end-users:
```cs
var q = cn.QueryBuilder()
    .Select($"ProductId")
    .Select($"Name")
    .Select($"ListPrice")
    .Select($"Weight")
    .From($"[Product]")
    .Where($"[ListPrice] <= {maxPrice}")
    .Where($"[Weight] <= {maxWeight}")
    .Where($"[Name] LIKE {search}")
    .OrderBy($"ProductId"); // there's also GROUP BY, HAVING, ORDERBY, and PAGING (OFFSET/FETCH NEXT)
    
var products = q.Query<Product>();
```

More examples and features [here](https://github.com/Drizin/DapperQueryBuilder/)

**Comment by NickCraver** [comment]
It's great to see new libraries, and thanks for the kind words!

I am curious! How are you guarding against injection in your library? The biggest reason we chose not support this behavior natively in Dapper is around risk around injection due to how the framework handles these strings. In #838, I outlined some of these (mainly around formatting strings being method overloads rather than underloads in resolution ordering) as to why we don't support it and EF Core ultimately ended up isolating it.

For example, if a user does this:
```cs
var searchFilter = $"[Name] LIKE {search}";
// ...and later
new Filter(searchFilter);
```
...how do you guard against that injection case? Are you implementing something in the overloads, or analyzers, or something else? Or is this considered a minimal case from another viewpoint or risk? Given we went another path, I'm always curious how others approached it and their analysis of the same problems!

**Comment by Drizin** [comment]
Hey Nick, thanks for reviewing and for your comments.

I may be overlooking this, but as far as I understand, as long as my methods only accept FormattableStrings it's impossible that someone sends an unsafe string by mistake. I've just tested your example above (where var is implicitly converted into a string), and doesn't compile. 

I've seen that #838 discussion before when I was designing the library. And I also explored the idea of having a [RawString](https://www.damirscorner.com/blog/posts/20180921-FormattableStringAsMethodParameter.html) class which would have implicit conversions from/to FormattableString/string while still prioritizing the FormattableString overload resolution. But as you described in the other thread, this still has some vulnerabilities. Forcing everything to be FormattableString seems to work fine.

So basically all methods take a FormattableString and extract the "embedded parameters" safely. These parameters are later combined and passed to a DynamicParameters bag. It's pretty simple.

Do you see any vulnerability in this design?

**Comment by NickCraver** [comment]
@Drizin ah I see! Indeed that should be safe if the handling underneath is - definitely avoids the type system issues we were encountering with existing methods. It trades a tad bit of efficiency for the safety (which I totally agree with for this case).

Thanks for the reply, and thanks for building this! If I encounter users with matching uses, I shall point them towards it :)

**Comment by NickCraver** [comment]
Closing out to clean things up (handling lots of issues)
