### ISSUE TITLE
Get information about the executed query statement

### ISSUE THREAD

**Issue by swaggyolafson** [DapperLib/Dapper#1519]
I'm using Dapper with MySQL and when fetching one user from the database all I have to do is

```cs
    public Task<User> GetUser(string username) 
    {
        using IDbConnection databaseConnection = new MySqlConnection("connectionString");
            
        DynamicParameters parameters = new DynamicParameters();
        parameters.Add("@username", username, DbType.String);
            
        return databaseConnection.QueryFirstOrDefaultAsync<User>(
            "SELECT * FROM person WHERE username = @username",
            parameters);
    }
```

but I would like to add some trace level logging. Is there a way I can fetch the query string before executing it?

I know there are some workarounds like

- https://stackoverflow.com/questions/44183650/how-to-log-get-a-sql-query-auto-generated-by-dapper-extensions/50875558#50875558

Do I really have to use an external tool for this?

- https://stackoverflow.com/questions/44194760/how-to-get-last-executed-sql-query-by-sqlconnection

I think the wrapping solution looks like a massive overhead

Thanks a lot in advance :)

**Comment by mgravell** [comment]
What do you mean by "query string"? If you mean the query: all Dapper ever uses is literally `"SELECT username FROM person WHERE username = @username"` - Dapper doesn't replace tokens into the query. If the underlying ADO.NET provider does that internally as an implementation detail (for not supporting parameters), then that's outside of what Dapper sees. MySQL presumably has proper support for parameters *anyway*.

**Comment by mgravell** [comment]
If you're just after logging: perhaps consider MiniProfiler (by the same team)

**Comment by swaggyolafson** [comment]
> What do you mean by "query string"? If you mean the query: all Dapper ever uses is literally `"SELECT username FROM person WHERE username = @username"` - Dapper doesn't replace tokens into the query. If the underlying ADO.NET provider does that internally as an implementation detail (for not supporting parameters), then that's outside of what Dapper sees. MySQL presumably has proper support for parameters _anyway_.

@mgravell I was hoping to fetch the final query statement after replacing the parameter placeholders with the real values.

**Comment by matthiashermsen** [comment]
@swaggyolafson maybe I am wrong, but I was also looking for it and as far as I know, that is not possible using "the standard way". Maybe that’ll help you

- https://www.reddit.com/r/csharp/comments/220tjh/c_mysql_prepared_statements_how_to_i_see_the/
- https://stackoverflow.com/questions/265192/get-the-generated-sql-statement-from-a-sqlcommand-object

**Comment by NickCraver** [comment]
Agree with going the MiniProfiler route here - it's basically a wrapped connection or just use the code from it around formatting. Specifically, you're lookin for https://github.com/MiniProfiler/dotnet/tree/main/src/MiniProfiler.Shared/SqlFormatters - if you have a DbCommand, you'd be calling them like this: https://github.com/MiniProfiler/dotnet/blob/main/src/MiniProfiler.Shared/SqlFormatters/SqlFormatterExtensions.cs

All these formatters are doing is formatting the parameters in a usable way, as others nave noted above no actual replacement ever happens in the pipe.

**Comment by bgrainger** [comment]
> MySQL presumably has proper support for parameters anyway.

MySQL Server doesn't. (At least for the "text" protocol, which is the most common.) All MySQL ADO.NET drivers (safely) substitute the parameter values into the SQL text before sending it over the wire.

> Is there a way I can fetch the query string before executing it?

That would require injecting logging between your MySQL ADO.NET library and the MySQL Server.

But I don't believe any MySQL libraries have hooks for logging the fully-interpolated query string. ([MySqlConnector](https://github.com/mysql-net/MySqlConnector) doesn't, at least; the debug-level logging only logs the statement _before_ substituting parameters, as I believe logging the parameter values could constitute a security risk (information disclosure vulnerability) in the general case. See https://github.com/mysql-net/MySqlConnector/issues/754 for more discussion.)

In any case, this doesn't seem like a Dapper issue: Dapper just passes the parameters off to an ADO.NET driver, and it would be up to that driver to support a logging mechanism for the SQL statement. Alternatively, as already suggested, it could be added at a higher level with an ADO.NET wrappper that performs its own parameter interpolation and logging.

One final approach would be to use MySQL's "[general log](https://dev.mysql.com/doc/refman/8.0/en/query-log.html)":

> The server writes information to this log when clients connect or disconnect, and it logs each SQL statement received from clients.

If you log to a table, you can select entries out of that table from a client (for reporting back to your system of choice). Of course, this only logs _after_ the statement is executed, not "before executing it" as you initially requested.

**Comment by NickCraver** [comment]
Either MiniProfiler or the alternative avenues Bradley lists above are the routes here - going to close out to cleanup!
