### ISSUE TITLE
mulit mapping

### ISSUE THREAD

**Issue by zivfuture** [DapperLib/Dapper#1527]
Here is the code,I have three entities like this:
```
public class Department
{
    public int Id{get;set;}
    public string LocationCode{get;set;}
    public string Name{get;set;}
    public List<Employee> Employees{get;set;}     //multi sub entities.
    public List<Asset> Assets{get;set;}               //multi sub entities
}
public class Employee
{
    pulibc int DeptID{get;set;}
    public string LastName{get;set;}
    public string FirstName{get;set;}
    public int Age{get;set;} 
}
public class Asset
{
    public int DeptID{get;set;}
    public string Code{get;set;}
    public string Name{get;set;}
    public Datetime PurchaseDate{get;set;}
}
```
I want the result  is ```List<Department> depts```. 
The query sql and c# code  as blow:
```
var sql="
SELECT * into #tp_depts FROM Departments where LocationCode in('a','b','c')
SELECT * FROM #tp_depts
SELECT * FROM Employees where deptid in (select id from #tp_depts)
SELECT * FROM Assets where deptid in (select id from #tp_depts)
";
var result =conn.Query<Department,List<Employee>,List<Asset>,Department>(sql,
(depts,emps,ass)=>{ depts.Employees= emps; depts.Assets=ass ; return depts; }, 
splitOn: "DeptID"
);
```
I got an error, where am i wrong?:
```
Uninspected exception:When using the multi-mapping APIs ensure you set the splitOn param if you have keys other than Id (Parameter 'splitOn')
```

**Comment by agpcardoso** [comment]
Try 
splitOn: "DeptID,DeptId"

Or try
splitOn: "DeptID,Code"

**Comment by zivfuture** [comment]
@agpcardoso   thanks for reply ,   i tried and get the same error .
"When using the multi-mapping APIs ensure you set the splitOn param if you have keys other than Id (Parameter 'splitOn'"

**Comment by agpcardoso** [comment]
I think the reason some of your exceptions are here `conn.Query<Department,List<Employee>,List<Asset>,Department>`

try this `conn.Query<Department, Employee, Asset, Department>`

`
    using (var multi = cn.QueryMultiple(sql, new { id = i }))
    {
        var empresa = multi.Read<Empresa>().SingleOrDefault();

        if (empresa != null)
            empresa.Clientes = multi.Read<Cliente>().ToList();

        Console.WriteLine("=================");
        Console.WriteLine($"Empresa: {empresa.Id} - {empresa.Nome}");
        Console.WriteLine("Cliente(s):");
        empresa.Clientes.ToList().ForEach(c => Console.WriteLine($"  {c.Id} - {c.Nome}"));
    }
`

**Comment by agpcardoso** [comment]
I think the reason some of your exceptions are here conn.Query<Department,List<Employee>,List<Asset>,Department>

try this conn.Query<Department, Employee, Asset, Department>

**Comment by zivfuture** [comment]
@agpcardoso   yes ,i tried ```conn.Query<Department, Employee, Asset, Department>```  before you mentioned, 
it's too bad.   the error never changed.

**Comment by NickCraver** [comment]
"Mulit-mapping" as we call it (`.Query<T1, T2,..., TResult>`) is designed to hook many 1:1 things together, if you are doing 1:n relationships, you'll want to issue multiple queries, like you are - but that's a different API. You want `.QueryMultiple()` here, then call `.Read<T>` on each...and map them up in memory. There's an example usage [in the README here](https://github.com/StackExchange/Dapper/blob/main/Readme.md#multiple-results) :)
