### ISSUE TITLE
override DynamicParameters.ToString()

### ISSUE THREAD

**Issue by jalil1408** [DapperLib/Dapper#1545]
override DynamicParameters.ToString() to show the content of the parameters: [@p1: value1, @p2: value2, ...] for debug purposes

**Comment by brad-carr** [comment]
Relates to [Dapper.DbString should provide a useful override for .ToString()](https://github.com/StackExchange/Dapper/issues/1538)

**Comment by rohansp** [comment]
Is this already implemented? I would like to contribute.
