### ISSUE TITLE
Dapper insert composite SQL has brackets and does not support MySQL syntax.

### ISSUE THREAD

**Issue by LiuHui66** [DapperLib/Dapper#1564]
The combined SQL is  [databtable] ([datatable].[columnName], [datatable].[columnName], [datatable' at line 1  
With brackets, MySQL syntax is not supported.
Are there any settings？？

**Comment by mgravell** [comment]
The combines SQL *of what*? Please be very specific about what you are using here. There are multiple tools in the Dapper toolkit.
