### ISSUE TITLE
Q: Dapper for .Net 5?

### ISSUE THREAD

**Issue by BenHayat** [DapperLib/Dapper#1566]
Is there going to be new version of Dapper for .Net 5?
Thanks!

**Comment by mgravell** [comment]
We will almost certainly add a .NET 5 specific TFM at some point, but there isn't an explicit plan unless we hit things that *need* the new TFM. Otherwise, it'll mostly be for convenience and clarity - the existing package should already work just fine on .NET 5 if it doesn't: please let us know!

**Comment by BenHayat** [comment]
> 
> 
> We will almost certainly add a .NET 5 specific TFM at some point, but there isn't an explicit plan unless we hit things that _need_ the new TFM. Otherwise, it'll mostly be for convenience and clarity - the existing package should already work just fine on .NET 5 if it doesn't: please let us know!

Thanks for clarification and knowing the existing version works just fine.

**Comment by NickCraver** [comment]
Closing out to cleanup!
