### ISSUE TITLE
Microsoft.Data.SqlClient 2.1 -- Command Timeout is now a connection string property 

### ISSUE THREAD

**Issue by amrbadawy** [DapperLib/Dapper#1579]
According to the latest version of  [Microsoft.Data.SqlClient 2.1.0](https://github.com/dotnet/SqlClient/blob/master/release-notes/2.1/2.1.0.md#command-timeout-connection-string-property)  Command Timeout is now a connection string property that can be set like below 
`"Server:{serverURL}; Initial Catalog={db}; Integrated Security=true; Command Timeout=60"
`
Can it be considered the default value in case if parameter(commandTimeout) is passed as null or it can be set the default value of `SqlMapper.Settings.CommandTimeout.Value`

**Comment by mgravell** [comment]
There's a couple of complications there:

- you could have multiple different connections and thus connection strings in play
- we don't want to be parsing connection strings frequently

I would suggest: if you're using the default command timeout from the connection string, just leave the value in dapper as `null`, and everything should work in the way you expect?

**Comment by NickCraver** [comment]
Closing out to cleanup!
