### ISSUE TITLE
Add ability to reuse DbConnection

### ISSUE THREAD

**Issue by Alexx999** [DapperLib/Dapper#1581]
As of now, all Dapper methods accept IDbConnection which is fine, however, some implementations (namely, Microsoft.Data.Sqlite.Core) has pretty expensive DbCommand first use, in my case, the cost is almost 30% which is pretty significant.
And here comes the issue - there's no way in Dapper to cache the command, or, at least, I wasn't able to find it.
It's created by CommandDefinition and it's a struct and you cannot set new parameters to it anyway.

**Comment by NickCraver** [comment]
I'm going to collapse this one into #474 - same issue if we decide to tackle that approach :)
