### ISSUE TITLE
QuerySingleOrDefault throws on delete statement with output clause.

### ISSUE THREAD

**Issue by jakubiszon** [DapperLib/Dapper#1635]
Database - sqlserver
Exception message "incorrect syntax near 'output'"
The snippet which throws:
```
        Models.Address.PK deleted = Connection.QuerySingleOrDefault<Models.Address.PK>(SQLDelete, new {
		TenantID = tenantID
	,	AddressID = addressID
	});
```

My sql declaration:
```			
        public static string SQLDelete = @"
        delete from [Address]
        output
	        deleted.[TenantID]
        ,	deleted.[AddressID]
        where [TenantID] = @TenantID
        and [AddressID] = @AddressID
        ";
```

The SQL is correct and works with `Connection.Query<Models.Address.PK>` which I used as a work-around.

**Comment by mgravell** [comment]
"incorrect syntax" errors are coming from the RDBMS, not the client
library. What SQL Server version is this? Meaning: does it support the
OUTPUT clause? Since you say SQL Server: does that operation work in SQL
Server Management Studio.

**Comment by mgravell** [comment]
I just saw the comment about it working fine with just Query. That's ...
very odd. There isn't actually a fundamental difference in what gets
executed here - in particular, QuerySingleOrDefault doesn't use any
different flags (like "single row"), because it needs to check whether 2
rows come back. Do you perhaps have a minimum repro that shows this
exploding?

**Comment by jakubiszon** [comment]
If I find the time tomorrow I might create a repo but I can't promise that.
I also use QuerySingleOrDefault with `update output` and it works fine.
As for sqlserver version:
```
select @@version

Microsoft SQL Server 2017 (RTM-CU22-GDR) (KB4583457) - 14.0.3370.1 (X64) 	Nov  6 2020 18:19:52 	Copyright (C) 2017 Microsoft Corporation	Developer Edition (64-bit) on Linux (Ubuntu 16.04.7 LTS)
```

**Comment by mgravell** [comment]
> "I also use QuerySingleOrDefault with update output and it works fine."

The library *mostly* (there are some edge cases, like "in @foo") doesn't
care what the SQL is; it just sends it to the server as-is. So it is
increasingly interesting! I really am curious to see if we can (between us)
repro this on demand.

**Comment by odinserj** [comment]
Differences indeed come from SQL Server, which requires a little bit different syntax when using the `output` clause in the `delete` statements. Comparing to `update` statements, which allows to use `output` directly, we should use table aliases when combining `delete` and `output` in the following way:

```sql
delete A
output
        deleted.[TenantID]
,	deleted.[AddressID]
from [Address] A
where [TenantID] = @TenantID
and [AddressID] = @AddressID
```

So feel free to close this issue as it unrelated to Dapper anyway.
