### ISSUE TITLE
Can't results any thing and Progressing with async function 

### ISSUE THREAD

**Issue by zanyar3** [DapperLib/Dapper#1643]
When use dapper with asynchronized programing and localDb in windows form c# dapper can not retuns any thing and  program in Progressing 

```
using (IDbConnection connection = GetConnection)
{
     return  await connection.QueryFirstOrDefaultAsync<T>(sql, parameters);
}
```

But when change for no async work and return results 

```
using (IDbConnection connection = GetConnection)
{
     return  connection.QueryFirstOrDefault<T>(sql, parameters);
}
```

**My Connection String** =  `"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\MyDb.mdf; Integrated Security=True"`

## I used

- Dapper 2.0.78
- Windows form c# (Framework 4.8)
- Classlibaray (standart 2.0)

**Comment by mgravell** [comment]
You need to `await` the async call, otherwise you've killed the connection as soon as it left the box, before the result came back:

``` c#
using (IDbConnection connection = GetConnection)
{
     return await connection.QueryFirstOrDefaultAsync<T>(sql, parameters);
}
```

**Comment by NickCraver** [comment]
Closing out to cleanup!
