### ISSUE TITLE
Async methods with Synchronous behavior

### ISSUE THREAD

**Issue by fabionaspolini** [DapperLib/Dapper#1651]
**Issue**
I try to execute big queries with `conn.QueryAync<DTO>` method, but thread freezing when DB (Oracle) process the command. I think with QueryAsync should be fast to create the task and freeze only when call "await" instruction.

```csharp
var loadTask = conn.QueryAsync<DTO>("big query");
var load2Task = conn2.QueryAsync<DTO>("big query");
var load3Task = conn3.QueryAsync<DTO>("big query");

// Anothers instructions

Task.WaitAll(loadTask, load2Task, load3Task);
```

It's correct to freeze the thread at the first, second, and third queries?

How can I perform these three queries asynchronous and wait for all tasks to complete on the end of block?

**Versions:**
Dapper: 2.0.78  
Oracle.ManagedDataAccess.Core: 2.19.100

**Comment by mgravell** [comment]
`await` is cooperative; it is dependent on every part of the chain playing nicely. If someone does an "async over sync": you're toast. Dapper doesn't do an "async over sync" AFAIK, but if the Oracle provider does, then it is out of our hands.

Are you sure it is actually freezing a thread, rather than releasing it for async continuation? How are you measuring that?

**Comment by fabionaspolini** [comment]
I measuring on the debugger, when step over QueryAsync<DTO>("..."), is waiting for the result.  
I expected quickly go through QueryAsync and wait only when perform "Task.WaitAll"

**Comment by mgravell** [comment]
Well, what you're doing is fundamentally not supported on a single connection *anyway*. Connections aren't meant to run concurrent commands like this - what you are doing is effectively the same as using 3 threads simultaneously to access the same connection 3 times at once with regular non-async/await code. It would be fine with 3 different connections, but this isn't a magic trick to do 3 things at once on one connection. Honestly, I'm surprised it is working at all - it isn't *guaranteed* to work when used this way.

**Comment by fabionaspolini** [comment]
I made a mistake in the example, there are actually 3 separate connections in the code.  
Updated example.

I will make an example with another DB and share the code to facilitate the analysis.

**Comment by NickCraver** [comment]
This is indeed a known issue with Oracle - not a Dapper thing. Unfortunately, there's nothing we can do, they haven't added proper async support though users have complained about it for a little over a decade now. You can find more info and links to the Oracle threads here: https://stackoverflow.com/questions/29016698/can-the-oracle-managed-driver-use-async-await-properly

**Comment by nRoger-Env** [comment]
I just want to say that QueryAsync now works properly for Oracle using the latest ODP.NET core drivers. But, as mgravell wrote above, you absolutly need to have a separate connection for each Task. Using the same connection will make the code execute synchronously as before. Also, the connections don't have to be opened manually.
