### ISSUE TITLE
stackexchange.github.io/Dapper 404

### ISSUE THREAD

**Issue by paulomorgado** [DapperLib/Dapper#1656]
The stackexchange.github.io/Dapper link on the [release notes section of  Reademe.md](https://github.com/DapperLib/Dapper#release-notes) reports 404.

**Comment by mgravell** [comment]
Thanks; casualty of the org move; fixed

**Comment by shps951023** [comment]
Why need to change org?

**Comment by mgravell** [comment]
no, nothing like that; simply an acknowledgement that Dapper is a thing unto itself, and to allow us to group a few Dapper-related repos together in a logical "dapper" space, without it being confused with other SE stuff, and to solve some security things where ACLs require "org" access, and we only want it to have access to Dapper repos, not all of the SE stuff.

**Comment by shps951023** [comment]
Thank you so much @mgravell  for answer!
