### ISSUE TITLE
Dapper + Sqlite "returning" clause

### ISSUE THREAD

**Issue by justanothergituser** [DapperLib/Dapper#1669]
Good morning. I'm working on a project and just stumbled upon Sqlite's newer "returning" clause (link below). Looked around a bit and couldn't find any documentation for using it. Also tried a few things with no luck. Is this clause usable with Dapper? If not, are there plans to add it? Only been using Dapper for a short while courtesy of iamtimcorey.com videos. Really good stuff! On both accounts. Thank you!

https://www.sqlite.org/lang_returning.html

**Comment by mgravell** [comment]
Assume we're not all sqlite users. What is the returning syntax, and how
does it interact with vanilla ADO.NET?

**Comment by justanothergituser** [comment]
My apologies! Figured the Sqlite link would be enough for the developers. I only "know enough to be dangerous" myself.

**RETURNING Clause**

DELETE, INSERT and UPDATE queries now can return the rows that they deleted, added, or changed respectively.

`create table users (
  id integer primary key,
  first_name text,
  last_name text
);

insert into users (first_name, last_name)
values ('Jane', 'Doe')
returning id;`

https://antonz.org/sqlite-3-35/

Hopefully the above is what you were asking about. I know nothing about vanilla ADO.NET.

**Comment by mgravell** [comment]
It sounds like it works like the "output" clause in SQL Server, then; in
which case: have you tried execute the operation using Query<T> for some T
that matches the columns that you're returning?

**Comment by justanothergituser** [comment]
It seems that SQLite 3.35 hasn't been included in System.Data.Sqlite yet, according to the release notes.

> 1.0.114.0 - May XX, 2021 (release scheduled)
> - Updated to SQLite 3.35.5.

Sorry for the confusion mgravell. Didn't do my own due diligence. Thank you for seeking to assist.

**Comment by NickCraver** [comment]
Glad we got to the root of it - closing out to cleanup!

**Comment by rhinox202** [comment]
Can we get this issue opened back up? Hopefully I am just missing something (see code below), but it seems that the "returning" clause is not currently supported by Dapper. Can I get some verification on this? Thank you!

**Regular ADO (working)**
```
using (var connection = new System.Data.SQLite.SQLiteConnection(@"Data Source=Fuel.db"))
{
        connection.Open();
        
        var command = connection.CreateCommand();
        command.CommandText =
        @"
	        INSERT INTO User_List
	        VALUES (null, 321, 'Bob', 1234)
	        returning id
        ";
        
        using (var reader = command.ExecuteReader())
        {
	        while (reader.Read())
	        {
		        var id = reader.GetInt32(0); //  String(0);
		        Console.WriteLine($"New User Id: {id}");
	        }
        }
}
```

**Dapper (not working)**

```
using (System.Data.IDbConnection con = new System.Data.SQLite.SQLiteConnection(@"Data Source=Fuel.db"))
{
        var user = new { Number = 987, Name = "Frank", Pin = 4321 };
        
        var p = new Dapper.DynamicParameters(user);
        //p.Add("Id", dbType: System.Data.DbType.Int32, direction: System.Data.ParameterDirection.Output);
        p.Add("Id", dbType: System.Data.DbType.Int32, direction: System.Data.ParameterDirection.ReturnValue);
        
        var test = con.Execute("insert into User_List (Number, Name, Pin) values (@Number, @Name, @Pin) returning Id", p);
        
        var newId = p.Get<int>("Id");
}
```

**Error Thrown by Dapper Example**
```
An unhandled exception of type 'System.NotSupportedException' occurred in System.Data.SQLite.dll: 'Specified method is not supported.'
   at System.Data.SQLite.SQLiteParameter.set_Direction(ParameterDirection value)
   at Dapper.DynamicParameters.AddParameters(IDbCommand command, Identity identity) in /_/Dapper/DynamicParameters.cs:line 260
   at Dapper.DynamicParameters.Dapper.SqlMapper.IDynamicParameters.AddParameters(IDbCommand command, Identity identity) in /_/Dapper/DynamicParameters.cs:line 151
   at Dapper.SqlMapper.<>c__DisplayClass165_0.<GetCacheInfo>b__0(IDbCommand cmd, Object obj) in /_/Dapper/SqlMapper.cs:line 1714
   at Dapper.CommandDefinition.SetupCommand(IDbConnection cnn, Action`2 paramReader) in /_/Dapper/CommandDefinition.cs:line 129
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2811
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 572
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 443
   at ComUI.Program.Main() in D:\Documents\ComUI\Program.cs:line 86
```
