### ISSUE TITLE
QueryAsync() against MS SQL Server crashes after repeated use

### ISSUE THREAD

**Issue by cha4osoOwll** [DapperLib/Dapper#1671]
public async Task<IEnumerable<T>> ReadAsync<T>(string sql, object param, int? commandTimeout = null)
        {
            await using var connection = new SqlConnection(_connectionString);
            connection.Open();
            return await connection.QueryAsync<T>(sql, param, null, 
                commandTimeout ?? _defaultCommandTimeout);
        }

This works once or twice, but after a few calls, the call to QueryAsync crashes with a generic "object reference not set to an instance of an object" error and no stack trace. The same code was working consistently against both MySQL and Oracle, and similar code using ExecuteAsync() is working against MS SQL Server with no issue - the problem appears to be specific to the combination of QueryAsync() and SQL Server.

**Comment by mxmissile** [comment]
QueryAsync and Sql Server is called a million times a day by others without this issue. What object is throwing the null ref exception? What does your debugger tell you?

**Comment by mgravell** [comment]
Any chance your param has properties that are causing these NREs itself? A
repro would be really useful. It a stacktrace. Or both.

**Comment by cha4osoOwll** [comment]
It happens after calling with the same parameters repeatedly. I agree that a stack trace would be useful. Sure wish I got one.

**Comment by cha4osoOwll** [comment]
Sync vs async issue in the surrounding framework running the code, nothing to do with the library. Closing.
