### ISSUE TITLE
Reading select query result into more than 7 types - Connection.QueryAsync<t1,t2,....,t10>

### ISSUE THREAD

**Issue by maulik-modi** [DapperLib/Dapper#1686]
I see that Dapper allows 7 resultset, what if I have 10 result set? Is there an extension method I can write?

**Comment by mgravell** [comment]
By result-set, do you mean vertically, i.e. separate result grids via
separate "select" queries? Because Dapper allows any number of those, via
the QueryMultiple API

The multi-generic API is for horizontally partitioned data, usually "join"
operations between different tables.

**Comment by maulik-modi** [comment]
https://github.com/DapperLib/Dapper/blob/main/Dapper/SqlMapper.GridReader.cs accepts maximum 7 Types

We intend to project flat resultset into hierarchical data based on start date, end date and subscriber Id, you can say activity and calling QueryMultiple with 7 T types.
```
select t1.*, t2.*, t3.*, t4.*
from t1
left join t2
left join t3
left join t4
```

**Comment by mgravell** [comment]
That query is still one result-set, hence my clarification. So; you're talking about one result-set partitioned horizontally into 8 types - fine. There closest option for that is the `Read<TReturn>` that takes a `Type[]` of the intermediate types.

**Comment by maulik-modi** [comment]
You are right. We intend to use something like below but get compile time error

`   var results = await conn.QueryAsync<t1,t2....,t10>`

```
select t1.*, t2.*, t3.*, t4.*, t5.*...,t10,.*
from t1
left join t2
left join t3
left join t4
...
left join t8
```

**Comment by mgravell** [comment]
yes, there isn't an overload with that many generics; so ... you can't do that; you can use the version of `Read<TReturn>` that takes a `Type[]`, though

**Comment by maulik-modi** [comment]
@mgravell , what overload you are referring to?

**Comment by mgravell** [comment]
`connection.Query<TReturn>(string sql, Type[] types, Func<object[], TReturn> map, object param = null, ....)`

The `types` parameter has the info for any number of intermediate objects, which are then combined by the `Func<object[], TReturn>`
