### ISSUE TITLE
Executing a command multiple times - a bit confusing

### ISSUE THREAD

**Issue by PureKrome** [DapperLib/Dapper#1688]
Hi 👋🏻 

I've always found the docs under the section [Execute a command Multiple Times](https://github.com/DapperLib/Dapper#execute-a-command-multiple-times) a bit confusing.

Would you be happy to accept a PR with another example (to add to the existing example, in this section) if you already have an existing collection/IEnumerable<T> ?

**Comment by mgravell** [comment]
absolutely! docs good; examples good; tests good

**Comment by PureKrome** [comment]
There we go @mgravell - PR made, ready for reviews, etc :) 🎉 👍🏻
