### ISSUE TITLE
Cannot get value from DapperRow

### ISSUE THREAD

**Issue by lbphp** [DapperLib/Dapper#1695]
![Untitled](https://user-images.githubusercontent.com/22989619/129492475-4e372b2e-d6fa-4683-aa20-18e27d766309.png)

As you can see from the Watch expressions, the record variable is a `DapperRow `having some columns and values. I have tried reading some of them but it gives me the error `object does not contain a definition for k`. 
Is that not the right way to get a column value?

**Comment by mgravell** [comment]
There are primary two ways of using Dapper

1. With typed POCOs
2. Via dynamic

I strongly prefer the first, via `Query<T>` for some type `T` that looks like your data, but you're using the second approach - which is fine. But: you're using the multi-row API, but it looks like you only want one row, in which case: consider `.FirstOrDefault()` or `QueryFirstOrDefault()`.

Then, when you have a single row, you can literally just access `.k` etc, and it will work by the power of `dynamic`. Alternatively, you *can* cast a single row to a `IDictionary<string,object>`, but that is not the intended primary API.

**Comment by mgravell** [comment]
Oh, also: parameters. **DO NOT CONCATENATE VALUES TO CREATE SQL**. Dapper has a parameters argument for that. Your code is ripe for SQL injection.

**Comment by lbphp** [comment]
Ok this is just to test if it is working, then i will use parameters.
It still doesn't work though
![Untitled](https://user-images.githubusercontent.com/22989619/129614897-de0ad4d1-e0a6-4cae-8989-da0c8969af06.png)

**Comment by mgravell** [comment]
I'm not going to try and debug from images. If you post code, I'll try and
post a version of it that should work - but obviously I can't test it
without your DB. But I'm not going to sit and try to transcribe long code
from images. Plus, images are terrible for "accessibility".
