### ISSUE TITLE
Why is this library upgraded from .net framework 4.5 to 4.6 since v2? 

### ISSUE THREAD

**Issue by JerryJian** [DapperLib/Dapper#1701]
Hi, 

I wonder to know why is this library upgraded from .net framework 4.5 to 4.6 since v2? 

Thanks!

**Comment by mgravell** [comment]
Ultimately the removal of very old runtimes comes under the points discussed here: https://blog.marcgravell.com/2020/01/net-core-net-5-exodus-of-net-framework.html

In a quick build test, the only *break* between net451 (the TFM used in the last v1.x build) and net461 is a relatively easy one to hack around - `Array.Empty<T>`; but all of the testing/support points raised in that post: remain - along with the note that net451 was end-of-life in January 2016. Given that net452 (the last of the net45x) is end-of-life in April 2022, I'm not sure there's a *huge* benefit to "the greater good" with us adding it back, especially when v1.x continues to work and do the needful.

**Comment by JerryJian** [comment]
Thanks for the explanation @mgravell .
