### ISSUE TITLE
GridReader ReadAsync support for Func<> like Read<T1,T2,T3>

### ISSUE THREAD

**Issue by stefanMinch3v** [DapperLib/Dapper#1705]
Hi there,
Trying to make the code async-await all the way,
I have a case where I need to map one to many objects and at the same time I need to have another select statement in that sql.
I'm already using `QueryMultipleAsync` but I'm not sure if this is enough because I see there is also ReadAsync but does not accept Func<>.
The plan is to wrap this in a command definition and use cancellation tokens and I'm not sure if `multi.Read` has to be async to achieve that?

`var sql = $@"
                SELECT 
                    s.Id,
	            s.[Name], 
	            s.[Description], 
	            s.[Address], 
                    r.Id,
                    r.Ratings,
                    r.Prices,
                    r.ServiceId
                FROM {TABLE_NAME_SERVICES} AS s
                LEFT JOIN {TABLE_NAME_REVIEWS} AS r
                    ON vs.Id = r.ServiceId
                ORDER BY s.Id DESC
                OFFSET @page ROWS FETCH NEXT @pageSize ROWS ONLY;

                SELECT COUNT(*) FROM {TABLE_NAME_SERVICES};";`
`
            using (var conn = this.dbFactory.GetConnection)
            {
                var parameters = new
                {
                    page = (page - 1) * pageSize,
                    pageSize = pageSize
                };

                var servicesDict = new Dictionary<int, Service>();

                using (var multi = await conn.QueryMultipleAsync(sql, parameters))
                {
                    var result = multi.Read<Service, Review, Service>((serviceDb, reviewDb) =>
                    {
                        if (!servicesDict.TryGetValue(serviceDb.Id, out Service service))
                        {
                            service = serviceDb;
                            service.Reviews = new HashSet<Review>();
                            servicesDict.Add(service.Id, service);
                        }

                        if (reviewDb != null)
                        {
                            var reivew = new Review
                            {
                                Id = reviewDb.Id,
                                VehicleServiceId = reviewDb.ServiceId,
                                Ratings = reviewDb.Ratings,
                                Prices = reviewDb.Prices
                            };

                            service.Reviews.Add(reivew);
                        }

                        return service;
                    })
                    .Distinct()
                    .ToArray();

                    var totalCount = multi.ReadFirstOrDefault<int>();

                    return (result, totalCount);
                }
            }`

**Comment by jesusvaz82** [comment]
@stefanMinch3v Dapper currently doesn't have a method to read more than one result in the GridReader at time, I created a new PR (https://github.com/DapperLib/Dapper/pull/1712) to add the method `ReadMultiple<(T1,T2,T3...Tn)>` which it allow read multiples results in one call.

**Comment by stefanMinch3v** [comment]
Awesome, will keep an eye on it then :)
