### ISSUE TITLE
A connection was successfully established with the server, but then an error occurred during the login process.

### ISSUE THREAD

**Issue by hw2cb** [DapperLib/Dapper#1709]
Asp Core 2.1
I use MS SQL SERVER
db.Query<Car>("SELECT * FROM Автомобили").ToList();
Error:
"Microsoft.Data.SqlClient.SqlException: "A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - Цепочка сертификатов выпущена центром сертификации, не имеющим доверия.)""
I try install Microsoft.AspNetCore.Authentication.Certificate, but it is not installed, requires net5.

**Comment by mgravell** [comment]
Ultimately, Dapper requires a working connection to the server. I can't help you fix that - that's specific to your setup, not Dapper. Basically: until you can successfully call Open() on a connection: Dapper doesn't stand a chance.

**Comment by Varooneh** [comment]
You get this error when you want use [Windows authentication mode] on domain network or other users [except sa] can not load or use certificate or local login name can not access to database. If you can not access to database from SSMS, add this option `Trusted_Connection=Yes` to connection string, else follow this steps:
[Reference](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/1e252688-14e2-42d4-95b9-ab9438535e4a/how-do-you-set-up-a-trusted-sql-account?forum=sqlsecurity)
1. Get into the MSSMS for your database.
2. Under databases you will find Security.  Expand it.
3. Under Security you will find Logins.  Expand it.
4. Right Click on Logins and Click New Login.
5. Create a Login Name: LoginName
6. Click SQL Server Authentication Radio Button.
7. Create a password and confirm it.
8. Remove the check box for Enforce password experation and Unser must change password at next login.
9. Default database:  Find the database you want this login to goto by default.
10. Goto User Mapping under Select a page in the upper Left corner.
11. Check the database(s) that this login will have access to and the roles you want them to have in that database.
12. Click OK
13. Open the database that this login will use.
14. Expand the security folder.
15. Expand the Users folder.
16. Double click on the login that you just created.
17. Under he general page give the login the Role Memebership that it needs.
18. Click OK.

I hope it helps you.

**Comment by hw2cb** [comment]
Hi, I added to the connection string:
`trust server certificate=True`
and its work! 

> You get this error when you want use [Windows authentication mode] on domain network or other users [except sa] can not load or use certificate or local login name can not access to database. If you can not access to database from SSMS, add this option `Trusted_Connection=Yes` to connection string, else follow this steps: [Reference](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/1e252688-14e2-42d4-95b9-ab9438535e4a/how-do-you-set-up-a-trusted-sql-account?forum=sqlsecurity)
> 
> 1. Get into the MSSMS for your database.
> 2. Under databases you will find Security.  Expand it.
> 3. Under Security you will find Logins.  Expand it.
> 4. Right Click on Logins and Click New Login.
> 5. Create a Login Name: LoginName
> 6. Click SQL Server Authentication Radio Button.
> 7. Create a password and confirm it.
> 8. Remove the check box for Enforce password experation and Unser must change password at next login.
> 9. Default database:  Find the database you want this login to goto by default.
> 10. Goto User Mapping under Select a page in the upper Left corner.
> 11. Check the database(s) that this login will have access to and the roles you want them to have in that database.
> 12. Click OK
> 13. Open the database that this login will use.
> 14. Expand the security folder.
> 15. Expand the Users folder.
> 16. Double click on the login that you just created.
> 17. Under he general page give the login the Role Memebership that it needs.
> 18. Click OK.
> 
> I hope it helps you.
