### ISSUE TITLE
Non-nullable string enforcement

### ISSUE THREAD

**Issue by ivanduka** [DapperLib/Dapper#1714]
Hi,

Dapper is awesome as it enforces non-nullable integers, for example.
However, how can I enforce **_non-nullable strings_** with Dapper while **in nullable mode**?
Is it a bug or by design that Dapper does not throw when assigning null to a non-nullable string?

Research led me to understanding that there is no such thing as a non-nullable string in C#. Does it mean that there is no solution for enforcing non-nullable strings?

```csharp
#nullable enable

using System;
using System.Linq;
using Dapper;
using Microsoft.Data.SqlClient;

namespace ConsoleApp2
{
    internal static class Program
    {
        private static void Main()
        {
            var connStr = "TrustServerCertificate=True;Integrated Security=true;Server=localhost;Database=MyDB;";

            using var db = new SqlConnection(connStr);
            db.Open();

            // Does not fail! How can I fail here instead of assigning null to non-nullable type?
            Console.WriteLine("string NULL");
            Console.WriteLine(db.Query<string>("SELECT NULL").Single() == null);

            // Allows null for nullable int, all good
            Console.WriteLine("int? NULL");
            Console.WriteLine(db.Query<int?>("SELECT NULL").Single() == null);
            
            // Fails as expected to assign null to non-nullable integer, unlike string
            Console.WriteLine("int NULL");
            Console.WriteLine(db.Query<int>("SELECT NULL").Single() == null);
        }
    }
}
```

**Comment by khairuzzaman** [comment]
Hi,
What is the actual use case for this. If your database table enforce the not null constraint for the column then you cannot insert null value for that column and select will always return non-null value.

If column allow null value and you does not want the null value in your query then apply filter in the query.

**Comment by roederja** [comment]
The idea is that you match the nullability of your string types to what you expect to get back from the query. But you need Dapper to enforce this as otherwise the null checking with nullable reference types will not work correctly as it will assign null to a non nullable string anyway.
