### ISSUE TITLE
Performcance with ExecuteReaderWithFlagsFallback 

### ISSUE THREAD

**Issue by attiqeurrehman** [DapperLib/Dapper#1729]
Hi,

I have been trying out the DotTrace to investiagte some of the hotspots in the app I am working on and I noticed that `ExecuteReaderWithFlagsFallback ` is one such hotspots. 

```
100.00%   ExecuteReaderWithFlagsFallback  •  9,230 ms  •  4,540 calls  •  Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand, Boolean, CommandBehavior)
  99.95%   ExecuteReader  •  9,225 ms  •  4,540 calls  •  System.Data.Common.DbCommand.ExecuteReader(CommandBehavior)
  0.02%   GetBehavior  •  1 ms  •  4,540 calls  •  Dapper.SqlMapper.GetBehavior(Boolean, CommandBehavior)
```

Is there anything can be done to improve it or is this something we will have to live with it. 

Thanks.

**Comment by mgravell** [comment]
That is the code that actually executes the ADO.NET command. It seems very
likely to me that what you're measuring here is the inherent ADO.NET and
RDBMS costs. That's something outside of Dapper's control, but if that
method is taking almost all of the time: ***that's great***: it means the
rest of Dapper (the bit that reshapes the API to make it convenient and
easy to use): *isn't* taking the time.

**Comment by mgravell** [comment]
Of course, "make your SQL faster" is always good advice, but that's beyond
what I can cover here (especially without SQL to look at), and it is highly
dependent on the RDBMS and the data being queried.

**Comment by attiqeurrehman** [comment]
thanks for a quick respone.
