### ISSUE TITLE
NotSupportedException: The member createdat of type System.DateOnly cannot be used as a parameter value

### ISSUE THREAD

**Issue by talley** [DapperLib/Dapper#1731]
NotSupportedException: The member createdat of type System.DateOnly cannot be used as a parameter value

**Comment by talley** [comment]
I had this in my model declaration and dapper was upset about it.
  public DateOnly Createdat { get; set; }

**Comment by mgravell** [comment]
Cross-referencing https://github.com/DapperLib/Dapper/issues/1728

If you're using Npgsql or any if the other providers that allow this: I aim to merge the relevant PR this week. If you're using SqlClient (SQL Server): the provider itself doesn't support it yet.

**Comment by mgravell** [comment]
(closing as dup of 1728)
