### ISSUE TITLE
Exception while reading GridReader in QueryMultiple with SoredProcedure

### ISSUE THREAD

**Issue by chandan009** [DapperLib/Dapper#1732]
Hi

I am getting below error while reading gridreader 

Error : - 

{"The member Comparer of type System.Collections.Generic.IEqualityComparer`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] cannot be used as a parameter value"}

My code - 

connection.QueryMultiple(storedProcedureName, parameters, commandTimeout: this.commandTimeoutSec, commandType: System.Data.CommandType.StoredProcedure);

Dapper Version - Dapper.2.0.123

Thank You!

**Comment by mgravell** [comment]
That code doesn't really allow me to repro much - I have no idea what the parameters look like, no idea what the shape of the proc is, and no idea what the reading code looks like. At best, I can guess the method overload being used, but the existing tests should cover the general case, so I expect the error here is quite specific. I don't even know what database kind we're talking to, in case that matters.

I think the most important thing will be: what is the value of `parameters` here?

**Comment by chandan009** [comment]
Found solution - Already answered in below issue

[https://github.com/DapperLib/Dapper/issues/1580](https://github.com/DapperLib/Dapper/issues/1580)

**Comment by chandan009** [comment]
> 

Yes Marc, Issue was with parameters , That was a  Dictionary<string, object> parameters which was causing issue. Now, I changed that to DynamicParameters which Fixed my issue.


Thank You!
