### ISSUE TITLE
Upgrade to NPgsql 6.01 single row delete results in mass delete

### ISSUE THREAD

**Issue by klaasbrant** [DapperLib/Dapper#1736]
After I upgraded to NPgsql version 6.01 I have hit two problems: 
1. the update of varchar results: PostgresException: 42883: operator does not exist: @ text POSITION: 33
2. the delete of a single record like this:
        public async Task<bool> Delete(T entity)
        {
            GetDb();
            return await _dbConnection.DeleteAsync(entity);
        }
results in mass delete as if there was no where condition. I verified in debug session and the object used has a value in id column which is in the table a PK column. 
This was the combo NPgsql 6.01 with Dapper 2.0.123.
After I restore the database and fall back to NPgsql 5.0.11 everything was normal again.
I have done the test twice with same results. Dapper problem or NPgsql problem?

**Comment by mgravell** [comment]
Well, that's alarming. I take it we're really talking about "dapper.contrib" here? Something that shows a repro of either (or both) would be useful. (/cc @roji for visibility, but without any presumption of cause)

**Comment by roji** [comment]
An Npgsql-only repro would be ideal for me to investigate this... But otherwise at least a fully runnable Dapper code sample would help.

**Comment by klaasbrant** [comment]
Yes it is dapper.contrib. Good and bad news, I **cannot** reproduce in simple console application. However in my asp.net core MVC application I can reproduced. Maybe dependency injection? But how? If I debug this:
            var x = await _dbConnection.GetAllAsync<Course>();
            bool b =  await _dbConnection.DeleteAsync(entity);
            var y = await _dbConnection.GetAllAsync<Course>();
All are in the same repository method...
I see all records in x, b = true  and oject has an value in id and should delete only 1 record. But y is an empty Icollection?

**Comment by mgravell** [comment]
It is going to be very hard for me to help without some kind of repro.
Ultimately, we can't see your repository etc code from here: anything we
say would be pure guesswork, especially since you say it doesn't repro in
the minimal console case.

**Comment by klaasbrant** [comment]
The problem is related to key column named Id in model. When Id it causes mass delete, when all lowercase id it works.
When I change in the console project the column to Id then it fail, but not with mass delete but with "column Id does not exist".
Will share repo when done some more debugging.

**Comment by klaasbrant** [comment]
The other issue is also related to column names being in mixed case. Is there a change in Npgsql V6 that mixed column names work different compared to V5.0.11?

**Comment by mgravell** [comment]
I have to say... my curiosity is piqued

**Comment by mgravell** [comment]
I do seem to recall case sensitivity of parameters changed, so it wouldn't amaze me if it was wider than that. But @roji is the oracle of that (pun intended).

**Comment by roji** [comment]
Npgsql 6.0 indeed made parameter placeholder names case-sensitive ([see breaking change note](https://www.npgsql.org/doc/release-notes/6.0.html#parameter-names-now-use-case-sensitive-matching)), but that shouldn't have anything to do with column name.

I think we're really going to need some sort of code sample here.

**Comment by klaasbrant** [comment]
Finally nailed it! The failing project uses dapper.contrib 2.0.91 and not the current 2.0.71 from nuget. That version (2.0.91) allows camel case attribute names in the models and all is fine with NPgsql V5.011. But when I upgrade to the new V6 NPgsql  the mass delete occurs and the updates fail. You can test yourself with my test program on github klaasbrant/testdapper.  The current version on nuget for dapper,contrib (2.0.71) does not allow for camelcase attribritued and NPgsql  will protest that e.g. Id column does not exist.

**Comment by roji** [comment]
So it's important to understand that PostgreSQL (not Npgsql) folds unquoted identifier names (table, column...) to lowercase. So `SELECT Id FROM Blogs` is actually evaluated by PG as `SELECT id FROM blogs`; you can quote identifier to preserve case (`SELECT "Id" FROM "Blogs"`).

This again has nothing to do with Npgsql - it's just PG behavior - so it's hard to see how Npgsql 5 vs. 6 could play a role here. Either way, a simple, runnable code sample would really help!

**Comment by klaasbrant** [comment]
Hi Shaj, It is a dapper.contrib issue. I have created a test program, just pull  [klaasbrant/testdapper](https://github.com/klaasbrant/testdapper) 
It has dapper.contrib v 2.0.91 that works with V5 and fails with V6

**Comment by klaasbrant** [comment]
Then again, having said that... nothing changes except the NPgsql interface and by magic all row disappear :-)

**Comment by roji** [comment]
@klaasbrant some notes on your repro:

* Your csproj contanis some reference to a Dapper.Contrib.dll on your filesystem, that obviously doesn't work here. I changed that to a standard `<PackageReference>` to version 2.0.78, which is the latest version on nuget.org. Above you mention 2.0.91 - I don't know where that version is coming from.
* Your table is created with unquoted column `Name`, which as I explained above is folded to lowercase `name` by PostgreSQL. As a result, the Dapper.Contrib insertion fails with `column "Name" of relation "persons" does not exist`.
* The same happens with `Id`, but apparently Dapper.Contrib adds a `RETURNING Id` clause to the insertion - the column must be quoted. This is a Dapper.Contrib issue (/cc @mgravell). It's possible to work around it by using only lower-case letters in the column name (`id`); I'm not sure how to define the column name for Dapper.Contrib, so I just lower-cased the .NET property.

Once I corrected all of the above, I got the output below - no indication of any rows disappearing magically.

<details>
<summary>Output</summary>

```
Create table
Insert Data
Inserted 1 - Mary
Inserted 2 - Joseph
Inserted 3 - Jesus
Data is now:
List Data
Found 3 records
Retrieved 1 : Mary                     
Retrieved 2 : Joseph                   
Retrieved 3 : Jesus                    
List Data
Found 3 records
Retrieved 1 : Mary                     
Retrieved 2 : Joseph                   
Retrieved 3 : Jesus                    
delete data, data before:
List Data
Found 3 records
Retrieved 1 : Mary                     
Retrieved 2 : Joseph                   
Retrieved 3 : Jesus                    
Delete key: 3
delete data, data after:
List Data
Found 2 records
Retrieved 1 : Mary                     
Retrieved 2 : Joseph                   
drop table
```

<details>

**Comment by klaasbrant** [comment]
Me being bad... the V2.0.91 was pulled from github a while ago
[Dapper.Contrib.zip](https://github.com/DapperLib/Dapper/files/7740762/Dapper.Contrib.zip)
Here is a copy that is used in the project.

**Comment by mgravell** [comment]
We also have a myget feed, but I don't see a 2.0.91 there (although we do go higher). On Monday I'll check whether the issue recurs with the current myget latest, and see if I can spot any obvious changes (although the fact that we haven't deployed it suggests: not).

Truth told, I don't know an awful lot about "contrib" (hence the name), but I'll see if we can do something to make the PGsql version more quoted.

**Comment by klaasbrant** [comment]
The dapper repo was pulled from github on May 2nd, 2021.

**Comment by roji** [comment]
@klaasbrant using the assembly you provide I start getting `column "name" of relation "persons" does not exist` - it seems like Dapper.Contrib starts sending out the following INSERT: `insert into persons ("name") values ($1) RETURNING id`. I'm not sure why `name` is now lower-case - that may be a bug. I renamed the .NET property to lower-case `name` to work around this.

At this point I get the same output as I posted above, with no trace of rows disappearing. I'd like to continue investigating, but as I've said several times already, I need a *fully runnable* code sample with clear instructions on how to reproduce the specific problem you're reporting here (rows magically disappearing with Npgsql 6.0 but not with 5.0).

**Comment by klaasbrant** [comment]
More digging... I found out that the Dapper.Contrib was modified by another colleague (thanks for not documenting) to force column names to lower case.  So this delete sql is generated as: **delete from persons where "id" = @id**
and then executed as:  **var deleted = conn.Execute(<delete-sq-abovel>, p1)**; passing the p1 object with Id as attribute and not id in lowercase. I change the code in my example and yep in V5 it deletes one row in V6 it deletes them all as if the where is gone and no error message it cannot find id.

**Comment by mgravell** [comment]
with the greatest will in the world: we can't really offer advice or support on code that has been changed locally; I'm as intrigued as you are here, but the first step has to be: repro - and we simply can't do that from here.

**Comment by klaasbrant** [comment]
Update: When running V6 with AppContext.SetSwitch("Npgsql.EnableLegacyCaseInsensitiveDbParameters", true);
then the all is well like in V5.  
So the whole issue is NOT a dapper issue but NPgsql issue.

**Comment by klaasbrant** [comment]
@mgravell Sorry for the fuzz, I thought the project used standard nuget packages. I am really not a fan of locally modified open source. I only found out after myget package (now at 114) also gave errors about the camelcase. Thanks to git I could see that local changes were made

**Comment by klaasbrant** [comment]
This ticket can be closed because it is not a dapper issue. @roji Should I open a ticket for NPgsql? I read about the change the breaking chance: Parameter names now use case-sensitive matching. I understand and it is cool there is a parameter to get the old behavior. But dropping a where clause is a bug I geuss.

**Comment by mgravell** [comment]
"dropping a where clause" a: seems like a server issue, not an ADO.NET provider issue, and b: seems *very* unlikely - I'm not saying it can't have happened; stranger things have and do! but: a minimal repro is key here, I think

**Comment by roji** [comment]
> Should I open a ticket for NPgsql?

Yes please - and please include a runnable repro using Npgsql code, ideally. I'm as curious as @mgravell to see how parameter name case sensitivity could lead to a dropped where clause...
