### ISSUE TITLE
 QueryAsync Method sometimes throw exception  'Object reference not set to an instance of an object' on GetColumnHash  

### ISSUE THREAD

**Issue by xhanb** [DapperLib/Dapper#1739]
When I Use QueryAsync Method, like under codes:
 string[] sqls = { "select data from table where endTime>=\@beginTime  and  endTime<=\@endTime"};
vat tasks= sqls.Select(sql =>
                    {
                        using var dbConnection = ContextFactory.CreateDbConnection("ConnectionStr");
                        return dbConnection.QueryAsync<Record>(new CommandDefinition(sql,
                             new { beginTime = beginTime.ToString("yyyy-MM-dd 00:00:00"), endTime = endTime.ToString("yyyy-MM-dd 23:59:59.999") }, cancellationToken: cancellationToken, commandTimeout: 111));
                    }
var queryResults = await Task.WhenAll(tasks);

sometimes throw:
Object reference not set to an instance of an object
at Dapper.SqlMapper.GetColumnHash(IDataReader reader, Int32 startBound, Int32 length) in /_/Dapper/SqlMapper.cs:line 38\n at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 420

I can not find the reason

**Comment by mgravell** [comment]
That's an easy one: because you aren't using `await` on `QueryAsync`, it is entirely possible (highly likely, even) for the connection to be disposed during the query, by exiting the `using` while an active incomplete task is in flight. You're in a thread-race between the network and the CPU, so it won't fail every time.

Basically: make sure you `await` so the `using` doesn't leave scope until you're actually done with the connection.

**Comment by xhanb** [comment]
@mgravell 
Thanks a lot, it is my falut.Is right fix it like this?
'''
vat tasks= sqls.Select( async sql =>
{
using var dbConnection = ContextFactory.CreateDbConnection("ConnectionStr");
return await dbConnection.QueryAsync(new CommandDefinition(sql,
new { beginTime = beginTime.ToString("yyyy-MM-dd 00:00:00"), endTime = endTime.ToString("yyyy-MM-dd 23:59:59.999") }, cancellationToken: cancellationToken, commandTimeout: 111));
}
'''

**Comment by mgravell** [comment]
Looks ok to me, but I'm looking casually here. Does it work better?

**Comment by xhanb** [comment]
> Looks ok to me, but I'm looking casually here. Does it work better?

@mgravell 
I don't have any other good ideas. Can you give me some updated suggestions? Like some pseudo-code, thank you

**Comment by mgravell** [comment]
Suggestions to what? You haven't told me whether there's still a problem...

**Comment by xhanb** [comment]
> Suggestions to what? You haven't told me whether there's still a problem...

😂 I think i had fix it,thanks your advice.@mgravell
