### ISSUE TITLE
about dynamic parameters order issue using OleDb.

### ISSUE THREAD

**Issue by czh0221** [DapperLib/Dapper#1741]
I tried to use Dapper to construct SQL and insert parameter data into Excel, and the column values were confused. 

The scenario is as follows:

The template column names defined by Excel are:
Id,LoginName,NickName,Gender,MobileNumber,CreatedAt,CreatedBy.

Construct insert SQL and parameters as follows:
INSERT INTO [Customer$] ([Id], [LoginName], [NickName], [Gender], [MobileNumber], [CreatedAt], [CreatedBy]) VALUES (@Id, @LoginName, @NickName, @Gender, @MobileNumber, @CreatedAt, @CreatedBy)

The parameter in the execute parameter method is the entity class Customer:
new Customer { Id = 473334215076, LoginName = "cKgwCugcMn", NickName = "entity", Gender = 1, MobileNumber = "12345678" }

Insert the result as follows:
Id,LoginName,NickName,       Gender,             MobileNumber,           CreatedAt,      CreatedBy
   ,       ,             1,            473334215076,   cKgwCugcMn,                     12345678,         entity

The problem may be that params sort in CreateParamInfoGenerator method.  

When I tried to change the execution parameters to anonymous classes, the insertion order was normal.  
new { Id = 473334215076, LoginName = "cKgwCugcMn", NickName = "entity", Gender = 1, MobileNumber = "12345678" }

Are there other solutions?

[Note]
When inserting access data, OleDbErrorCollection exception will be caused by parameter sorting problem.  

the order in which OleDbParameter objects are added to the OleDbParameterCollection must directly correspond to the position of the question mark placeholder for the parameter in the command text.

If the parameters in the collection do not match the requirements of the query to be executed, an error may result.

https://docs.microsoft.com/en-us/dotnet/api/system.data.oledb.oledbcommand.parameters?redirectedfrom=MSDN&view=dotnet-plat-ext-6.0

**Comment by mgravell** [comment]
Do you have code that shows your call here? In particular, I'm confused by two things:

1. the SQL you show has more parameters than you are passing
2. the SQL you show is using `@foo`-style parameters, but you cite OleDb

Dapper does have an alternative syntax for pseudo-positional parameters, which I will dig up when I've had coffee; I want to say `?foo?`, but I'll check.

**Comment by czh0221** [comment]
> 
thanks for your help.

1. the SQL you show has more parameters than you are passing
 It is SQL generated automatically through POCO.

2. the SQL you show is using @foo-style parameters, but you cite OleDb
Create Connection by DbProviderFactories.GetFactory("System.Data.OleDb");

The code is as follows:
public class CustomerEntity
    {
        public long Id { get; set; }

        public string LoginName { get; set; }

        public string NickName { get; set; }

        public int Gender { get; set; }

        public string MobileNumber { get; set; }

        public DateTime? CreatedAt { get; set; }

        public string CreatedBy { get; set; }
    }
    
 public void Dapper_Insert()
        {
            var customer = new CustomerEntity
            {
                Id = 10000,
                LoginName = "loginName",
                NickName = "entity",
                Gender = GenderType.Male,
                MobileNumber = "1234567",
                CreatedAt = DateTime.Now,
                CreatedBy = "system"
            };

            using (var connection = DbProviderFactories.GetFactory("System.Data.OleDb").CreateConnection())
            {
                connection.ConnectionString = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=|DataDirectory|\App_Data\Customers_Excel.xlsx;Extended Properties='Excel 12.0 Xml;HDR=YES;IMEX=0';";

                var sql = "INSERT INTO [Customer$] ([Id], [LoginName], [NickName], [Gender], [MobileNumber], [CreatedAt], [CreatedBy]) VALUES (@Id, @LoginName, @Nickname, @Gender, @MobileNumber, @CreatedAt, @CreatedBy)";
                connection.Execute(sql, customer);
            }
        }

**Comment by mgravell** [comment]
Once again, I have no idea how that is even doing *anything* with OleDb; OleDb is typically ordinal, not nominal; the expected usage here for Dapper would be:

``` c#
const string sql = "INSERT INTO [Customer$] ([Id], [LoginName], [NickName], [Gender], [MobileNumber], [CreatedAt], [CreatedBy]) VALUES (?Id?, ?LoginName?, ?Nickname?, ?Gender?, ?MobileNumber?, ?CreatedAt?, ?CreatedBy?)";
```

Dapper will substitute the `?foo?` tokens with `?`, but use the original positions for the order. Try the above, and let me know how you get on.

**Comment by czh0221** [comment]
@mgravell  
thank you!!!  got it.  it's work.  I will adjust the parameter style.
