### ISSUE TITLE
Return the ID (Primary Key) of the last inserted row in SQL.

### ISSUE THREAD

**Issue by LeoRis** [DapperLib/Dapper#1749]
Hello Dapper enthusiasts :)

I have a table in my DB called "Address", which consists of the following columns: AddressId (Primary Key), Street, Number, PostalCode, City, State, Province, Country, IsActive, IsDeleted.

I am working on a method that inserts data into SQL table, but I want to get the ID ( AddressId - my Primary Key) that the inserted row gets.

Here is my code:

```
public int GetAddressId { get; set; }

public void InsertAddress(string street, string number, string postalCode, string city, string state, string province, string country, string isActive, string isDeleted)
        {
            using(IDbConnection connection = new System.Data.SqlClient.SqlConnection(Helper.ConnectionValue("DMS")))
            {
                Addresses newAddress = new Addresses
                {
                    Street = street,
                    Number = Convert.ToInt32(number),
                    PostalCode = Convert.ToInt32(postalCode),
                    City = city,
                    State = state,
                    Province = province,
                    Country = country,
                    IsActive = Convert.ToInt32(isActive),
                    IsDeleted = Convert.ToInt32(isDeleted)
                };

                List<Addresses> addresses = new List<Addresses>();

                addresses.Add(newAddress);

                GetAddressId = connection.Execute(
                                           "INSERT INTO dbo.Address 
                                            VALUES(@Street, @Number, @PostalCode, @City, @State, @Province, @Country, @IsActive, @IsDeleted); 
                                            SELECT SCOPE_IDENTITY();", addresses);
          }
}
```
I tried everything: SCOPE_IDENTITY(), @@IDENTITY, IDENT_CURRENT('tablename') and they all return 1. 
I have created a stored procedure and tried RETURN, or OUTPUT there but nothing works.
And my last ID in my table is 1000429.

Any kind of advise here would be much appreciated :)

Many thanks in advance.

**Comment by mgravell** [comment]
`Execute` performs a non-query operation. The moment you `select` something (such as `SCOPE_IDENTITY()`), *you are performing a query*, and `Execute` is no longer the correct API. Try instead `QuerySingle<int>`, or `ExecuteScalar`.

The return code from `Execute` means something very different, and is often not set at all.

**Comment by LeoRis** [comment]
You are a GOD ! Thank you very much ! I deff owe you a beer ! 🥇 💯
