### ISSUE TITLE
TableValuedParameter should be IDisposable

### ISSUE THREAD

**Issue by AleyCZ** [DapperLib/Dapper#1750]
We are using FxCop to analyze source code and it marked our usage of Dapper's TableValuedParameter as unsafe because it uses DataTable and DataTable is IDisposable. We use SqlMapper.AsTableValuedParameter, which sends our DataTable to the constructor of TableValuedParameter. And I can see the TableValuedParameter constructor stores the given DataTable in its object, but I can't see any place where Dispose is called. I think this is an issue, I think each class storing DataTable in itself should be IDisposable. (Or maybe even better would be to convert all data you need from DataTable to some clean local storage and do not keep the DataTable object at all.)

**Comment by mgravell** [comment]
FxCop sometimes gives irrelevant advice.

Data table is disposable via the inheritance model; it doesn't really have any related resources to clean up. The Dispose() method of DataTable is not overridden, which leaves just the base implementation. Now, the base implementation does two things:

1. Checks for "site" (in the component-model sense), and disconnect it: our DataTable will not have a "site"
2. Suppresses the finalizer flag; note that DataTable knows it doesn't need finalizing, so *does this in the constructor*

So: there are two things that dispose could theoretically do here, both specific to the base-type (not the DataTable itself), and ***neither of those things apply to this DataTable scenario***.

Honestly, it is incredibly rare to see anyone attempt to dispose a DataTable, and I would consider this a "false positive". In other news: `Task` is disposable too, and yet nobody ever disposes them.

I do not propose to change Dapper in any way in relation to this, although as always I'm open to discussion - my point is: it would be necessary to discuss an actual concrete problem scenario.

**Comment by mgravell** [comment]
Second thought: if we consider that the data table is being passed in from external caller: *we still don't own the lifetime*. There is nothing I hereby to say that the user is done with the table just because they used it with dapper. As such, I think it would be *semantically incorrect* to dispose it even if we wanted to: ***we don't own the life cycle***.

If the caller urgently wants to dispose all their tables, they still can. They don't need dapper to do anything for that.

**Comment by AleyCZ** [comment]
Based on the fact that the existence of Dispose in DataTable is just a side effect and it does nothing, I would agree on false positive.

The only real issue is that DataTable class is confusing by design and confusing software is not good. It will confuse other people in the future the same way as it confused FxCop and me. I don't think it is a problem of FxCop, it does its work correctly. I think it's rather a strange design flaw in DataTable class.

**Comment by mgravell** [comment]
> I don't think it is a problem of FxCop, it does its work correctly. I think it's rather a strange design flaw in DataTable class.

It can be both. Since DataTable is a well known type, I would expect FxCop to have it in an allow-list.
