### ISSUE TITLE
希望对.net 4.5支持（Want：The lowest version supports NET 4.5）

### ISSUE THREAD

**Issue by ping9719** [DapperLib/Dapper#1763]
现在最低版本为4.6.1（The current minimum version is 4.6.1）
他们差别不是很大（They are not very different）

我们的用户使用win7系统非常多，所以我们需要对低版本net的一个支持（There are many users of Windows 7，So we need to support lower versions of NET）

辛苦作者，谢谢。（thank）

**Comment by mgravell** [comment]
Realistically, that's just not going to happen. It would take work for a very small numbers of consumers, and we wouldn't be able to validate it very well. I've covered the additional reasons and context in more depth here: https://blog.marcgravell.com/2020/01/net-core-net-5-exodus-of-net-framework.html

**Comment by ping9719** [comment]
博客已阅。（I read the blog.）

支持低版本的话时间成本和性能确实难以解决。（If lower versions are supported，Time cost and performance are really difficult to solve.）

如果是服务器端我肯定使用最新版本，但是是客户端我们开发者就需要考虑非常多的问题。（If it is B/S, I will use the latest version。But for C/S, We developers need to consider a lot of problems）

那我就使用1.50.2吧。其实也没有多大的问题，我也是执着想用最新的而已。（I use version 1.50.2 . Have nothing wrong with，ideologism new version..... ）  ┐(￣ー￣)┌

谢谢（thank）
