### ISSUE TITLE
Dapper Not recognizing parameters with oracle.

### ISSUE THREAD

**Issue by LeonardoDaLuz** [DapperLib/Dapper#1776]
![image](https://user-images.githubusercontent.com/80224694/165407289-75d83006-35ac-4c21-840b-9c668000fe3b.png)
![image](https://user-images.githubusercontent.com/80224694/165407330-f73ede67-bea9-4513-ba4d-cf8d2fef3e22.png)

The dapper abstraction hides everything making debugging difficult. Please support the visualization of the query generated with the parameter. These abstractions only make it difficult for the developer.

I beg! Too much abstraction is bad!

It works normally if the value is manually written inside the query

**Comment by LeonardoDaLuz** [comment]
Please create another way to escape the inputs. This way with '@" is very bad to debug.

**Comment by mgravell** [comment]
The short answer here is that Oracle uses `:foo`, not `@foo`, for parameters - so your query should contain `:UserName` and `:Password`.

> Please support the visualization of the query generated with the parameter. 

We literally *do not generate* any final/composed query (at least, not usually). What you type is what we send.

> Please create another way to escape the inputs. This way with '@" is very bad to debug.

We don't define the SQL used by your database - that's outside of our control, and is up to the individual RDBMS.

---

If you don't want to know the SQL syntax of your database, then you might prefer a tool like EF (via LINQ), which *would* generate the query for you. The idea here is that Dapper is usually a tool for people who want to write their own SQL.

As a side note: storing plain text passwords is usually a very bad idea.

**Comment by LeonardoDaLuz** [comment]
I'm very happy for the answer.

About plain text password, I know. I'm make it easy to isolate errors.

I thought it was the dapper that entered the parameters.

Ultimately. The oracle that is horrible. A simple query that runs smoothly in SQL Developer does not run here, and there is no readable clue about it. I'm going to drop this oracle, I don't recommend it to anyone. (i'm using hardcored query just to test).

![image](https://user-images.githubusercontent.com/80224694/165845474-ec82f8e4-203e-443e-8be8-647ff9bd83d8.png)

MariaDB and MySQL are much more productive.
