### ISSUE TITLE
Support for DbBatch

### ISSUE THREAD

**Issue by kmcclellan** [DapperLib/Dapper#1778]
Some providers don't support pipelining multiple concurrent requests on the same connection but do support sending multiple commands using the new [System.Data.Common.DbBatch](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbbatch). I have in mind `npgsql` (see [documentation](https://www.npgsql.org/doc/performance.html#batchingpipelining)).

It would be nice to utilize this for the Dapper overloads that accept `IEnumerable` command parameters (e.g. `Execute(...)` and `ExecuteAsync(...)`) to cut down the round trip time. As a bonus, expose some way in the API of grouping commands/parameters to be sent in the same batch. Something like `CommandDefinition` but with a collection of command text/parameter definitions perhaps?

**Comment by asherborntofly** [comment]
It is certainly possible to utilize the System.Data.Common.DbBatch feature of certain providers like Npgsql to cut down on round trip time when using Dapper's Execute and ExecuteAsync methods with multiple command parameters. This can be done by creating a DbBatch object and adding each CommandDefinition to it, and then executing the batch with a single round-trip to the database.
