### ISSUE TITLE
Npgsql 6 positional parameters support

### ISSUE THREAD

**Issue by marekott** [DapperLib/Dapper#1782]
Hi,
Npgsql 6 introduced support for positional parameters rather than named ones which is more efficient when using Postgres since it is expecting positional parameters (details here: https://www.roji.org/parameters-batching-and-sql-rewriting). Are there any plans for supporting it in Dapper?

**Comment by hrrrrustic** [comment]
> Will need to think about!
Any updates here?

**Comment by mgravell** [comment]
Moving to AOT
