### ISSUE TITLE
When use using statement

### ISSUE THREAD

**Issue by hukar** [DapperLib/Dapper#1788]
Hello,

I don't understand when to use `using statement` ?
Especially with a `repository` pattern ?
In your examples you never use `using` except with `QueryMultiple` and `ExecuteReader`.
What are the good practices for using `using statement`?
If I look at your code, every extension method seems to close the connection with `conn.Close()`.

Thanks for informing me

**Comment by mgravell** [comment]
The `using` statement just handles automatic dispose of resources that go out of scope. This is useful for things like connections, to ensure that the *underlying* connection gets returned to the pool when you are done with it, regardless of success or failure. To discuss anything more nuanced than that, an example of what you mean would help.

**Comment by hukar** [comment]
Thank you for your answer.
I don't understand the particular use in the documentation of `using` for these two cases:
```cs
using (var multi = connection.QueryMultiple(sql, new {id=selectedId}))
{
    // ...
    
using (var reader = connection.ExecuteReader("select * from Shapes"))
{
    // ...
```
Here the connection is already established (and certainly in a `using block`), I don't see what is disposed in these cases.

Thanks in advance.

**Comment by hukar** [comment]
I just realized (finally!), most of the `Dapper` extension methods implement calls to `Dispose` directly. So there is no reason to use an `using block`.

On the other hand, `QueryMultiple` and `ExecuteReader` are the only two methods returning objects implementing `IDisposable` :


```cs
private static GridReader QueryMultipleImpl(this IDbConnection cnn, ref CommandDefinition command)
{ 
    // ...
    
```

```cs
public partial class GridReader : IDisposable
{
    // ...
```

```cs
private static IDataReader ExecuteReaderImpl(...)
{
    // ...
```

```cs
public interface IDataReader : IDataRecord, IDisposable
{
     // ...
```


That's why an `using block` is necessary in these cases.

Thanks and congratulations for your library.
