### ISSUE TITLE
postgreSQL NpgsqlOperationInProgressException `NpgsqlOperationInProgressException`  

### ISSUE THREAD

**Issue by JungOkKim1** [DapperLib/Dapper#1833]
I am developing postgreSQL using dapper.
The application creates and processes a connection.
The following exception occurs.
```
Npgsql.NpgsqlOperationInProgressException
  HResult=0x80004005
  메시지=NpgsqlOperationInProgressException
```
![image](https://user-images.githubusercontent.com/45255092/193744388-d4e24eb8-47f1-41e2-ad5d-396e3847b0b6.png)

**Is it possible to use a shared Connecton in Thread?
Do I need to create a new connection for each thead?**

In the previous Oracle, it worked without problems.

The sample source is below.
[Dapper_Postgre_Thread.zip](https://github.com/DapperLib/Dapper/files/9703089/Dapper_Postgre_Thread.zip)

**Comment by mgravell** [comment]
ADO.NET objects are not intended for concurrent usage. If you are spawning N threads, you will need N connections - or at least some kind of synchronization primitive such as a semaphore, such that no connection is used simultaneously from 2or more threads/async-flows.

**Comment by JungOkKim1** [comment]
Thanks for the quick reply. 

@mgravell
