### ISSUE TITLE
Dapper with MySQL unable to catch any exceptions

### ISSUE THREAD

**Issue by luisrr1590** [DapperLib/Dapper#1843]
Hi I have a .net core 6 Web API and trying to use dapper to send and get data from a MYSQL database.

after adding Dapper and MySQL.Data nugets to the project I created the following class:

       public class DataAccess
       {
               private readonly IConfiguration _config;

               public DataAccess(IConfiguration config)
              {
                     _config = config;
              }

             public async Task<List<T>> LoadData<T, U>(string sql, U parameters)
             {
                    using (IDbConnection conn = new MySqlConnection(_config.GetConnectionString("DefaultConnection")))
                    {
                           var rows = await conn.QueryAsync<T>(sql, parameters);
                           return rows.ToList();
                    }
             }

             public async void SaveData<T>(string sql, T parameters)
             {
                     using (IDbConnection conn = new MySqlConnection(_config.GetConnectionString("DefaultConnection")))
                     {
                               await conn.ExecuteAsync(sql, parameters);
                     }
             }
      }

I then added this class to Program.cs to uses it as a Singleton 

              builder.Services.AddSingleton<DataAccess>();

and inject it into the controllers.

Here´s an example of an action in a controller:

       public IActionResult Post([FromBody] ModelSample value)
        {
            try
            {
                        _dataAccess.SaveData("<SQL QUERY>", new { <Parameters> });
                        return Ok();
            }
            catch (Exception ex)
            {
                       return BadRequest(ex.Message);
            }
        }

this apparently works fine untils there´s an exception coming from the database like a simple duplicate key.

However I´m not able to catch the exception in the try/catch block and the app is treating it like an unhandled exception from external code crashing the app.

Can someone explain what´s going on, I have seen a bunch of examples online where they are able to catch the exceptions using a try/catch block.

What am I doing wrong?

**Comment by mgravell** [comment]
Two words: "async void".

Make it "async Task", and await the completion.

**Comment by luisrr1590** [comment]
Hi mgravell,

Thanks a lot for the quick response.

You were totally right. 

I´ve been using async/await for the LoadData method but something missed the other one.

It´s working now.

Closing now
