### ISSUE TITLE
Feature [DapperJson] Attribute

### ISSUE THREAD

**Issue by mryan-hpg** [DapperLib/Dapper#1844]
Given that JSON strings are first class citizens in many modern databases, it would be nice, if there was an easy way to decorate a property using an attribute that would trigger JSON serialization/deserialization to/from database calls.

Note: this should handle enumerables as a JSON array, where objects will be the object structure.  This should probably use the default json serialization for .Net Core/5+ with a minimal/default configuration, that can possibly be extended or overridden.

```cs
class Foo {
  [DapperJson]
  IEnumerable<Bar> somePropertyList { get; set; }

  [DapperJson]
  Bar someProperty { get; set; }
}
```

Related to #688

**Comment by tracker1** [comment]
Forgot to add under my personal user, instead of work.
