### ISSUE TITLE
Using nvarchar for retaining unicode literals

### ISSUE THREAD

**Issue by greffgreff** [DapperLib/Dapper#1853]
Hello, how can one retain special charracters using `@param` nortation?

In SQL Server, to achieve this, you can simple use `N'<text>'` to achieve this:
```
INSERT INTO Table(Id, Text) VALUES(1, N'🎻 This is a guitar')
```

However, with Dapper using `N'<@attribute>'` does not substitue `@attribute` properly. The sql below inserts "@Text" instead of "🎻 This is a guitar":
```
var count = connection.Execute(
          @"INSERT INTO Table(Id, Text) VALUES(@Id, N'@Text')", 
          new { Id = 1, Text = '🎻 This is a guitar' });
```
While this works:
```
var count =  connection.Execute(@"INSERT INTO Table(Id, Text) VALUES(1, N'🎻 This is a guitar')");
```

How can I make use of SQL Server's `N'<text>'` to retain special characters with Dapper?

**Comment by mgravell** [comment]
Parameters. `N'@Text'` is the 5 unicode characters with values `@`, `T`, `e`, `x` and `t`; the simpler `@Text` (no quotes etc) is the value of the parameter named `Text`. Parameters are sent as nvarchar by defualt, so this should work fine:

``` c#
var count = connection.Execute(
          @"INSERT INTO Table(Id, Text) VALUES(@Id, @Text)", 
          new { Id = 1, Text = '🎻 This is a guitar' });
```

**Comment by greffgreff** [comment]
Sorry for the late reply. Made some changes and it works perfectly fine now.
