### ISSUE TITLE
Gotchas returning Span<T> 

### ISSUE THREAD

**Issue by SuperDaveOsbourne** [DapperLib/Dapper#1854]
Just starting to look at Span<T> for returning 100 to 250 rows of a datetime, string, double, double, double. double. Since I am just getting started and haven't used Span of T with Dapper, is there any issues I should know about? Maybe under the covers, the implicit conversion makes this a waste of time? 

Since I didn't see anything come up on the search I assume a gotcha or so simple that it doesn't matter.

**Comment by NickCraver** [comment]
Do you have an example? Ultimately, you can't return a Span from a method, that's explicitly not allowed - the benefits of Span mostly revolve around tight control of the lifetime and stack-only type, which prohibits returning since any caller is further _down_ the stack, and not up it.

**Comment by SuperDaveOsbourne** [comment]
Well, certainly the algorithm that I am using is about 10 times faster on the data with spans so I will just give it a try and see if there is any speed pickup using spans throughout the data chain without the allocations.
