### ISSUE TITLE
[Question] Release of unsafe resources

### ISSUE THREAD

**Issue by RyoKakomi** [DapperLib/Dapper#1858]
Why doesn't the QueryAsync method use DbDataReader.Dispose() at line 450?
i'm thinking it could cause a NpsqlOperationInProgressException.

`reader = null; // to prevent it being disposed before the caller gets to see it`

Information.
Dapper : 2.0.123
Npgsql : 6.0.2
PostgreSQL : PostgreSQL 12.7 (Linux)

**Comment by mgravell** [comment]
The entire point of that method is to return a wrapper around an open
query. We haven't consumed the data yet; that return is the success case
where we've obtained a live reader, and now the consumer can read the data.
It will be disposed when they dispose the thing we give them. If we dispose
before exiting: the data-hose would be nuked *before* we give it to the
person who wants it.

The "finally" here is so that if we exit in any other way than success
(i.e. failure), it gets disposed.

**Comment by RyoKakomi** [comment]
@mgravell 

Thank you for your response.
As I read the code, I found that it is disposed. (on finally block)

I don't know the cause of the "NpsqlOperationInProgressException", but if I change QueryAsync() to Query().

**Comment by mgravell** [comment]
That *probably* means you have overlapping operations on the same connection; is there code we can see here? There are two different ways to overlap operations:

1. non-awaited / out-of-order-awaited async operations:

``` c#
var pending = whatever.SomethingAsync();
whatever.DoSomethingElse(); // boom! SomethingAsync hasn't finished yet
await pending; // it hasn't finished *until this has completed*
```

2. overlapping open (non-batched) queries:

``` c#
foreach (var row in conn.Query<Foo>(..., buffered: false))
{   // because of "buffered: false", this is an "open" query; it is an iterator over
    // a live data-reader - we have *not* read the data-reader to completion
    conn.DoSomethingElse(); // boom! the existing query hasn't finished yet
}
```

Do either of those apply?

**Comment by RyoKakomi** [comment]
@mgravell 

1. non-awaited / out-of-order-awaited async operations: 
-> awaited QueryAsync method.
`var list = await QueryAsync<Bar>("", {})`

3. overlapping open (non-batched) queries: 
i writed this code.
but, it's may be called recursively.
`var list = await QueryAsync<Bar>("", {})`


i think 2. applies.

**Comment by mgravell** [comment]
odd; I can't see anything inherently wrong there

**Comment by RyoKakomi** [comment]
@mgravell 
I write and run test code.
This issue was was reproduced.

An exception is raised when an asynchronous method is called from a synchronous method.


bad 
```C#
[FactPostgresql]
public void TestPostgresqlQueryAsyncMultiTask()
{
    using var conn = GetOpenNpgsqlConnection();
    IDbTransaction transaction = conn.BeginTransaction();
    for (int i = 0; i < 10; i++)
    { 
        PostgresqlQueryAsync(conn, transaction);
    }
    transaction.Rollback();
}

private async void PostgresqlQueryAsync(NpgsqlConnection conn, IDbTransaction  transaction)
{
    await conn.ExecuteAsync("create table tcat ( id serial not null, breed character varying(20) not null, name character varying (20) not null);", transaction);
    await conn.ExecuteAsync("insert into tcat(breed, name) values(:Breed, :Name) ", Cats, transaction);

    var r = await conn.QueryAsync<Cat>("select * from tcat where id=any(:catids)", new { catids = new[] { 1, 3, 5 } });
    Assert.Equal(3, r.Count());
    Assert.Equal(1, r.Count(c => c.Id == 1));
    Assert.Equal(1, r.Count(c => c.Id == 3));
    Assert.Equal(1, r.Count(c => c.Id == 5));
}
```

good
```C#
[FactPostgresql]
public void TestPostgresqlQueryAsyncMultiTask()
{
    using var conn = GetOpenNpgsqlConnection();
    IDbTransaction transaction = conn.BeginTransaction();
    for (int i = 0; i < 10; i++)
    {
        Task.Run(() =>
        {
            PostgresqlQueryAsync(conn, transaction);
        });

    }
    transaction.Rollback();
}
```

**Comment by mgravell** [comment]
If that fix is working, it is working by accident; the "good" version should be:

``` c#
 for (int i = 0; i < 10; i++)
{ 
    await PostgresqlQueryAsync(conn, transaction);
}
```

The `await` is important; without that, as Nick says, you're overlapping work on `conn` / `transaction`, and that *isn't expected* (by Npgsql - this isn't a Dapper thing, it is a fundamental consideration of ADO.NET connections).

**Comment by mgravell** [comment]
To lean back on my examples from my initial reply where I said:

``` c#
var pending = whatever.SomethingAsync();
whatever.DoSomethingElse(); // boom! SomethingAsync hasn't finished yet
await pending; // it hasn't finished *until this has completed*
```

What you have is basically:

``` c#
whatever.SomethingAsync(); // just ignore the async result completely; YOLO
whatever.DoSomethingElse(); // boom! SomethingAsync hasn't finished yet
```

**Comment by RyoKakomi** [comment]
@mgravell 
@NickCraver 

Thank you your response.
I realize how I using async/await by mistake.
(I Call DoSomethingElse() after SomethingAsync()...)

This issue will be closed.
