### ISSUE TITLE
[Question] Unable to pass @ as parameters

### ISSUE THREAD

**Issue by JustasKvederis** [DapperLib/Dapper#1859]
Good afternoon. I am using an old database DBISAM 4 for my project, and it seems like it won't accept @paramName only "?"  it will just return an error saying.... "Database was expecting **** but instead found @" Any workarounds ? Or should I just use "?" Any workarounds for this ?

**Comment by mgravell** [comment]
If your database uses just `?`, then Dapper allows "pseudo-positional parameters"; in the command you give to dapper, use `?paramName?` (note the leading and trailing `?`). Dapper will replace this with `?`, and will use the value from `paramName`, and the order from the query.

**Comment by JustasKvederis** [comment]
@mgravell Thank you very much this solved a bunch of my previous issues. One last inquiry is it possible to set table Name in such manner (Select * From ?tableName?) Since it doesn't seem to work with table name only with other parameters.

**Comment by NickCraver** [comment]
@JustasKvederis that's generally an RDBMS question, but the vast majority do not allow it (because they couldn't generate a query plan to re-use with other parameters if that part was dynamic).

**Comment by JustasKvederis** [comment]
@NickCraver Thanks, for your response, I guess that's not really possible. 

@mgravell any idea why this would not work:

`                string sql = $"Update Users SET Deleted = True Where Key = ?Key?";

                var result = await BaseRepository.DbConnection.ExecuteAsync(sql, new{Key});`

It does not give out an error just doesn't do anything, the key is correct

**Comment by mgravell** [comment]
No idea without investigating, and: I don't have access to DBISAM; initial guesses:

1. case sensitivity in the value of `Key`
2. the `True` keyword - is that a thing in DBISAM? most RDBMS would want `1` there
3. are you sure there isn't a `catch` block that is swallowing an exception, and it is trying really hard to tell you the problem?
4. does the same thing work when executed in whatever ad-hoc query tools exist for DBISAM?

**Comment by mgravell** [comment]
oh, and the other classic "nothing is happening!" causes: executing against the wrong database/server/table (which in some RDBMS can be as simple as having a `dbo.Users` table and a `SomeAccount.Users` table, when the app is logged in as `SomeAccount` - but you intended to update the data in `dbo.Users`)

**Comment by JustasKvederis** [comment]
@mgravell I do understand where you are coming from, but if I simply just change the previous line to:

`                string sql = $"Update Users SET Deleted = True Where Key = '{request.Key}'";`

it works as intended. Meaning that most of your guesses are sadly not the case here :( and no I am debugging my catch too and it's never hit :/ it just always return 0 as a result and make no changes in the database. 

Again if I change it to above code it works as intended :/ but I don't want to open this to sql injection.

**Comment by mgravell** [comment]
very interesting; I honestly don't know, without more input; my next guess would be "ANSI strings"; try, perhaps (as the arg):

    new { Key = new DbString { IsAnsi = true, Value = Key } }

which *should* configure a non-unicode string with the relevant value

**Comment by JustasKvederis** [comment]
@mgravell I tried your suggestion, but does not seem to help :/ It might just be the ancient database being weird. As you mentioned you need more input I am posting the entire method:

`        [HttpPost]
        [Route("Delete")]
        public async Task<Boolean> Delete(DeleteViewModel request)
        {
            try
            {
                BaseRepository.DbConnection.Open();
                //string Key = request.Key;
                string sql = $"Update Users SET Deleted = True Where Key = ?Key?";

                var result = await BaseRepository.DbConnection.ExecuteAsync(sql, new { Key = new DbString { IsAnsi = true, Value = request.Key } });

                BaseRepository.DbConnection.Close();
                if (result > 0)
                    return true;

                return false;
            }
            catch (Exception e)
            {
                BaseRepository.DbConnection.Close();
                return false;
                throw e;
            }
        }`

**Comment by JustasKvederis** [comment]
@mgravell  I thought this might be helfpull, but I tried to bypass Dapper and just use plain ODBC, and it seems to work :/

`        [HttpPost]
        [Route("Delete")]
        public async Task<Boolean> Delete(DeleteViewModel request)
        {
            try
            {
                BaseRepository.DbConnection.Open();
                //string Key = request.Key;

                string sql = $"Update Users SET Deleted = True Where Key = ?";

                OdbcCommand DbCommand = BaseRepository.DbConnection.CreateCommand();
                DbCommand.CommandText = sql;
                DbCommand.Parameters.Add("@Key", OdbcType.VarChar).Value = request.Key;

                var result = DbCommand.ExecuteNonQuery();

                DbCommand.Dispose();

                //var result = await BaseRepository.DbConnection.ExecuteAsync(sql, new { Key = new  { IsAnsi = true, Value = request.Key } });

                BaseRepository.DbConnection.Close();
                if (result > 0)
                    return true;

                return false;
            }
            catch (Exception e)
            {
                BaseRepository.DbConnection.Close();
                return false;
                throw e;
            }
        }`

This code does work

**Comment by mgravell** [comment]
without my having access to DBISAM, I can only shrug and make grunty sounds. I'm interested - I just lack the capacity to investigate. My *guess* would be something to do with the precise parameter configuration (we won't be using `OdbcType`, for example, but instead: `DbType`), but...

**Comment by JustasKvederis** [comment]
@mgravell Thank you for your time, if I ever figure it out I will reopen it and post an answer why is this happening :/ for now I am not sure what's going on but I have to move on for now. Thank you again.

**Comment by JustasKvederis** [comment]
@mgravell  I figured one thing out :/ That slightly reduced the places where the error could be happening:

the pseudo positional parameters do work. This might help people in the future.

`                var sql = "Update Users Set Active = ?Active?, FirstName = ?FirstName?, LastName = ?LastName?," +
                          " Company = ?Company?, Address1 = ?Address1?, Address2 = ?Address2?, Address3 = ?Address3?," +
                          " County = ?County?, Country = ?Country?, Email = ?Email?, Phone = ?Phone?," +
                          " UserName = ?Username?, UserPassword = ?UserPassword?," + " UserType = ?Type?," +
                          $" Modified = '{DateTime.Now.ToString(Constants.IsoStandard)}', Sync = '{DateTime.Now.AddSeconds(1).ToString(Constants.IsoStandard)}'" +
                          $"Where Key = '{request.Key}'";
`
This does work. It puts everything in place for the correct row:

`                var sql = "Update Users Set Active = ?Active?, FirstName = ?FirstName?, LastName = ?LastName?," +
                          " Company = ?Company?, Address1 = ?Address1?, Address2 = ?Address2?, Address3 = ?Address3?," +
                          " County = ?County?, Country = ?Country?, Email = ?Email?, Phone = ?Phone?," +
                          " UserName = ?Username?, UserPassword = ?UserPassword?," + " UserType = ?Type?," +
                          $" Modified = '{DateTime.Now.ToString(Constants.IsoStandard)}', Sync = '{DateTime.Now.AddSeconds(1).ToString(Constants.IsoStandard)}'" +
                          $"Where Key = ?Key?";`

And this does not work. There must be some error somewhere when comparing the Key in a parameter maybe there is some kind of transformation or a cut off. That's why it works and does not error out, but never finds the required parameter.... Now just to find out how to pass the parameter so it works.

**Comment by JustasKvederis** [comment]
@mgravell setting the size made it work 

`                request.Keyo = new DbString {Value = request.Key, IsFixedLength = true, Length = 32};`

Finally made it work.... But I need a better work around... The line above makes it work. When digging into the Dapper code it set's the length to 4000 somewhere, not sure why.
