### ISSUE TITLE
Dapper installation failed - terminated with exit code 1

### ISSUE THREAD

**Issue by selvakumar-arc** [DapperLib/Dapper#1870]
Hi,
I am using VS Code and sdk 7.  Trying to install dapper from VS Code Nuget gallery but it is failing and same for cli command as well.

Error message -
The terminal process "C:\Program Files\PowerShell\7\pwsh.exe -Command dotnet add s:/Work/Code/dapper/dapper.csproj package Dapper -v 2.0.123 -s https://api.nuget.org/v3/index.json" terminated with exit code: 1.

Please help me on fixing this issue.

Thank you
Selvakumar R

**Comment by mgravell** [comment]
So my initial thought here: is this vscode, nuget, or Dapper? Cna you add
Dapper manually to see if it works? I.e. in an `<ItemGroup>` in the csproj,
add `<PackageReference Include="Dapper" Version="2.0.123" />`

And: does it restore, build, run, etc?

**Comment by selvakumar-arc** [comment]
I am still getting error if I try to add package reference manually.
  Determining projects to restore...
s:\Work\Code\TechStack\dapper\dapper.csproj : error NU1108: Cycle detected. 
s:\Work\Code\TechStack\dapper\dapper.csproj : error NU1108:   dapper -> Dapper (>= 2.0.123).
  Failed to restore s:\Work\Code\TechStack\dapper\dapper.csproj (in 162 ms).
Done: 1.

Thank you
Selvakumar R

**Comment by mgravell** [comment]
K. The thing you're trying to install dapper into; is that by any chance: dapper? Meaning: have you pulled the code from GitHub and now you're trying to install itself into itself?

**Comment by selvakumar-arc** [comment]
I just give a project name as dapper.  Not downloaded dapper project code from github.  Whether .net 7 supports dapper 2.0.123? or is it looking for higher version?

**Comment by NickCraver** [comment]
Overall, you've created an ambiguous project name as far as tooling is concerned - I'd rename your project :)

**Comment by mgravell** [comment]
Well now I want to call my next project `ConsoleApplication1`, just to mess with folks
