### ISSUE TITLE
Postgresql UUID field not being mapped to Guid during Multimap

### ISSUE THREAD

**Issue by josdeweger** [DapperLib/Dapper#1875]
Postgres: Azure Database for PostgreSQL flexible server, PostgreSQL version 14.5
Dapper: 2.0.123
Dapper.Extensions.PostgreSQL: 4.2.1
Npgsql: 7.0.1

we have the following classes:

```
public class Parent
{
    public string Identifier { get; set; } //postgres datatype: character varying
    public IdentifierType IdentifierType { get; set; } //postgres datatype: character varying
    public List<Child> Children { get; set; }
}

public class Child
{
    public Guid Id { get; set; } //postgres datatype: uuid
    public string ParentIdentifier { get; set; } //postgres datatype: character varying
}
```

When querying a child record all the fields are properly filled, including the Child Id, which is a Guid:
`var child = await _db.QueryAsync<Child>(new CommandDefinition("SELECT * FROM children LIMIT 1"));`

But when we do a multimap with a join, child.Id is set to an empty Guid:

```
var command = @"SELECT 
                parent.identifier, 
                parent.identifier_type, 
                child.parent_identifier,
                child.id
            FROM parent 
            LEFT JOIN child ON parent.identifier = child.parent_identifier
            WHERE parent.identifier = @identifier
            AND parent.identifier_type = @identifierType";

var lookup = new Dictionary<string, Parent>();
        
await _dapper.QueryAsync<Parent, Child, Parent>(
    sql: command,
    param: @params,
    map:(parent, child) =>
    {
        if (!lookup.TryGetValue(parent.Identifier, out Parent? found))
        {
            lookup.Add(parent.Identifier, found = parent);
        }
        
        found.Children.Add(child);
        
        return found;
    }, splitOn: "identifier");

return lookup.Values;
```

We noticed that when we add a * to the select statement, the child.Id field gets filled.

What are we missing here?

**Comment by NickCraver** [comment]
The default `splitOn` is "Id", so there are 2 quick fixes here: either place `child.id` as the first child field in the query and it'll work without `splitOn` specified, or adjust `splitOn` to be correct like this: `splitOn: "identifier,parent_identifier"`. It should specify all fields to split on, where right now it's only specifying a single identifier and that's only on the parent, so it's all treated as a single parent object and never begins looking to populate another :)

**Comment by josdeweger** [comment]
Hi @NickCraver, thanks for the help, that did the trick!
