### ISSUE TITLE
Dapper QueryMultiple doesn't return all the selected tables

### ISSUE THREAD

**Issue by query-wow** [DapperLib/Dapper#1876]
Hello, I wanted to ask why I can't get the values from a stored procedure when there's a concatenated query.

I'm migrating from a normal outdated connector to dapper but when I have a stored procedure with `EXEC (Query)` and a normal select statement, dapper grid only contains the data of the normal query and not the dataset inside the exec statement.

**Comment by mgravell** [comment]
Can we have a concrete example so we don't talk past eachother?

**Comment by query-wow** [comment]
Hello, thank you for the response, i wrote this on my phone because i was already out of the office.
The Stored Proc consists of doing some temporary table updates and in the end select them into two different result sets.

![image](https://user-images.githubusercontent.com/660776/212857449-84f6046c-0996-49ea-9604-46ee917fa9a6.png)

![image](https://user-images.githubusercontent.com/660776/212857589-4f98a759-7b88-48a2-81cc-85cc0c8d0969.png)

But when i execute this in Dapper all i get is the Total competitors. 
This only happens with this exact stored proc, i don't have others that   


I tried with a runnable example but it all works normally 

```csharp
   using (SqlConnection sql = new SqlConnection(_configuration.GetConnectionString("SqlConn")))
            {
                string query = @"SELECT ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS number
                                FROM master..spt_values
                                WHERE type = 'P'
                                AND number BETWEEN 1 AND 10
                                EXEC('SELECT ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS number
                                FROM master..spt_values
                                WHERE type = ''P''
                                AND number BETWEEN 1 AND 10')";
                var data = await sql.QueryMultipleAsync(query,  commandType: System.Data.CommandType.Text);

                var stats = await data.ReadAsync<int>();
                var count = await data.ReadAsync<int>()
            }
```

**Comment by query-wow** [comment]
I found out the issue, i was sending bad params to the SP! Thank you for your time! Everything works!
