### ISSUE TITLE
Exception in CDK: System.TypeInitializationException: The type initializer for 'Dapper.SqlMapper' threw an exception.

### ISSUE THREAD

**Issue by zeng-github01** [DapperLib/Dapper#1881]
System.TypeInitializationException: The type initializer for 'Dapper.SqlMapper' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
  at Dapper.SqlMapper..cctor () [0x00645] in <51f57a25b85f44c4988211f1f77af0bc>:0

**Comment by mgravell** [comment]
What framework are you targeting, and what library version are you using?

**Comment by zeng-github01** [comment]
> What framework are you targeting, and what library version are you using?

Target Framework：.Net framework 4.8.1 , Dapper Version：Nuget Latest

**Comment by zeng-github01** [comment]
> What framework are you targeting, and what library version are you using?

The problem now is that Dapper was normal at first.  Then there was a problem, this problem appeared after using the query.  But the corresponding code block is very concise.  I can't see why
