### ISSUE TITLE
Does Dapper have a simplified Chinese language pack similar to. net core 3.1? I think the annotated English can be directly translated into Chinese for easy reading and understanding. Please tell me as soon as possible that I need to determine whether the next work content needs to be translated manually by using the translation software.

### ISSUE THREAD

**Issue by gallop1** [DapperLib/Dapper#1888]
Does Dapper have a simplified Chinese language pack similar to. net core 3.1? I think the annotated English can be directly translated into Chinese for easy reading and understanding. Please tell me as soon as possible that I need to determine whether the next work content needs to be translated manually by using the translation software.
（备注：请问一下Dapper有没有类似于.net core3.1的简体中文语言包？我想注释的英语可以直接翻译成中文，便于阅读理解。请尽快告诉我一下，我需要确定下一步的工作内容是否需要自己手动使用翻译软件翻译对应注释内容。）

**Comment by mgravell** [comment]
Currently, no it does not. I'm open to input, but it would need community input to provide content. What sort of elements are you looking for here? i.e. what would this provide / change?

**Comment by gallop1** [comment]
![Uploading image.png…]() @mgravell  like this ,I want you can directly The translation method is noted in Simplified Chinese. I hope this is useful.Because just like you are a foreigner, it will be much slower for you to check in other people's languages. In addition, China is a big country, and I think it is necessary to support it.
（备注：因为就好比你是外国人，你用其他人语言来查看会慢很多，另外中国是个大国，我也觉得很有必要支持一下。）

**Comment by mgravell** [comment]
"and I think it is necessary to support it"

I think it is *desirable* to support it, sure. But: this is an unfunded project, so that effort needs to come from somewhere, and realistically: I lack the ability to provide this content (meaning: I lack the language skills). If you wish to volunteer to provide it, again: I'm open to conversation.

There's also the logistics problem if figuring out what we need to do at the technical level - unlike the provision of content, this part only needs doing once, though.

**Comment by gallop1** [comment]
You can use this Chinese Baidu translation software, so that when you write English, you can translate it into the corresponding Chinese, which is basically accurate, and rarely not correct. this website is in https://fanyi.baidu.com/appdownload/download.html?tab=desktop&fr=pcproduct . you can dowload it if you want to do it.
(备注：你可以使用这个中国的百度翻译软件，以便你在写英文的时候，对照翻译成对应的中文，基本上都是准确的，很少是对不上的。) @mgravell

**Comment by mgravell** [comment]
There's two separate things here:

- providing the content (automated is usually not great for technical purposes)
- hooking all the machinery needed to make it work

Even if we solved the first problem, I'm not sure there are great options for the second (for example, see https://github.com/dotnet/roslyn/issues/3371). I can't provide infinite resource to implement documentation, so *right now* I just don't think there are practical ways of making this work. If I'm wrong, please feel free to propose genuine yet manageable mechanisms for this to work. It isn't as simple as "here's the text" - it needs to actually integrate with all the build and deployment steps.

**Comment by gallop1** [comment]
https://dotnet.microsoft.com/zh-cn/download/intellisense
"I think you can refer to these Chinese translations of Microsoft. Net Core. Although I don't know how it is implemented, there are probably solutions available online.". I have read similar articles before, hoping to be helpful to you.Because I'm reading Chinese documents on Baidu, it's useless for me to send you links."
(备注：我觉得你可以参考微软.net core这些中文翻译，虽然我不知道它是怎么实现的，但估计网上有解决方案。我曾经看过类似的文章，希望对你有所帮助。因为我看的是百度上中文文档，所以我发给你链接也是没用的。) @mgravell
