### ISSUE TITLE
Potential MemoryLeak, it seems this this line may cause memory leak

### ISSUE THREAD

**Issue by wojtekelpl** [DapperLib/Dapper#1902]
https://github.com/DapperLib/Dapper/blob/b272cc664d933b4b65703d26a79272d549576dff/Dapper/DynamicParameters.cs#L17

**Comment by wojtekelpl** [comment]
It may cause memory leak when we use wrong paramaters

**Comment by mgravell** [comment]
I *presume* this is more related to non-parameterized queries causing slow saturation. IMO the solution in any event is probably "use Dapper.AOT when it ships" - because of how this is implemented, there is no such dictionary growth anywhere

**Comment by mgravell** [comment]
Closing because without example there isn't anything to investigate

**Comment by wojtekelpl** [comment]
> I _presume_ this is more related to non-parameterized queries causing slow saturation. IMO the solution in any event is probably "use Dapper.AOT when it ships" - because of how this is implemented, there is no such dictionary growth anywhere

yes exactly

**Comment by mgravell** [comment]
Then in the first: "use parameterized queries"

In the second: "Dapper.AOT should ship a public build in the next few days"
