### ISSUE TITLE
mySQL: column of CHAR(36) is deserialized as GUID

### ISSUE THREAD

**Issue by SwissMaWi** [DapperLib/Dapper#1904]
For some miraculous reason (I am sure the programmer thought he is a genius) the SqlMapper wants to deserialize database columns with type CHAR(36) as GUID. That is a horrible mistake now making it impossible to use such columns normally. This behavior should be removed.

**Comment by bgrainger** [comment]
For MySql.Data, you can set `OldGuids=True` in the connection string, although this will cause all `BINARY(16)` columns to be read as a `Guid` instead.

For [MySqlConnector](https://www.nuget.org/packages/MySqlConnector/), you can set `GUID Format=None` or use one of the other [`GuidFormat` values](https://mysqlconnector.net/connection-options/#GuidFormat).

**Comment by mgravell** [comment]
I don't think this is Dapper doing this; the tips by @bgrainger above suggest that it is the MySql provider itself.

**Comment by SwissMaWi** [comment]
Thanks for this. Unbelievable that a DAC converts types without knowing what they actually are.
