### ISSUE TITLE
Missing QueryUnbufferedAsync for IDBConnection

### ISSUE THREAD

**Issue by DevEngineReq** [DapperLib/Dapper#1921]
Extension Method QueryUnbufferedAsync only implemented \ available (public) for DbConnction.
The method for IDBConnection is private.

Is there a reason for this strategy?

**Comment by NickCraver** [comment]
Overall, `IDBConnection` doesn't have the async methods, they were added later to `DbConnection`...so things only work on a `DbConnection`. Looking back, we should have only ever offered async extensions on `DbConnection` but we can't unship what's out there without breaking more people.
