### ISSUE TITLE
Missing QueryUnbufferedAsync without generic parameter (dynamic)

### ISSUE THREAD

**Issue by DevEngineReq** [DapperLib/Dapper#1922]
Is it possible to implement QueryUnbufferedAsync without a generic parameter. Return a dynamic list like QueryAsync

**Comment by mgravell** [comment]
It is possible, but with hindsight, is it *necessary*? `QueryUnbufferedAsync<dynamic>` (or `QueryUnbufferedAsync<object>`, if you want to defer the "everything is `dynamic`" part): works identically

Thoughts?

**Comment by DevEngineReq** [comment]
Sure, it is not necessary from a technical point of view, but it would be the same for handling like QueryAsync...
If you do not define a generic parameter it will always be a dynamic list.

May be someone does not know that he can use dynamic as generic parameter.

**Comment by mgravell** [comment]
Fixing in #1925
