### ISSUE TITLE
Query against an existing SqlCommand

### ISSUE THREAD

**Issue by jnm2** [DapperLib/Dapper#1943]
Sometimes I use a helper utility to build dynamic SQL which also dynamically inserts SQL parameters, for anything Dapper can't scale (more complex than `in (@1, @2, @3)`). Even though I want to create my own SqlCommand instance, I still want to take advantage of all the benefits of Dapper's mapping of the query results via `.Query<T>`. Can I have the best of both worlds?

Willing to implement all the `QueryXyz` extension methods if this is acceptable. It would replace the `string sql` and `object param` parameters, but not necessarily any of the other parameters like the connection, the transaction, command timeout, etc. You could take an opinionated stance that these things should be first set on the DbCommand before calling `.QueryXyz`, instead of being parameters passed to `.QueryXyz`, and then I would ask if it makes sense to put the extension methods on `DbCommand` instead of `DbConnection`.

**Comment by mgravell** [comment]
Maybe `GetTypeDeserializer` is the API you're looking for?

**Comment by jnm2** [comment]
It appears so, but I'm also looking for not having to declare all the variants of Query/First/OrDefault/Single/OrDefault/Async. Could I contribute extension methods like this to Dapper?

```cs
public static async Task<IEnumerable<T>> QueryAsync<T>(this DbCommand command, CancellationToken cancellationToken)
{
    await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);

    var deserialize = SqlMapper.GetTypeDeserializer(
        typeof(T),
        reader,
        startBound: 0,
        length: reader.FieldCount,
        returnNullIfFirstMissing: false);

    var results = new List<T>();

    while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        results.Add((T)deserialize(reader));

    return results;
}
```
