### ISSUE TITLE
C# Dapper Transaction Scope is auto committed for DB2 Provider

### ISSUE THREAD

**Issue by ras90it** [DapperLib/Dapper#1955]
`using (TransactionScope scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
{
    try
    {
        using (IDbConnection sqlConnection = GetDbconnection("SQL_CONNECTION_STRING"))
        {
            using (IDbConnection db2Connection = GetDbconnection("DB2_CONNECTION_STRING"))
            {
                sqlConnection.Open();
                db2Connection.Open();

				string db2Query1 = "";  // INSERT QUERY
				result = await db2Connection.QueryFirstOrDefaultAsync<bool>(db2Query1, new DynamicParameters(), commandType: CommandType.Text);
				
				string db2Query2 = "";  // INSERT QUERY
				result = await db2Connection.QueryFirstOrDefaultAsync<bool>(db2Query2, new DynamicParameters(), commandType: CommandType.Text);

				string procName = "SP_NAME";
                DynamicParameters dynamicParams = new DynamicParameters();
				dynamicParams.Add("Parameter1", "VALUE1", DbType.String);
                GridReader sqlResult = await sqlConnection.QueryMultipleAsync(procName, dynamicParams, commandType: CommandType.StoredProcedure, commandTimeout: 30);
                resultSet = await sqlResult.ReadAsync<T>();
                int sqlExecResult = await sqlConnection.ExecuteAsync(procName, dynamicParams, commandTimeout: 30, commandType: CommandType.StoredProcedure);

                scope.Complete();  // COMPLETE THE TRANSACTION
                IsSuccess = true;
            }
        }
    }
    catch (Exception ex)
    {
        errorMessage = ex.Message;
        throw;
    }
}
`

If db2Query1 is inserted successfully and db2Query2 is getting an error then db2Query1 already inserted is not rollback.

Even after inserting db2Query1 (before db2Query2 was not inserted) I can see the data of db2Query1 in DB is committed. 

**In DB2 it is auto-commited before calling scope.complete(). whereas in SQL Server it waits until calling scope.complete()**

**Comment by mgravell** [comment]
Dapper literally does nothing with TransactionScope - not does it need to. Does this work in raw ADO.NET? Does DB2 even support ambient transactions / TransactionScope? My suspicion is that it doesn't, and therefore from DB2's perspective, there was no transaction.

**Comment by mgravell** [comment]
I'm going to assume comment is correct. If you have more context: please add it and reopen.
