### ISSUE TITLE
Dapper Send Wrong SP String to Database

### ISSUE THREAD

**Issue by aliajboy** [DapperLib/Dapper#1956]
Hi, 
I use dapper to exec my SP. here is the problem:

using (var connection = new SqlConnection(connectionString))
{
    office = await connection.QueryFirstOrDefaultAsync<Office>("SELECT * FROM Office");

    string GetMemberQuery = @"DECLARE " +
        "@return_value int, " +
        "@IDMember int, " +
        "@SNCard float, " +
        "@Credit float, " +
        "@Group_Code int, " +
        "@GroupDeviceUse1 int, " +
        "@GroupDeviceUse2 int, " +
        "@GroupDeviceUse3 int, " +
        "@GroupDeviceUse4 int, " +
        "@GroupDeviceUse5 int, " +
        "@GroupDeviceUse6 int, " +
        "@GroupDeviceUse7 int, " +
        "@GroupDeviceUse8 int, " +
        "@GroupDeviceUse9 int, " +
        "@GroupDeviceUse10 int, " +
        "@GroupDeviceUse11 int, " +
        "@GroupDeviceUse12 int, " +
        "@GroupDeviceUse13 int, " +
        "@GroupDeviceUse14 int, " +
        "@GroupDeviceUse15 int, " +
        "@GroupDeviceUse16 int, " +
        "@gomshodeh bit, " +
        "@Expired bit, " +
        "@DateEt varchar(10), " +
        "@Day1Use bit, " +
        "@Day2Use bit, " +
        "@Day3Use bit, " +
        "@Day4Use bit, " +
        "@Day5Use bit, " +
        "@Day6Use bit, " +
        "@Day7Use bit, " +
        "@TimeStartUse int, " +
        "@TimeEndUse int " +
        "EXEC " +
        "@return_value = [dbo].[GetMember] " +
        $"@CurrDate = N'{DateTime.Now.MiladiToPersian().Replace("/", "")}', " +
        $"@Card_ID = {cardId}, " +
        "@IDMember = @IDMember OUTPUT, " +
        "@SNCard = @SNCard OUTPUT, " +
        "@Credit = @Credit OUTPUT, " +
        "@Group_Code = @Group_Code OUTPUT, " +
        "@GroupDeviceUse1 = @GroupDeviceUse1 OUTPUT, " +
        "@GroupDeviceUse2 = @GroupDeviceUse2 OUTPUT, " +
        "@GroupDeviceUse3 = @GroupDeviceUse3 OUTPUT, " +
        "@GroupDeviceUse4 = @GroupDeviceUse4 OUTPUT, " +
        "@GroupDeviceUse5 = @GroupDeviceUse5 OUTPUT, " +
        "@GroupDeviceUse6 = @GroupDeviceUse6 OUTPUT, " +
        "@GroupDeviceUse7 = @GroupDeviceUse7 OUTPUT, " +
        "@GroupDeviceUse8 = @GroupDeviceUse8 OUTPUT, " +
        "@GroupDeviceUse9 = @GroupDeviceUse9 OUTPUT, " +
        "@GroupDeviceUse10 = @GroupDeviceUse10 OUTPUT, " +
        "@GroupDeviceUse11 = @GroupDeviceUse11 OUTPUT, " +
        "@GroupDeviceUse12 = @GroupDeviceUse12 OUTPUT, " +
        "@GroupDeviceUse13 = @GroupDeviceUse13 OUTPUT, " +
        "@GroupDeviceUse14 = @GroupDeviceUse14 OUTPUT, " +
        "@GroupDeviceUse15 = @GroupDeviceUse15 OUTPUT, " +
        "@GroupDeviceUse16 = @GroupDeviceUse16 OUTPUT, " +
        "@gomshodeh = @gomshodeh OUTPUT, " +
        "@Expired = @Expired OUTPUT, " +
        "@DateEt = @DateEt OUTPUT, " +
        "@Day1Use = @Day1Use OUTPUT, " +
        "@Day2Use = @Day2Use OUTPUT, " +
        "@Day3Use = @Day3Use OUTPUT, " +
        "@Day4Use = @Day4Use OUTPUT, " +
        "@Day5Use = @Day5Use OUTPUT, " +
        "@Day6Use = @Day6Use OUTPUT, " +
        "@Day7Use = @Day7Use OUTPUT, " +
        "@TimeStartUse = @TimeStartUse OUTPUT, " +
        "@TimeEndUse = @TimeEndUse OUTPUT " +
        "SELECT " +
        "@IDMember as N'@IDMember', " +
        "@SNCard as N'@SNCard', " +
        "@Credit as N'@Credit', " +
        "@Group_Code as N'@Group_Code', " +
        "@GroupDeviceUse1 as N'@GroupDeviceUse1', " +
        "@GroupDeviceUse2 as N'@GroupDeviceUse2', " +
        "@GroupDeviceUse3 as N'@GroupDeviceUse3', " +
        "@GroupDeviceUse4 as N'@GroupDeviceUse4', " +
        "@GroupDeviceUse5 as N'@GroupDeviceUse5', " +
        "@GroupDeviceUse6 as N'@GroupDeviceUse6', " +
        "@GroupDeviceUse7 as N'@GroupDeviceUse7', " +
        "@GroupDeviceUse8 as N'@GroupDeviceUse8', " +
        "@GroupDeviceUse9 as N'@GroupDeviceUse9', " +
        "@GroupDeviceUse10 as N'@GroupDeviceUse10', " +
        "@GroupDeviceUse11 as N'@GroupDeviceUse11', " +
        "@GroupDeviceUse12 as N'@GroupDeviceUse12', " +
        "@GroupDeviceUse13 as N'@GroupDeviceUse13', " +
        "@GroupDeviceUse14 as N'@GroupDeviceUse14', " +
        "@GroupDeviceUse15 as N'@GroupDeviceUse15', " +
        "@GroupDeviceUse16 as N'@GroupDeviceUse16', " +
        "@gomshodeh as N'@gomshodeh', " +
        "@Expired as N'@Expired', " +
        "@DateEt as N'@DateEt', " +
        "@Day1Use as N'@Day1Use', " +
        "@Day2Use as N'@Day2Use', " +
        "@Day3Use as N'@Day3Use', " +
        "@Day4Use as N'@Day4Use', " +
        "@Day5Use as N'@Day5Use', " +
        "@Day6Use as N'@Day6Use', " +
        "@Day7Use as N'@Day7Use', " +
        "@TimeStartUse as N'@TimeStartUse', " +
        "@TimeEndUse as N'@TimeEndUse' " +
        "SELECT 'Return Value' = @return_value";

    getmmbr = await connection.QueryAsync<GetMember_Result>(GetMemberQuery);
}

but in the Sql Server Profiler,  "@GroupDeviceUse5 as N'@GroupDeviceUse5', " becomes "@GroupDeviceUse5 asN'@GroupDeviceUse5', "

I checked on debugging and the string is ok and can run on ssms, but after dapper send it, It wont run and give error. 
can anybody help?
sorry for my english

**Comment by mgravell** [comment]
Ok, can we clarify a few things? Are you saying that a space got removed? Is that the difference we're talking about? With very few exceptions, Dapper doesn't usually edit the command string at all, so: this seems unlikely. Is there a reproducible example we can run, i.e. code I can *actually run* (even if it includes an empty CREATE TABLE or whatever).

Note, when writing SQL in C#, there are two better string options that make things *much easier to read*: verbatim string literals:

``` c#
conn.Execute(@"a long string
with multiple lines
goes here");
```

and more recently (needs up-to-date compiler):

``` c#
conn Execute("""
    a long string
    with multiple lines
    goes here
    """);
```

(the latter has much better indentation and quoting behaviour - the left column position is defined by the closing quotes)

It would probably be much easier to see what is going on if you wrote your SQL using one of those options, so we know we aren't overlooking a problem in the line endings.

**Comment by mgravell** [comment]
If the problem is whitespace, I also wonder if the test in your file might have a non-ASCII unicode whitespace character in it - i.e. maybe what looks like a space there *isn't a space character*, but something else. Try removing that space and re-adding it - or enable whitespace character visibility in your text editor. Worst case, check the actual bytes to see if this is truly a space.

**Comment by mgravell** [comment]
Note: this example also shows very bad practice re parameters; Dapper is
*designed* to make correct parameterization easy - using things like
***@***.***_ID = {cardId}, ` undoes all of that (and it causes allocations, lack
of query plan reuse, etc. I wonder if what we should really look at here is
getting this query working using direct SP mode, i.e.
CommandType.StoredProcedure (see the optional commandType parameter)

**Comment by aliajboy** [comment]
Hi, Thanks everybody, It was my problem. My Model Names and Select Query at the end didn't have same names! the query has @ before them and the class doesn't. but it should give some sort of exception! 
I investigate and found that SQL will run that OK! and Dapper Do what it should do and bring back the answer and wants to put it in my model, but Couldn't because of my names.
so basically, Dapper is perfectly fine.
Sorry If I take your time

**Comment by mgravell** [comment]
and please please please use parameters
