### ISSUE TITLE
v2.1.1 introduces breaking changes

### ISSUE THREAD

**Issue by ilya-scale** [DapperLib/Dapper#1959]
This code does not compile anymore (if one has warnings as errors):

```csharp
public class DateTimeHandler : SqlMapper.TypeHandler<DateTime>
{  
    public override DateTime Parse(object value)
    {
        return DateTime.SpecifyKind((DateTime) value, DateTimeKind.Utc);
    }
}
```

The reason is the new nullability.

It is probably fine, but just wanted to check if maybe doing 3.0.0 would fit better since it is breaking?

I have warnings as errors and floating version, so by just running nuget get I got the compilation error.

**Comment by mgravell** [comment]
Firstly, thanks for trying hidden builds and finding this :)

I assume this is now "object?" ? Let me revisit this API and see if there are any genuine scenarios where the value is null; if there aren't, we can possibly make that "object". Otherwise: well, it is right :) In the second case - I'm not sure this warrants a "major"; it is a code warning that is readily fixed or suppressed. I imagine more people will get hit by the "OrDefault" methods returning "?", but again: it is right :)

**Comment by mgravell** [comment]
@ilya-scale looks like we can tweak this 👍

**Comment by mgravell** [comment]
This should be fixed in release 2.1.4

**Comment by mgravell** [comment]
[2.1.4](https://github.com/DapperLib/Dapper/releases/tag/2.1.4) is [on nuget now](https://www.nuget.org/packages/Dapper/2.1.4) (it may not have been indexed yet)

**Comment by ilya-scale** [comment]
Thanks for taking a look at this @mgravell , with 2.1.4 I was able to revert my changes back to non-nullable.

There were some other places that I have found similar issues, e.g.

1. `public override void SetValue(IDbDataParameter parameter, T? value)` (in the same class) was just `T value` before
2. `public static void AddTypeHandler(Type type, ITypeHandler handler)` became non nullable

I am not sure about the first case (whether it should or should not be nullable). The second ones looks correct of course as there is no need to send null in there. It is just in my case caused an error during a compilation which is kind of an indication of a major version, but I see you point that it is probably too small of a change for a Major.

Additionally, I am not sure what do you mean by "hidden builds", my configuration is:

```
<PackageReference Include="Dapper" Version="2.*" />
```
So while I see that somehow these builds are not visible on nuget website, the dotnet commands find them for sure for floating version :)
