### ISSUE TITLE
2.1.4 Version

### ISSUE THREAD

**Issue by michal-ciechan** [DapperLib/Dapper#1962]
Is there issues with this version? Should this have been marked pre-release? 

I noticed it got de-listed. Should we avoid using this version, or is it relatively safe to use?

But Rider is still showing it as latest.

**Comment by mgravell** [comment]
No known issues, no. It is not "delisted" so much as "not yet listed". It should be safe to use, any problems: let me know like normal. Nothing nefarious about this one, just: because of the "NRT" annotations there is a higher-than-normal chance of build warnings. I'd love to hear your experiences.

**Comment by michal-ciechan** [comment]
If we fine any issues, we'll come back, or if there is anything that stands out. I'll take a look at whats new and keep an eye out.
