### ISSUE TITLE
When I create a new instance of SQLConnection, the connection is closed

### ISSUE THREAD

**Issue by AmirMahdyJebreily** [DapperLib/Dapper#1963]
When I create a new instance of SQLConnection, the connection is closed and in the debug window of Visual Studio, this exception message is placed instead of the value of "RetryLogicProvider" and the value of "System Invalid Operation Exception" is placed instead of the value of "ServerVersion"!

![https://i.stack.imgur.com/UZELo.png](https://i.stack.imgur.com/UZELo.png)

**Comment by mgravell** [comment]
Yes. That's normal. If it isn't currently actively connected to a server, it can't tell you the server version of the server it isn't connected to.

Dapper handles opening/closing connections as necessary, so the fact that you haven't opened the connection: doesn't matter.

None of this relates to Dapper. Going to close this out, but happy to discuss more if there's a Dapper-related question here.
