### ISSUE TITLE
Should `ITypeMap.GetConstructorParameter` be allowed to return null?

### ISSUE THREAD

**Issue by nyctef** [DapperLib/Dapper#1969]
We're currently using a custom type map like this:

```csharp
internal class RemoveSpacesFromColumnNames : SqlMapper.ITypeMap
{
    private readonly Type _type;

    public RemoveSpacesFromColumnNames(Type type)
    {
        _type = type;
    }

    public ConstructorInfo FindConstructor(string[] names, Type[] types) =>
        _type.GetConstructors().Single();

    public ConstructorInfo? FindExplicitConstructor() => null;

    public SqlMapper.IMemberMap? GetConstructorParameter(ConstructorInfo constructor, string columnName)
    {
        var nameWithoutSpaces = columnName.Replace(" ", "");
        var parameter = constructor.GetParameters().FirstOrDefault(x => x.Name == nameWithoutSpaces);
        return parameter == null ? null : new CustomParameterMap(columnName, parameter);
    }

    public SqlMapper.IMemberMap? GetMember(string columnName) => null;
}
```

where we'd added the nullable reference annotations ourselves. (Hopefully this code doesn't look too crazy :)

However when updating to dapper 2.1.4 this code now fails to compile since `GetConstructorParameter` is expected to return `SqlMapper.IMemberMap` instead of `SqlMapper.IMemberMap?`.

In `SqlMapper.GenerateDeserializerFromMap` it seems like the output of this method is checked for null in the same way that `GetMember` is, so I guess returning null is probably valid here?

**Comment by nyctef** [comment]
as a side note, while reviewing this code I realized we've implemented our own `CustomParameterMap` implementation of `IMemberMap`, which is just a bunch of boilerplate - it'd be handy if `SimpleMemberMap` was public so we didn't need to do that  (https://github.com/DapperLib/Dapper/issues/613?)

**Comment by mgravell** [comment]
yes, I think you're right re the NRT - fixing
