### ISSUE TITLE
Need a setting to disable unreliable OLEDB parameter check

### ISSUE THREAD

**Issue by StruanT** [DapperLib/Dapper#1971]
The smellsLikeOleDb regex on SqlMapper doesn't work correctly in all kinds of scenarios. If you are passing a model that has properties that you don't intend to parameterize and cannot be parameterized this results in a NotSupportedException

I think this would most easily solved by having a setting turn it off on this line (just make filterParams true and ignore this regex if a setting is enabled)
https://github.com/DapperLib/Dapper/blob/47ef1e7100b7ecdb68bcf97432b9674373a6f75c/Dapper/SqlMapper.cs#L2538

Some examples that break this "smell check".

- Question marks in SQL Comments 
`-- Why is the question mark in this comment treated as a parameter ?` 

- Question marks in strings. https://github.com/DapperLib/Dapper/issues/1914

- Using openquery execute LDAP Queries that start with `<LDAP://:>;`

- Postgres type casts https://github.com/DapperLib/Dapper/issues/1299

This would all be solved by having a way to turn it off (make filterParams true and ignore this regex)

I see no reason not to have the option to disable this footgun completely for anyone not using OLEDB at all. For that matter... why not default it to off and let anyone using OLEDB turn it on?

**Comment by mgravell** [comment]
I can't disagree with anything you've said. There are no scenarios when the pseudo-positional parameters (`?abc?`) wouldn't be preferable. Agree, we should:

- add a property to turn it off, but leave the default behaviour as-is for now
- add release notes advertising that this default will be changed in a future version, and that anyone using naked `?` parameters should manually set it
- release a "major" maybe start of 2024 with the default swapped, again with release notes highlighting it

**Comment by Giorgi** [comment]
Should the new setting live in `SqlMapper.Settings` ?

**Comment by mgravell** [comment]
Yes. I was planning to take a look when I get a moment, but I'd happily consider a PR if that's your plan.

**Comment by mgravell** [comment]
https://github.com/DapperLib/Dapper/releases/tag/2.1.11
