### ISSUE TITLE
Dapper 2.1.11 PR#1975 (auto-detect stored procedures as anything without whitespace) regression with non-breaking spaces

### ISSUE THREAD

**Issue by tlecomte** [DapperLib/Dapper#1986]
Dear Dapper maintainers

Dapper 2.1.11, and in particular #1975, changes how the command type is determined. It breaks some of our code by unexpectedly inferring "Stored Procedure" for a plain "SELECT * FROM Table". We found that the source code actually contained non-breaking space (ASCII 160) instead the normal space (ASCII 32). That code was working fine in the previous Dapper version 2.1.4.

This is with a connection to SQL Server.

One possibility to solve this could be to use [char.iswhitespace](https://learn.microsoft.com/en-us/dotnet/api/system.char.iswhitespace?view=net-7.0) instead of the hardcoded list of whitespace characters [CommandDefinition.cs#L113](https://github.com/DapperLib/Dapper/blob/78e1fccd7cf9c6550513f5e919a844b082995eb6/Dapper/CommandDefinition.cs#L113) ?

Thanks for your help and the work done in Dapper.

**Comment by mgravell** [comment]
The irony here is: I was actually using an "all whitespace characters" version, and changed it at the last moment. Ill change to that. For now:

- use a previous version, or
- explicitly specify the command type (this only applies if omitted), or
- use regular spaces

But: thanks for the report, will fix, probably today

**Comment by mgravell** [comment]
Proposed: revert https://github.com/DapperLib/Dapper/pull/1975/commits/78e1fccd7cf9c6550513f5e919a844b082995eb6

**Comment by mgravell** [comment]
https://github.com/DapperLib/Dapper/releases/tag/2.1.15
