### ISSUE TITLE
Error executing stored procedure with parmas of varchar type

### ISSUE THREAD

**Issue by GiuliaChesches** [DapperLib/Dapper#1988]
Hi, 
I'm getting the following error
"Error converting data type nvarchar(max) to int.
2023-10-19 StartDate
2023-10-19 EndDate
Start ConvertedDate 2023-10-19
End ConvertedDate 2023-10-19"

I'm trying to execute a stored procedure by sending some dynamic parms; the parms sent are strings; the stored procedure expects varchar type for those parms;

Here is the code that I'm trying to execute:
 var parameters = new DynamicParameters();
 parameters.Add("Code", diaryUserCode, DbType.String);
   parameters.Add("SDate", new DbString() { Value = startDate, IsAnsi = true }, DbType.AnsiString);
   parameters.Add("EDate", new DbString() { Value = endDate, IsAnsi = true }, DbType.AnsiString);
   parameters.Add("jsonResult", DbType.String, direction: ParameterDirection.Output);
   await connection.ExecuteAsync
       (procedureName, parameters, commandType: CommandType.StoredProcedure);
       
       and here is the procedure signature
       CREATE   PROCEDURE [dbo].[Test] (
	@Code VARCHAR(30)
	,@SDate VARCHAR(30)
	,@EDate VARCHAR(30)
	,@jsonResult NVARCHAR(MAX) OUTPUT
	)
AS

**Comment by mgravell** [comment]
``` diff
- parameters.Add("jsonResult", DbType.String, direction: ParameterDirection.Output);
+ parameters.Add("jsonResult", dbType: DbType.String, size: -1, direction: ParameterDirection.Output);
```
