### ISSUE TITLE
Dapper assembly started throwing exception which was not the case earlier

### ISSUE THREAD

**Issue by cjmakwana** [DapperLib/Dapper#1990]
Hello,

Our solution is a cloud native, deployed on Kubernetes cluster on Microsoft Azure. The Azure AKS cluster is on 1.26.6. However, recently we started getting the following exception. **Please note that it works perfectly well in Windows. The above issue is only for dockerized service / linux binary**.:

Unhandled exception. System.InvalidOperationException: A parameterless default constructor or one matching signature (System.Int32 Id, System.String CompanyName, System.String Currency, System.String Email, System.String PhoneNumber, System.String NodaTimeZone, System.String E164Code, System.String AirGateways, System.Int32 MembershipID, System.Boolean OwnerRecord, System.String CountryCode, System.String Country, System.String LogoPath, System.String Address) is required for <my class type>> materialization
   at Dapper.SqlMapper.GenerateDeserializerFromMap(Type, DbDataReader, Int32, Int32, Boolean, ILGenerator) in /src/Dapper/SqlMapper.cs:line 3463
   at Dapper.SqlMapper.GetTypeDeserializerImpl(Type, DbDataReader, Int32 , Int32 , Boolean ) in /src/Dapper/SqlMapper.cs:line 3294
   at Dapper.SqlMapper.TypeDeserializerCache.GetReader(DbDataReader, Int32, Int32, Boolean) in /src/Dapper/SqlMapper.TypeDeserializerCache.cs:line 151
   at Dapper.SqlMapper.TypeDeserializerCache.GetReader(Type, DbDataReader, Int32, Int32, Boolean) in /src/Dapper/SqlMapper.TypeDeserializerCache.cs:line 50
   at Dapper.SqlMapper.GetDeserializer(Type, DbDataReader, Int32, Int32, Boolean) in /src/Dapper/SqlMapper.cs:line 1945
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection, Type, CommandDefinition) in /src/Dapper/SqlMapper.Async.cs:line 442
   at <my source code file> in
 <my source code file>:line 63
   at Program.<Main>$(String[]) in <my source code file>:line 15
   at Program.<Main>(String[])

Please note that this was not the case earlier, and we have not made any deployment since long. Here, the type initialization fails as it could not find the default constructor. But we have never created any constructor for POCO entity type, and it was working well before.

**Comment by mgravell** [comment]
Happy to try to help here, but I'm going to need some help. This error suggests that your type *has* a constructor, but that it doesn't match the query. Can we perhaps see the query and type being used here? If the query involves `select *` in some form, is it possible that the column order in your database has changed due to a dB refactor (maybe changing a column type slightly), and no longer matches?


Note that we already have work completed to make re-ordering columns less brittle in this scenario, but: it is only implemented in the incomplete AOT piece.

**Comment by mgravell** [comment]
Also, are you *sure* there is no constructor? Is this perhaps a partial type? Is some other code adding the constructor? A generator maybe?

**Comment by mgravell** [comment]
As a note to myself: should we list the available/discovered .ctor signatures?

**Comment by mgravell** [comment]
Sorry to keep asking lots of questions, but did this suddenly start happening by itself, or did it change when you changed library version, or...?

**Comment by cjmakwana** [comment]
Hi @mgravell 

Yes, I am damn sure that we are not having any constructor in that class. Further, there is no query (which is in fact an SP) that has select * kind of query. We have select top 1, which always returns either no records or one only. Further, there is no change in the SQL schema of the tables associated.

**Comment by cjmakwana** [comment]
> Sorry to keep asking lots of questions, but did this suddenly start happening by itself, or did it change when you changed library version, or...?

No, we found it suddenly started. In fact, it works well with Windows. It started only in dockerized service.

**Comment by mgravell** [comment]
This is very odd. I'm intrigued, but I'm not sure how we can repro this, at least without more context/code. I'm tempted to go ahead and add more info about the available constructors, in case that helps.

Has there been any change to your deployment process? For example, do you publish as "trimmed" on the container deploy? Because if that has removed the parameterless constructor, that might explain things.

**Comment by cjmakwana** [comment]
> This is very odd. I'm intrigued, but I'm not sure how we can repro this, at least without more context/code. I'm tempted to go ahead and add more info about the available constructors, in case that helps.
> 
> Has there been any change to your deployment process? For example, do you publish as "trimmed" on the container deploy? Because if that (trimming) has removed the parameterless constructor, that might explain things.

@mgravell we are already using trimmed docker image, which we used to do since beginning, and the code worked well since then. But just a recent unknown has caused this. However, let me check with my team. Further to ask you, does introducing a trigger to the table cause such behaviour ?

**Comment by mgravell** [comment]
no, a trigger should have no effect; can I suggest adding the following, to help diagnose this?


``` c#
static string DescribeConstructors(Type type)
{
    var ctors = typeof(Foo).GetConstructors(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
    var sb = new StringBuilder("Found ").Append(ctors.Length).AppendLine(" .ctors:");
    foreach (var ctor in ctors)
    {
        var parameters = ctor.GetParameters();
        sb.Append(ctor.Attributes & (MethodAttributes.MemberAccessMask)).Append(" ").Append(type.Name).Append("(");
        for (int i = 0; i < parameters.Length; i++)
        {
            var p = parameters[i];
            if (i != 0) sb.Append(", ");
            sb.Append(p.ParameterType.Name).Append(" ").Append(p.Name);
        }
        sb.AppendLine(")");
    }
    return sb.ToString();
}
```

and doing something that writes out `DescribeConstructors` for your given type? Again, I wonder if something interesting in the build is changing the output to be different to our expectations.

**Comment by mgravell** [comment]
Btw if this *does* turn out to be a trimming problem - then that's one more thing in favor of Dapper AOT, which is nearly usable (we can't ship before net8). It fixes all trimming problems, by design.

**Comment by cjmakwana** [comment]
Hi @mgravell 

After executing the above code, I found this output:

![image](https://github.com/DapperLib/Dapper/assets/23075550/f3855e8d-8330-4f0f-8a83-28245a40a261)

**Comment by cjmakwana** [comment]
However, it's my apology, as I came to know yesterday after comparing the DB schema against the type that there was one column in DB added by my teammate, for which the attribute was not present in the C# type. However, I have already added that attribute now, and tested. However, still I am getting the same error. So should I do something more there ?

**Comment by mgravell** [comment]
> Hi @mgravell
> 
> After executing the above code, I found this output:
> 
> ![image](https://user-images.githubusercontent.com/23075550/277238275-f3855e8d-8330-4f0f-8a83-28245a40a261.png)

And that is on the system that is failing, deployed in the same way? Ok, I'm very confused. A public parameterless constructor should work absolutely fine. This still smells like trimming to me, but I'll see if we can add some more diagnostics here.

**Comment by mgravell** [comment]
> I came to know yesterday after comparing the DB schema against the type that there was one column in DB added by my teammate

This won't impact anything when a public parameterless constructor is being used. This is highly intriguing.

**Comment by cjmakwana** [comment]
@mgravell , interestingly, when I executed the same code in linux-musl-x64 runtime, I found the below result for the same code:

![image](https://github.com/DapperLib/Dapper/assets/23075550/8d274bcc-9ddb-47b7-b36a-a4144f943d3d)

**Comment by mgravell** [comment]
Ah, so this is definitely a trimming problem - at some point during build and deploy, the tooling has decided your constructor is never used (it can't see Dapper's usage, at least until we ship the AOT bits) and has stripped it completely. So: we've solved the first part of the mystery!

The trimming options in msbuild are described here:

https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options

I wonder if simply adding `<TrimMode>partial</TrimMode>` to a csproj property group section will fix this. And to repeat: the AOT tooling would also fix this, so thanks for the extra use-case scenario!

**Comment by cjmakwana** [comment]
Hi @mgravell ,

My heartful thanks for your above tip. With this, we could eliminate the issue. However, I am still curious to know on why it was working perfectly well just few weeks back, when we were having default trim mode (which is full). Please feel free to comment, or allow me to close this issue. And yes, awaiting for your next release of this package with AOT for .NET 8.0.

**Comment by mgravell** [comment]
I have absolutely no clue. I'm intrigued, but I don't know.

**Comment by cjmakwana** [comment]
Thanks @mgravell,

So I am closing this issue for now.
