### ISSUE TITLE
Issue handling properties with underscores and setters

### ISSUE THREAD

**Issue by jarrodls** [DapperLib/Dapper#1993]
I noticed an issue in 2.0.151 that I've traced down to the change in underscore handling https://github.com/DapperLib/Dapper/commit/33090c0218383411c3b25fa6cb4cbee38d0f3270. This issue did not exist on 2.0.143.

There seems to be some issue with the logic that chooses what property to map to.

If you have a class like this, the setter on DisplayName never gets called and AltName never gets set.
This only seems to happen if the property has a backing field, if that backing field **is above** the other field (Display name in this case), and if the backing field has a `{ get; set; }`.
```cs
private string _displayName { get; set; }
public string DisplayName {
    get => _displayName;
    set {
        _displayName = value;
        AltName = _displayName;
    }
}

public string AltName { get; set; }
```

If you move the backing field below `DisplayName`, the setter on `DisplayName` gets called as normal. It also works fine if you remove the `{ get; set; }` from the backing field.
So this works fine with the backing field below.
```cs
public string DisplayName {
    get => _displayName;
    set {
        _displayName = value;
        AltName = _displayName;
    }
}

private string _displayName { get; set; }
public string AltName { get; set; }
```

The query I'm doing is just something like, using Npgsql.
```cs
return conn.QueryAsync<MyClass>("SELECT display_name FROM some_table;");
```
I also have `DefaultTypeMap.MatchNamesWithUnderscores` set to true.

**Comment by mgravell** [comment]
> and if the backing field has a { get; set; }

then it isn't a backing field - it is another property; the code is already correctly preferring properties over fields (so: if you *actually* have a **field** `_displayName`, it works correctly), but this is an unexpected scenario. Let me see what we can do.

**Comment by mgravell** [comment]
fixing, but honestly: I think you should just use a field here, not a property - i.e.

``` diff
- private string _displayName { get; set; }
+private string _displayName;
```
