### ISSUE TITLE
Error executing the query using .net8 and postgres

### ISSUE THREAD

**Issue by alanbarcellos** [DapperLib/Dapper#2006]
After updating the version to .net 8, the query using the postgres provider (8.0.0) and dapper (2.1.24) shows the following error:

>    System.Data.DataException
  HResult=0x80131501
  Message=The read on this field has not consumed all of its bytes (pos: 4, len: 1140850688)
  Source=Dapper
  StackTrace:
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value)
   at Dapper.SqlMapper.<QueryImpl>d__147`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Program.Main() in C:\Repos\Postgres8\Postgres8\ConsoleApp1\Program.cs:line 31
  This exception was originally thrown at this call stack:
    [External Code]
Inner Exception 1:
InvalidOperationException: The read on this field has not consumed all of its bytes (pos: 4, len: 1140850688)

_Below is the code for reproduction and I attach the database script._
_In the previous version of the provider (7.0.6) the query runs without problem._

```c#
using Dapper;
using Npgsql;

public class Program
{
    private static readonly string Host = "localhost";
    private static readonly string User = "postgres";
    private static readonly string DBname = "postgres";
    private static readonly string Password = "secret";
    private static readonly string Port = "5432";

    public class Test
    { 
        public string name {  get; set; }
        public decimal? value1 {  get; set; }
        public decimal? value2 { get; set; }
        public decimal? value3 { get; set; }
        public decimal? value4 { get; set; }
        public decimal? value5 { get; set; }
        public decimal? value6 { get; set; }
    }

    public static void Main()
    {
        using var cnn = new NpgsqlConnection(string.Format("server={0};username={1};database={2};port={3};password={4};Include Error Detail=True",
            Host, User, DBname, Port, Password));

        cnn.Open();
        var tr = cnn.BeginTransaction();
        cnn.Execute(File.ReadAllText("insert.txt"), transaction: tr);
        tr.Commit();
        var results = cnn.Query<Test>("SELECT qtd1 as value, qtd2 as value2, qtd3 as value3, 0 as value4, 0 as Value5, 0 as Value6 from formula", tr);
    }
``` 
[insert.txt](https://github.com/DapperLib/Dapper/files/13480396/insert.txt)

**Comment by mgravell** [comment]
Does this work on .net 8, npgsql 7? If so, I suggest that this is a topic
for the npgsql folks, not Dapper

**Comment by mgravell** [comment]
I've reported and linked above. I don't think there's much more we can do from the Dapper side, except perhaps help provide a "what Dapper is using under the covers" example, but for now I think the best thing would be for you to help the npgsql folks on the above ticket, to see if together you can all get a repro and resolution.

While that happens, maybe just us the latest v7 release, which should still work fine on .NET 8

**Comment by alanbarcellos** [comment]
> Eu relacionei e coloquei um link acima. Não acho que haja muito mais que possamos fazer do lado do Dapper, exceto talvez ajudar a fornecer um exemplo "o que o Dapper está usando nos bastidores" (versão resumida: o Dapper vanilla usará GetValue por coluna, em ordem estrita das colunas); Dapper.AOT usará GetDouble digitado, GetSingle etc ou uma `<T>`leitura genérica), mas enquanto acho que a melhor coisa seria você ajudar o pessoal do npgsql no ticket acima, para ver se juntos vocês fornecem uma reprodução e uma resolução.
> 
> Enquanto isso acontece, talvez apenas use a versão v7 mais recente, que ainda deve funcionar bem no .NET 8

I will follow the open ticket for npgsql. Thanks for the feedback.
