### ISSUE TITLE
Error on Postgres `ENUM` on first run

### ISSUE THREAD

**Issue by rick-micpoint** [DapperLib/Dapper#2018]
I'm running into an issue where newly created `ENUM`s are not visible to dapper, resulting in the following exception:
```
System.InvalidCastException: 'Reading as 'System.Object' is not supported for fields having DataTypeName '.<unknown>''

Inner Exception
ArgumentException: A PostgreSQL type with the oid '0' was not found in the current database info
```

However, when running the code a second time where all tables and types already exist, everything works just fine. The following small example reproduces the issue. Comment out `dropCommand.ExecuteNonQueryAsync()` and `tableCommand.ExecuteNonQueryAsync()` after running the code once to see that everything works fine when the tables already exist:
```csharp
using Dapper;
using Npgsql;

var connection = new NpgsqlConnection("Host=127.0.0.1;Port=5432;User ID=postgres;Password=password;Database=messaging;Include Error Detail=true;");
await connection.OpenAsync();

var dropCommand = new NpgsqlCommand()
{
    Connection = connection,
    CommandText = """
        DROP TABLE IF EXISTS message;
        DROP TYPE IF EXISTS message_type;
        """
};

await dropCommand.ExecuteNonQueryAsync();

var tableCommand = new NpgsqlCommand()
{
    Connection = connection,
    CommandText = """
        CREATE TYPE message_type AS ENUM ('sms', 'email');
        CREATE TABLE message (
            id SERIAL PRIMARY KEY,
            type message_type NOT NULL
        );
        """
};

await tableCommand.ExecuteNonQueryAsync();

var queryCommand = new NpgsqlCommand()
{
    Connection = connection,
    CommandText = """
        SELECT id, type
        FROM message;
        """
};

var reader = await queryCommand.ExecuteReaderAsync();
// The offending line
var parser = reader.GetRowParser<Message>();

class Message
{
    public int Id { get; set; }
    public string? Type { get; set; }
}
```

Manual parsing the row like the following example will not result in an exception, so it appears to be a Dapper issue:
```csharp
var reader = await queryCommand.ExecuteReaderAsync();
while (await reader.ReadAsync())
{
    var message = new Message
    {
        Id = reader.GetInt32(0),
        Type = reader.GetString(1),
    };
}
```

I am using the latest version (at the time of writing) of everything:
 - Postgres 16.1
 - .NET 8
 - Dapper 2.1.24
 - Npgsql 8.0.1

**Comment by mgravell** [comment]
Dapper knows literally nothing about postgresql enums; I can only presume that this is handled internally inside Npgsql, with Npgsql building a cache of known types when needed, hence if you add types: it doesn't immediately know about it. Note that Dapper.AOT is in the process of adding more enum support (it doesn't exist today), which will use a different API rather than the `object` API; this *may* change how this works with Npgsql, hopefully for the better!

**Comment by mgravell** [comment]
To clarify: the enum handling in AOT is going to switch to using GetInt32 etc (insert appropriate type here), hence it sounds like Dapper.AOT's changes will indeed remove some overheads and problems here. That'll probably get done over the festive period.

**Comment by rick-micpoint** [comment]
Thank you for your quick response! Looks like it wasn't related to dapper after all. Calling `ReloadTypesAsync` on the connection after every migration fixes the issue.

**Comment by mgravell** [comment]
It was actually very welcome, though - it hints at some tangible side benefits to the ongoing enum work, so: yay
