### ISSUE TITLE
What is the correct way to pass a CancellationToken to QueryUnbufferedAsync?

### ISSUE THREAD

**Issue by R2D221** [DapperLib/Dapper#2019]
I'm trying to use QueryUnbufferedAsync for some queries that return tons of results, but I also want to add a Cancel button. I'm trying to implement this with a CancellationToken, but apparently QueryUnbufferedAsync does not receive a CancellationToken parameter.

I know about .WithCancellation() for IAsyncEnumerable, but I'm not sure if that would be the correct way to cancel the query in the db server.

I also tried to use a CommandDefinition, but apparently the overload that receives a CommandDefinition is private, and the public methods only ever pass a default token to the CommandDefinition.

**Comment by mgravell** [comment]
Yes, `WithCancellation`. We derer everything to there - you can see that in the `Impl` method here: https://github.com/DapperLib/Dapper/blob/4160c9f3443c1b0f4c721e65c3f50506caf5e40b/Dapper/SqlMapper.Async.cs#L1295

**Comment by R2D221** [comment]
Thanks, then it's working as I was expecting.
