### ISSUE TITLE
Output parameter type Sql BIT to C# bool not working.

### ISSUE THREAD

**Issue by alvee07** [DapperLib/Dapper#2020]
I am trying best to explain my scenario->

In MS SQL,
Stored Procedure is setting @isUpdated bit to 0/1.
```
CREATE PROCEDURE dbo.uspEditX
...
@isUpdated BIT OUTPUT
AS
...

SET @isUpdated = IIF(@@ROWCOUNT > 0, 1, 0);

...
END;

```

In ASP.NET Core web api,
A C# function body like->
```
public int Edit()
{
...
DynamicParameters param = new();
param.Add("@isUpdated", DbType.Boolean, direction: ParameterDirection.Output);

connection.execute("dbo.uspEditX", param, commandType: CommandType.StoredProcedure);

// -----------------------------START OF PROBLEM-------------------------------
var res = param.Get<bool>("@isUpdated");
// var res = param.Get<Boolean>("@isUpdated");
// -----------------------------END OF PROBLEM---------------------------------
...
return 10;
}
```

Exception message is: **Unable to cast object of type 'System.Int32' to type 'System.Boolean'.**

![image](https://github.com/DapperLib/Dapper/assets/56930077/0ff188ac-7572-4bfe-9234-80840ff038dc)

![image](https://github.com/DapperLib/Dapper/assets/56930077/8ded248e-295e-4e6a-a3b2-51e05959b490)

**NOTE**: When I query table, it retrieves the row with BIT value column and maps to C# bool/Boolean property. NO problem in this scenario.

**Comment by mgravell** [comment]
Please try:

``` c#
param.Add("@isUpdated", type: DbType.Boolean, direction: ParameterDirection.Output);
```

Right now, you're passing the enum as the value

**Comment by alvee07** [comment]
Thanks @mgravell for your help. 

Problem solved with this line of code -
`param.Add("@isUpdated", dbType: DbType.Boolean, direction: ParameterDirection.Output);`
