### ISSUE TITLE
Support for Cancellation Tokens in QueryUnbufferedAsync Overloads

### ISSUE THREAD

**Issue by walidmabdelal** [DapperLib/Dapper#2021]
### CancellationToken honoring in QueryBufferdAsync

**Summary:**

I'm working on implementing a method to asynchronously stream large sets of data from a database using Dapper's QueryUnbufferedAsync. However, I've encountered a couple of issues and areas where I believe the library could be enhanced. Specifically, I am looking for better support for cancellation tokens in QueryUnbufferedAsync and clarification on the method's internal behavior.

**Details:**

1. _Cancellation Token Support_: 
The QueryUnbufferedAsync overload don't seem to accept a CancellationToken as a parameter, although internally, a CancellationToken is instantiated and used. This design makes it unclear how to pass an external CancellationToken that could be triggered by the caller of the method.

The specific method signature I'm referring to is:

`public static IAsyncEnumerable<T> QueryUnbufferedAsync<T>(this DbConnection cnn, string sql, object? param = null, DbTransaction? transaction = null, int? commandTimeout = null, CommandType? commandType = null)`

2. _Internal Implementation_: T
he second exposed method does build a CommandDefinition type which evidently lacks the token. The overload does seem to honor the token (which would be set to "default" by the CommandDefinition initializer yielding a non-canceled state.

`return Impl(cnn, effectiveType, command, command.CancellationToken);`

3. _Best Practices and Recommendations_: 
I'm following best practices for asynchronous streaming and cancellation in a robust and scalable manner. Here's the relevant part of the code that I'm working with:

```
private Task<IAsyncEnumerable<T>> FetchQueryStreamAsync<T>(
    DbConnection connection,
    CommandDefinition command)
{
    // Current approach to get an IAsyncEnumerable
    return Task.FromResult(connection.QueryUnbufferedAsync<T>(
        sql: command.CommandText,
        param: command.Parameters,
        commandTimeout: command.CommandTimeout,
        commandType: command.CommandType));
}


    public async IAsyncEnumerable<T> QueryStoredProcedureStreamAsync<T>(
        string storedProcedure,
        object? parameters = null,
        int? commandTimeout = null,
        CommandType commandType = CommandType.StoredProcedure,
        [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
      var connection = await OpenConnectionAsync("Default", cancellationToken); // Replace "Default" with actual connection ID if needed

      var command = new CommandDefinition(
          commandText: storedProcedure,
          parameters: parameters,
          commandTimeout: commandTimeout,
          commandType: commandType,
          cancellationToken: cancellationToken);

      try
      {
        var resultStream = await ExecuteWithResiliencyPolicyAsync(
            () => FetchQueryStreamAsync<T>(connection, command),
            new Dictionary<string, object>
            {
                  { "StoredProcedure", storedProcedure },
                  { "Parameters", parameters ?? new {} }
            });

        await foreach (var item in resultStream.WithCancellation(cancellationToken))
        {
          yield return item;
        }
      }
      finally
      {
        // AGNI: Do we need to dispose of the connection here? 
        // TODO: Extreme testing is needed to determine if this is necessary.
        // Dapper is supposed to handle this for us; however, it is not clear if this is the case.
        await connection.DisposeAsync(); // Ensure the connection is disposed of after streaming is complete
      }
    }
    
```

**Comment by mgravell** [comment]
1: `IAsyncEnumerable<T>` already has an inbuilt cancellation metaphor; short version is `.WithCancellation(token)`

2: this question has come up more than once; I'm open to reconsidering it and exposing via both APIs

3: open/close should already "just work"; for disposal: `using` or `await using` should work fine, no?

**Comment by walidmabdelal** [comment]
Thank you @mgravell for your prompt and insightful response. I appreciate the clarification regarding the use of .WithCancellation(token) for IAsyncEnumerable<T> and the potential for API changes to expose cancellation more directly. It's also reassuring to know that open/close and disposal should work as expected with using or await using.

Your feedback has been incredibly helpful, and I believe it has addressed my concerns. I'll proceed with the recommendations provided and will keep an eye for future updates.

Thanks again for your assistance and the great work on this library. I'm closing this issue now.
