### ISSUE TITLE
How to make LEFT JOIN multiple records for main records with limit TOP 1 for the main table.

### ISSUE THREAD

**Issue by KostyaKov10** [DapperLib/Dapper#2027]
Hi.
I have the query with connection.QueryAsync<Main>
with new[] { typeof(User), typeof(Car) } and then User user = objects[0] as User; Car car = objects[1] as Car;

But if I need to make LEFT JOIN #Tools table and there can be 0 or 1 or 10 records to fill into List<Tool> property.
Also I have constraint to make limit for select only for main table "SELECT TOP 10" for example.
So I need the result with TOP 1 for Users but with joined relative Tools table there should be 2 records for Dapper.

In EntityFramework it will be the query with .Include(x => x.Cars).Include(x => x.Tools).Take(1)

When I am doing example with two selects to make TOP 1 inside for the main table and LEFT JOIN outside - I have an issue with duplicate columns.

How to resolve this?

-----------------
Example to check.

DROP TABLE IF EXISTS #Users
DROP TABLE IF EXISTS #Cars
DROP TABLE IF EXISTS #Tools

delete #Users
delete #Cars
delete #Tools

create table #Users (Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY, Title nvarchar(100) not null)
create table #Cars  (Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY, Title nvarchar(100) not null, UserId INT NOT NULL)
create table #Tools (Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY, Title nvarchar(100) not null, UserId INT NOT NULL)

insert into #Users(Title)         values ('u1'), ('u2')
insert into #Cars(Title, UserId)  values ('c1-u1',1), ('c2-u1', 1),('c3-u2',2), ('c4-u2', 2)
insert into #Tools(Title, UserId) values ('t1-u1',1), ('t2-u1', 1),('t3-u2',2), ('t4-u2', 2)

select * from #Users
select * from #Cars
select * from #Tools

select top 1 * from #Users u -- Here I need to get two records in select because of relative 2 records in table Cars
left join #Cars c on u.Id = c.UserId

select * from (
select top 1 * from #Users u
left join #Cars c on u.Id = c.UserId
) x -- error "The column 'Id' was specified multiple times for 'x'"
left join #Tools t on x.Id = t.UserId

**Comment by spidergeuse** [comment]
select top 1 * from #Users u
left join #Cars c on u.Id = c.UserId

That query returns multiple columns with the same name (id, title).

You could explicitly select column names (instead of using *) and give the names aliases


`SELECT
*
FROM
(
	SELECT TOP 1
		   u.Id UserId,
		   u.Title UserTitle,
		   c.Id CarId,
		   c.Title CarTitle
		   --c.UserId
	FROM #Users u
	LEFT JOIN #Cars c ON u.Id = c.UserId
) x -- error "The column 'Id' was specified multiple times for 'x'"
LEFT JOIN #Tools t ON x.UserId = t.UserId;`
