### ISSUE TITLE
Dapper QueryMultipleAsync does not pull multiple result sets

### ISSUE THREAD

**Issue by genifycom** [DapperLib/Dapper#2031]
Using SqlConnection and SqlCommand if you open the connection and perform

```
_Command.CommandText = "SET STATISTICS XML ON;"; //Actual execution plan
 _Command.ExecuteNonQuery();
_Reader = _Command.ExecuteReader();
```

then you will receive two result sets. The first (name id) is the query result. The second named "Microsoft SQL Server 2005 XML Showplan" will contain the XML of the query plan.

If you perform the same test in Dapper:

```
        using (SqlConnection _Connection = new SqlConnection(_source_connection))
        {
            await _Connection.ExecuteAsync("SET STATISTICS XML ON;"); //Actual plan request

            using (var multi = await _Connection.QueryMultipleAsync(_QueryToTest))
            {
                var tx_id = await multi.ReadAsync<Guid>();
                string plan = await multi.ReadSingleAsync<string>();
            }
        }
```
Then you do not appear to receive both result sets. After reading the first, multi.IsConsumed will be true and the second Read will fail with "System.ObjectDisposedException: 'The reader has been disposed; this can happen after all data has been consumed
Object name: 'Dapper.SqlMapper+GridReader'.'
"

**Comment by mgravell** [comment]
Curious. I'll take a peek when I get a moment. I am intrigued.

**Comment by mgravell** [comment]
Are you sure the issue isn't the `Read<Guid>`? Should that perhaps be `ReadSingle<Guid>()` ?

**Comment by mgravell** [comment]
Hmmm, no, we buffer by default, so that should be fine. I'll stop speculating, and check when I get a moment!

**Comment by genifycom** [comment]
In this case, 3 guids are returned, but I have tried a ReadSingle for another query and same result.

Thanks

**Comment by genifycom** [comment]
Any updates?

**Comment by genifycom** [comment]
Were you able to reproduce?

**Comment by mgravell** [comment]
Sorry, will take a deeper look hopefully tomorrow

**Comment by mgravell** [comment]
OK, sorry for delay, but: I took a look; short version: "I can't repro"; worked fine on both System.Data and Microsoft.Data clients, tested on net472, net6 and net8:

![image](https://github.com/DapperLib/Dapper/assets/17328/a8590e59-70f3-4835-aa25-3b7088459075)

Do you have a full repro, similar to the code in the branch above? Note that some commands *do not generate query plans* - for example `select NEWID();` doesn't.

**Comment by TSlivede** [comment]
I had the same problem. The Reason was, that I not explicitly opened the connection. In this case dapper opens the connection implicitly. However in this case the connection is also closed again before executing the next command - and that resets the `SET STATISTICS XML ON` setting.

No I explicitly call `await _Connection.OpenAsync()` before `await _Connection.ExecuteAsync("SET STATISTICS XML ON;")` and get the expected query plan.

**Comment by mgravell** [comment]
Yep, that's expected and normal; Dapper has background open/close semantics when it encounters a closed connection, but: this won't work correctly if you use anything connection-scoped. Usually this means that `#whatever` temporary tables won't exist, but it extends to other transients such as (some, not quite all) `SET` options, transactions, etc. So: I don't think there's anything to change here, except: "open the connection manually"; alternatively, include the `SET` instruction *in the same command* (assuming it isn't a stored procedure, etc)
