### ISSUE TITLE
Version 2.1.37 not in NuGet

### ISSUE THREAD

**Issue by Danchieke** [DapperLib/Dapper#2061]
The latest version of Dapper is not currently listed in the NuGet repository, the most recent listed version is 2.1.35.

I am needing the recently implemented DateOnly functionality and would rather not have to implement a workaround when the release is already published.

**Comment by mgravell** [comment]
It is there - it is just unlisted due to a problem with the other change in that release - I need to revert that change and republish

**Comment by jameswilson281** [comment]
Hi! Any update on this? Would it be better to rollback to 2.1.35 or keep running 2.1.37 (I guess it depends on how bad the "problem" you mentioned is).  Thanks!

**Comment by buzz100** [comment]
you can see the details here https://github.com/DapperLib/Dapper/issues/2056

**Comment by mgravell** [comment]
https://github.com/DapperLib/Dapper/releases/tag/2.1.42
