### ISSUE TITLE
Version 2.1.44 not listed on NuGet Package Manager

### ISSUE THREAD

**Issue by PSCBryson** [DapperLib/Dapper#2096]
Just added a new project late yesterday, and the current version 2.1.44 is not showing in NuGet Package Manager. I checked and it is not listed on the [NuGet site](https://www.nuget.org/packages/Dapper/2.1.35?_src=template#versions-body-tab) either, as I thought I might be going crazy. I am not sure if it is just a bug on NuGet or not, but figured you should be aware.

**Comment by mgravell** [comment]
K, there's a story here, but you're right: we should clarify the release and mark it as withdrawn. There was a problem with the DateOnly/TimeOnly pieces.

**Comment by PSCBryson** [comment]
Understandable. I just had already updated other projects to 2.1.44, and when creating a new one in the solution, the same version could not be found. Luckily I got it handled , but I wanted to make sure you were aware. Keep up the good work; and I will look forward to the next update.

**Comment by torbenkohlmeier** [comment]
Not only 2.1.44 was unlisted but also 2.1.42 and 2.1.37. I guess because #2050 had to be reverted? But what about #2051? That was not reverted but is now also missing. Was this on purpose?
