### ISSUE TITLE
How to replace variables within '@var' and "@var"

### ISSUE THREAD

**Issue by Coloryr** [DapperLib/Dapper#2098]
I have an SQL statement that goes like this
```
JSON_CONTAINS(mcmod_game_version->'$.Fabric', '[\"@version\"]') AND 
```
then execute the code
```
using var codeSQL = new MySqlConnection(s_str);
var list = codeSQL.Query<DataObj>(sql, new {version});
```
this will not be able to query any data, but if I use string concatenation `version`, it can work properly, this is bug?

**Comment by mgravell** [comment]
This is working exactly as expected; that's simply how string literals work in SQL. Workarounds are usually things like:

```
'[\"' + @version + '\"]'
```

however, care must still be exercises since some values of such a parameter could perform injection-like escape.

**Comment by Coloryr** [comment]
> This is working exactly as expected; that's simply how string literals work in SQL. Workarounds are usually things like:
> 
> ```
> '[\"' + @version + '\"]'
> ```
> 
> however, care must still be exercises since some values of such a parameter could perform injection-like escape.

Yes i need this.

**Comment by Coloryr** [comment]
> This is working exactly as expected; that's simply how string literals work in SQL. Workarounds are usually things like:
> 
> ```
> '[\"' + @version + '\"]'
> ```

No work, is it written like this?
```
"JSON_CONTAINS(mcmod_game_version->'$.Forge', '[\"' + @version + '\"]') AND "
```

**Comment by Coloryr** [comment]
All `SQL`
```
SELECT * FROM `mcmod` WHERE `mcmod_mod_type` LIKE @modtype AND JSON_CONTAINS(mcmod_game_version->'$.Forge', '["' + @version + '"]') AND 1 ORDER BY mcmod_update_time LIMIT @page, 20
```
And replace arg run in phpadmin
```
SELECT * FROM `mcmod` WHERE `mcmod_mod_type` LIKE '魔法' AND JSON_CONTAINS(mcmod_game_version->'$.Forge', '["1.12.2"]') AND 1 ORDER BY mcmod_update_time LIMIT 0, 20;
```
![image](https://github.com/DapperLib/Dapper/assets/26276037/aa926c2d-2ec7-4cde-824b-6bea863e7ede)

**Comment by Coloryr** [comment]
Okay, this work.
```
JSON_CONTAINS(mcmod_game_version->'$.Forge', CONCAT('[\"', @version, '\"]')) AND 
```
