### ISSUE TITLE
Documentation for Dapper.SqlBuilder

### ISSUE THREAD

**Issue by markalanevans** [DapperLib/Dapper#480]
Hey guys, do you have any docs for how to use it?

For example, how does one do:

```
Select *, TotalUsers = (Select count(*) from Users where User.UserId=Profile.UserId) 
From Profile
WHERE Profile.ProfileId = 10
```

**Comment by mgravell** [comment]
What model do you want to populate here? Do you have a Profile class with
properties that match the table, for example? And where do you want
TotalUsers to go? Are we expecting one row? Or many? I'm guessing one, and
that TotalUsers is a member of Profile, in which case:

    int profileId = 10;
    var profile = connection.QuerySingleOrDefault<Profile>(
       @"Select ...
        ...
        WHERE Profile.ProfileId=@profileId",
        new { profileId });

I hope that renders OK - am on 'phone...

**Comment by markalanevans** [comment]
Hi @mgravell thank you.

I should have been more clear. I'm wondering how you do nested select queries using the SqlBuilder.

Where in this case, there is a select query with WHERE's that are are a sub select.
