### ISSUE TITLE
DapperExtensions

### ISSUE THREAD

**Issue by znyet** [DapperLib/Dapper#582]
Hello, I am a rookie, I wrote a development based on your Dapper.
Is this written performance is good. What are the defects.

<pre>
<code>
https://github.com/znyet/DapperExtensions
</code>
</pre>

**Comment by mgravell** [comment]
Via Google translate: "Hello , I was a novice , I wrote based grow your
Dapper 's . Is this a good write performance Mody . What defects.". I will
try to take a peek later today to provide some feedback.

**Comment by NickCraver** [comment]
This one isn't something we're likely to get time to get to (just catching up in general is a struggle - going to close out for now as part of active issue cleanup.
