### ISSUE TITLE
Question about Inserting on Firebird and getting the return value on a query

### ISSUE THREAD

**Issue by dimkasta** [DapperLib/Dapper#705]
I am doing an insert on a firebird 2.5 embedded database. 
Everything seems to work ok both using query or execute Dapper methods.
But I cannot seem to get the value of the new Id using the query method of Dapper and the "returning" syntax on firebird sql.
I keep getting an exception "sequence contains no elements". And if I use FirstOrDefault I get 0 as expected.
I tried the insert sql statement directly on the server and it properly returns the new Id.

Does anyone know if this is supported for Firebird?

Thanks in advance

**Comment by unsafePtr** [comment]
You probably are not familiar with FireBird database. On insert you will never receive the id of current inserted row. To get it you can use Generics. Simple call the generic which corresponds to your table, then insert row with this id.

**Comment by dimkasta** [comment]
Thanks for the reply

As I wrote in my initial post, FireBird DOES support that since 2.0 and it is working properly for me using other clients. You can read about it here
https://firebirdsql.org/refdocs/langrefupd21-insert.html#langrefupd21-insert-returning

**Comment by unsafePtr** [comment]
@dimkasta Hi, i am now working on an old project which is with version 1.5 of FireBird, that's why i was posted such answer. Do you tried ExecuteScalar<T>? Can you provide some code if this will not help

**Comment by unsafePtr** [comment]
@dimkasta Did you solve the problem problem?

**Comment by masonwheeler** [comment]
Any progress on this issue?  I just ran into the same problem on a Firebird 3 embedded database.

**Comment by dimkasta** [comment]
Sorry for not updating. I ended up using some other approach which I do not remember right now. It still did not work for me though.

**Comment by lgabryel** [comment]
I have te same problem in Firebird 2.5. I solve it by execute scalar. 

using (IDbConnection db = DS.LockConnection(null).Connection)
{
  using (var tran = db.BeginTransaction())
  {
     var id = db.ExecuteScalar<int>("insert into <table>( <fields> ...) values (<values> ...) returning id", 
       pocoObject, tran);
  }
}

**Comment by NickCraver** [comment]
The approach @lgabryel notes above is the general pattern you'd want to use here!
