### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by jitbit** [DapperLib/Dapper#749]
Just upgraded to the most recent verison of Dapper (was previously using the very first dapper from Sam's blog post - just one c# file - for YEARS) and started getting errors like this:

Expression of type 'System.Int32' cannot be used for parameter of type 'System.Object' of method 'System.Object SetValue(System.String, System.Object)'

Steps to replicate:

```
var results = connection.Query<dynamic>("SELECT Col1, Col2 from Table");
var row = results.First();
row.NewProperty = 42; //throws error
row.Col2 = 42; //also throws error
```

**The old Dapper was free of this bug**

Have to do casting, everywhere in my code

`row.Col2 = (object)42; //temp workaround`

**Comment by mgravell** [comment]
sounds odd, and I think I saw another report of that in the last few days;
I will take a look.

**Comment by NickCraver** [comment]
Yep, #736 as well...looked at the code and nothing apparent changed there in quite some time.

@jitbit Can you let us know which version of .NET you're running on?

**Comment by jitbit** [comment]
Thanks for looking into this.

I'm targeting 4.5 (not 4.5.x, just 4.5)

The old dapper version used to return results as `FastExpando` which didn't throw the excaption, the new version returns `DapperRow` which doesn't like this.

I will fork and try to debug on my side too.

**Comment by NickCraver** [comment]
@jitbit Thanks, excellent information there - we'll take a look.

**Comment by jitbit** [comment]
I've created a simple unit-test that replicates this error:

```
[Fact]
public void TestAssignProp()
{
	using (var connection = GetOpenConnection())
	{
		var res = connection.Query("select 1 as a, 2 as b, 3 as c").First();
		res.a = 1;
	}
}
```

The expression is thown on line 35 of `DataRowMetaObject`

It does not like that the `DapperRow`'s `SetValue` method has its second parameter as `object` so it throws an exception.

I guess you need to use `Expression.Convert` first, so will add all the boxing/unboxing stuff for value-types like `int` or `bool`. But I embarrassed to say I don't know how... I'm really really bad with linq-expressions, sorry...

**Comment by jitbit** [comment]
Adding something like this to `DapperRowMetaObject.BindSetMember` will probably help:

`parameters[1] = Expression.Convert(parameters[1], typeof(object));`

It works now, the test runs just fine. But like I said, I'm a total noob with expressions. And also, I'm not familiar with your code, not sure how this will brake something else.

Thanks

**Comment by jitbit** [comment]
Any update?
