### ISSUE TITLE
Return Count 0 when sql query uses syscolumns

### ISSUE THREAD

**Issue by ghost** [DapperLib/Dapper#784]
A SQL SERVER 2008R2 SP :
SELECT TOP(19) Name AS StaffLevel FROM syscolumns WHERE id=object_id('dbo.dcmlaborrate') AND type=110

SSMS produces 19 rows.

Dapper query.read<obj> Return 0;

We have tried wrapping select in table var, cte, etc.: returns 0.  Cast StaffLevel as nvarchar(50): SSMS - 19, Dapper returns 0.  The same result set entered into a table with 19 rows returns correct count.  The only place we have 'tripped' with Dapper is this SP and the single difference is the syscolumns.  Is there metadata we don't see?

**Comment by NickCraver** [comment]
It sounds like the user your querying as doesn't have permission to see the rows. Proxying through a stored procedure works around the same access issue...so that definitely seems like what you hit here.
