### ISSUE TITLE
DefaultTypeMap.MatchNamesWithUnderscores is ignored for ctor parameters

### ISSUE THREAD

**Issue by julealgon** [DapperLib/Dapper#818]
While testing the `MatchNamesWithUnderscores` property with one of my stored procedures, I noticed that if I set it to true to ignore the underscores in my proc columns, it will map them properly into class properties, but still fail for constructor arguments using the same rule.

I'd expect the rule to be consistent across all name-mathing in the type mapper, as the toggle seems to imply it is for "all names" due to it's name, `Match ... NAMES ... WithUnderscores".

I want my model to be immutable, and now I cannot have properly named arguments in my code.

Would it be possible to fix this inconcistency by applying the same logic when trying to match constructor argument names as well?

**Comment by agjini** [comment]
maybe we could submit a PR for this change

**Comment by andreas-antoniou-cko** [comment]
Created a PR: https://github.com/StackExchange/Dapper/pull/1394

**Comment by andreas-antoniou-cko** [comment]
Is there anything more I need to do to get this PR merged? I am unsure if I missed out a step or if this is just due to everyone's time constraints.

**Comment by chrsin** [comment]
@andreas-antoniou-cko I think @NickCraver is saying it can't be added since it would break stuff.
@NickCraver would you accept a new boolean on DefaultTypeMapper that signifies if the stuff should work on constructors aswell?

This issue makes working with postgres, records and dapper a real pain. :'(

https://stackoverflow.com/questions/66624066/dapper-postgres-and-camelcase

**Comment by senritsu** [comment]
fwiw, this is still an issue and is still annoying. +1 for even an opt-in solution via some configuration option, anything would be better than having to alias all columns in result sets.

**Comment by macco3k** [comment]
Is it really so big of a deal to include the linked PR? From what I can see it looks backward compatible with the current behaviour, so this should not be breaking existing code.

**Comment by mgravell** [comment]
Completed via #1947

**Comment by mgravell** [comment]
https://github.com/DapperLib/Dapper/releases/tag/2.0.151
