### ISSUE TITLE
Bug in returned objects in multimap with custom splitOn

### ISSUE THREAD

**Issue by TroySchmidt** [DapperLib/Dapper#869]
When executing a multimapped query with custom SplitOn and the column values are repeated in base table and the related table the columns after the first appearance of the splitOn value that is the Id of the related will result in the remainder of those columns not being read by the grid.

```
SELECT TableId, RelatedId, Title, Name, RelatedId, RelatedName FROM .....
```

This will result in an entity of table with the id only and without title and name being populated.  The related information will be populated just fine (although in certain situations with more than just one relationship I have seen otherwise).

This appears to be a glitch from 1.50.2 to the newest 1.50.4 pre-release.

Workaround was to move the related properties to the end of the classes property list in the class definition.

**Comment by aasf86** [comment]
hi, i implented commands on cascade @aasf86 [dappir](https://github.com/aasf86/dappir)

**Comment by NickCraver** [comment]
The behavior here is correct - the expectation is that the columns are everything wanted for the first type, then the second, and so on. If we _didn't_ do that, a lot of ambiguity would be present for all mappings. Closing out to cleanup!
