### ISSUE TITLE
I have a query question .

### ISSUE THREAD

**Issue by Leowuqunqun** [DapperLib/Dapper#902]
this is my code ： 

sql:
SELECT a.AccountId,b.Name,b.Avatar FROM tableA LEFT JOIN tableB as b on a.Accountid = b.AccountId where a.AccountId = @AccountId
c# : 
db is a IDbConection  
db.Query<Entity.tableA,Entity.tableB,Entity.C>（sql,(a,b)=>{var c = new Entity.c ;c.property=b.property ; return c},splitOn:"Name"）

question  1.-> b is a null ,But the database   b.avatar has value ,why??
                 2.-> Func<TFirst,TSecond> ，How to assign the past from the database?

First, thank you

**Comment by Leowuqunqun** [comment]
I think my already  known why b is null , this question because spliton value is null , I think whether because spliton a value at database not null

**Comment by GertArnold** [comment]
You should use `splitOn:"AccountId"` and also select `b.AccountId` in the SQL query.

**Comment by NickCraver** [comment]
Answered above - closing out to cleanup!
