### ISSUE TITLE
Multi mapping: keep references

### ISSUE THREAD

**Issue by GertArnold** [DapperLib/Dapper#931]
Adapted from the example in the docs...
```
var sql = 
@"select * from #Posts p 
left join #Users u on u.Id = p.OwnerId 
Order by p.Id";
 
var posts = connection.Query<Post, User, Post>(sql, (post, user) => { post.Owner = user; return post;});
```
...we get a collection of `Post`s, each having a `User` object.

However, it seems that all `User` objects are new instances, even if they have the same `Id`. (Correct me if I'm wrong).

Would it be possible to materialize unique `User` objects and add the correct references in the `Post`s? It would greatly add to the usability of the object graph.

**Comment by NickCraver** [comment]
This isn't something that's supported in-box, since we're seeing _many_ users (and each _could_ be different) from the query itself. If you want a unique map, it may be better to look at a `.QueryMultiple<>` and fetch each - then hook them up in memory/code afterwards.
