### ISSUE TITLE
Scaffolding or POCO model creation

### ISSUE THREAD

**Issue by gitfortee** [DapperLib/Dapper#938]
Hello, 

Can someone please provide insights how to do POCO or DbContext code generation as it is available in entity framework.? are there any scaffolding tools available for Dapper to achieve code generation? if not, what is the option. 

thanks!

**Comment by nguyenkien** [comment]
You can try FastCrud.ModelGenerator

**Comment by NickCraver** [comment]
There's still nothing built into Dapper for this, if you need such tools we'd definitely point you at Entity Framework Core :)
